# ext_b1.py — расширения контента B1.1 и B1.2
# Каждый урок: +36 слов (vocab_extra) + 9 упражнений (exercises_extra)

EXT_B1_1 = {
  1: {  # Persönlichkeit und Charaktereigenschaften
    "vocab_extra":[
      {"de":"die Eigenschaft","ru":"свойство, черта","uz":"xususiyat"},
      {"de":"der Charakter","ru":"характер","uz":"xarakter"},
      {"de":"selbstbewusst","ru":"уверенный в себе","uz":"o'ziga ishongan"},
      {"de":"bescheiden","ru":"скромный","uz":"kamtar"},
      {"de":"ehrgeizig","ru":"честолюбивый","uz":"shijoatli"},
      {"de":"geduldig","ru":"терпеливый","uz":"sabr-toqatli"},
      {"de":"ungeduldig","ru":"нетерпеливый","uz":"sabrsiz"},
      {"de":"neugierig","ru":"любопытный","uz":"qiziquvchan"},
      {"de":"zuverlässig","ru":"надёжный","uz":"ishonchli"},
      {"de":"verantwortungsbewusst","ru":"ответственный","uz":"mas'uliyatli"},
      {"de":"gesellig","ru":"общительный","uz":"muloqotchan"},
      {"de":"introvertiert","ru":"интровертный","uz":"introvert"},
      {"de":"extrovertiert","ru":"экстравертный","uz":"ekstrovert"},
      {"de":"kreativ","ru":"творческий","uz":"ijodiy"},
      {"de":"analytisch","ru":"аналитический","uz":"analitik"},
      {"de":"empathisch","ru":"эмпатичный","uz":"empatiyali"},
      {"de":"rücksichtsvoll","ru":"внимательный к другим","uz":"e'tiborli"},
      {"de":"kritisch","ru":"критичный","uz":"tanqidiy"},
      {"de":"optimistisch","ru":"оптимистичный","uz":"optimistik"},
      {"de":"pessimistisch","ru":"пессимистичный","uz":"pessimistik"},
      {"de":"humorvoll","ru":"с чувством юмора","uz":"hazilkash"},
      {"de":"ernsthaft","ru":"серьёзный","uz":"jiddiy"},
      {"de":"sensibel","ru":"чувствительный","uz":"sezgir"},
      {"de":"pragmatisch","ru":"прагматичный","uz":"pragmatik"},
      {"de":"flexibel","ru":"гибкий","uz":"moslashuvchan"},
      {"de":"stur","ru":"упрямый","uz":"qaysar"},
      {"de":"aufgeschlossen","ru":"открытый, восприимчивый","uz":"ochiq fikrli"},
      {"de":"verschlossen","ru":"закрытый","uz":"yopiq"},
      {"de":"konfliktscheu","ru":"избегающий конфликтов","uz":"nizolardan qochadigan"},
      {"de":"durchsetzungsfähig","ru":"настойчивый","uz":"qat'iyatli"},
      {"de":"die Stärke","ru":"сила, достоинство","uz":"kuch, afzallik"},
      {"de":"die Schwäche","ru":"слабость, недостаток","uz":"zaiflik, kamchilik"},
      {"de":"das Vorbild","ru":"пример для подражания","uz":"ibrat namunasi"},
      {"de":"die Persönlichkeit","ru":"личность","uz":"shaxsiyat"},
      {"de":"der Typ","ru":"тип (человека)","uz":"inson turi"},
      {"de":"die Weltanschauung","ru":"мировоззрение","uz":"dunyoqarash"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was bedeutet 'ehrgeizig'? / 'Ehrgeizig' nima demak?",
       "opts":["ленивый / dangasa","честолюбивый / shijoatli","скромный / kamtar","терпеливый / sabr-toqatli"],"ans":1},
      {"type":"choice","q":"Какое слово означает 'надёжный'? / 'Ishonchli' qaysi so'z?",
       "opts":["sensibel","ungeduldig","zuverlässig","stur"],"ans":2},
      {"type":"choice","q":"'Introvertiert' — это человек который...? / 'Introvert' — bu ...",
       "opts":["очень общительный / juda muloqotchan","избегает общения / muloqotdan qochadi","любит спорт / sportni yaxshi ko'radi","работает ночью / kechasi ishlaydi"],"ans":1},
      {"type":"choice","q":"Wie sagt man 'открытый, восприимчивый'? / 'Ochiq fikrli' nemischa?",
       "opts":["verschlossen","aufgeschlossen","bescheiden","kreativ"],"ans":1},
      {"type":"choice","q":"'Rücksichtsvoll' bedeutet / 'Rücksichtsvoll' demak:",
       "opts":["беззаботный / beparvo","невежливый / qo'pol","внимательный к другим / e'tiborli","ленивый / dangasa"],"ans":2},
      {"type":"choice","q":"Что такое 'die Schwäche'? / 'Die Schwäche' nima?",
       "opts":["сила / kuch","слабость / zaiflik","характер / xarakter","личность / shaxsiyat"],"ans":1},
      {"type":"choice","q":"'Durchsetzungsfähig' на русском / o'zbekcha:",
       "opts":["мягкий / yumshoq","настойчивый / qat'iyatli","весёлый / quvnoq","ленивый / dangasa"],"ans":1},
      {"type":"choice","q":"Противоположность 'optimistisch' / 'Optimistisch' ning qarshisi:",
       "opts":["humorvoll","pragmatisch","pessimistisch","empathisch"],"ans":2},
      {"type":"choice","q":"'Das Vorbild' — это / 'Das Vorbild' — bu:",
       "opts":["пример для подражания / ibrat namunasi","слабость / zaiflik","характер / xarakter","мировоззрение / dunyoqarash"],"ans":0},
    ]
  },
  2: {  # Wohnen und Stadtleben
    "vocab_extra":[
      {"de":"die Miete","ru":"арендная плата","uz":"ijara haqi"},
      {"de":"der Mieter","ru":"арендатор","uz":"ijarakor"},
      {"de":"der Vermieter","ru":"арендодатель","uz":"ijaraga beruvchi"},
      {"de":"der Mietvertrag","ru":"договор аренды","uz":"ijara shartnomasi"},
      {"de":"die Nebenkosten","ru":"дополнительные расходы","uz":"qo'shimcha xarajatlar"},
      {"de":"die Kaution","ru":"залог","uz":"garov"},
      {"de":"das Wohnheim","ru":"общежитие","uz":"yotoqxona"},
      {"de":"die Wohngemeinschaft (WG)","ru":"совместное проживание","uz":"birgalikda yashash"},
      {"de":"die Eigentumswohnung","ru":"собственная квартира","uz":"o'z kvartirasi"},
      {"de":"der Altbau","ru":"старый дом (постройки)","uz":"eski bino"},
      {"de":"der Neubau","ru":"новостройка","uz":"yangi bino"},
      {"de":"das Erdgeschoss","ru":"первый этаж","uz":"birinchi qavat"},
      {"de":"der Aufzug","ru":"лифт","uz":"lift"},
      {"de":"der Keller","ru":"подвал","uz":"yerto'la"},
      {"de":"der Dachboden","ru":"чердак","uz":"cherdak"},
      {"de":"der Balkon","ru":"балкон","uz":"balkon"},
      {"de":"die Terrasse","ru":"терраса","uz":"terassa"},
      {"de":"das Grundstück","ru":"земельный участок","uz":"er uchastka"},
      {"de":"die Heizung","ru":"отопление","uz":"isitish"},
      {"de":"die Innenstadt","ru":"центр города","uz":"shahar markazi"},
      {"de":"der Vorort","ru":"пригород","uz":"shahar atrofi"},
      {"de":"das Viertel","ru":"квартал, район","uz":"kvartal, tumancha"},
      {"de":"die Nachbarschaft","ru":"соседство","uz":"qo'shnichilik"},
      {"de":"umziehen","ru":"переезжать","uz":"ko'chib o'tmoq"},
      {"de":"einrichten","ru":"обустраивать","uz":"jihozlamoq"},
      {"de":"renovieren","ru":"ремонтировать","uz":"ta'mirlamoq"},
      {"de":"kündigen","ru":"расторгать (договор)","uz":"shartnomani bekor qilmoq"},
      {"de":"vermieten","ru":"сдавать в аренду","uz":"ijaraga bermoq"},
      {"de":"mieten","ru":"снимать в аренду","uz":"ijaraga olmoq"},
      {"de":"der Lärm","ru":"шум","uz":"shovqin"},
      {"de":"ruhig","ru":"тихий","uz":"sokin"},
      {"de":"zentral gelegen","ru":"в центре, центрально расположенный","uz":"markaziy joylashgan"},
      {"de":"die Wohnfläche","ru":"жилая площадь","uz":"turar joy maydoni"},
      {"de":"das Quadratmeter (qm)","ru":"квадратный метр","uz":"kvadrat metr"},
      {"de":"der Parkplatz","ru":"парковочное место","uz":"to'xtash joyi"},
      {"de":"barrierefreiheit","ru":"доступность для инвалидов","uz":"nogironlar uchun qulay"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Kaution'? / 'Die Kaution' nima?",
       "opts":["договор аренды / ijara shartnomasi","залог / garov","арендная плата / ijara haqi","лифт / lift"],"ans":1},
      {"type":"choice","q":"'Die WG' bedeutet / 'WG' demak:",
       "opts":["собственная квартира / o'z kvartirasi","новостройка / yangi bino","совместное проживание / birgalikda yashash","чердак / cherdak"],"ans":2},
      {"type":"choice","q":"Как сказать 'переезжать'? / 'Ko'chib o'tmoq' nemischa?",
       "opts":["renovieren","vermieten","umziehen","kündigen"],"ans":2},
      {"type":"choice","q":"'Der Vermieter' — это / 'Der Vermieter' — bu:",
       "opts":["арендатор / ijarakor","арендодатель / ijaraga beruvchi","сосед / qo'shni","ремонтник / ta'mirchi"],"ans":1},
      {"type":"choice","q":"'Die Nebenkosten' — это / 'Die Nebenkosten' — bu:",
       "opts":["основная аренда / asosiy ijara","дополнительные расходы / qo'shimcha xarajatlar","залог / garov","ипотека / ipoteka"],"ans":1},
      {"type":"choice","q":"Что значит 'kündigen'? / 'Kündigen' nima demak?",
       "opts":["снимать в аренду / ijaraga olmoq","ремонтировать / ta'mirlamoq","расторгать договор / shartnomani bekor qilmoq","переезжать / ko'chib o'tmoq"],"ans":2},
      {"type":"choice","q":"'Der Altbau' — это / 'Altbau' — bu:",
       "opts":["новостройка / yangi bino","старый дом / eski bino","общежитие / yotoqxona","чердак / cherdak"],"ans":1},
      {"type":"choice","q":"'Zentral gelegen' значит / 'Zentral gelegen' demak:",
       "opts":["тихое место / sokin joy","в центре расположенный / markaziy joylashgan","дешёвое жильё / arzon uy","с лифтом / liftli"],"ans":1},
      {"type":"choice","q":"'Barrierefreiheit' означает / 'Barrierefreiheit' demak:",
       "opts":["доступность для инвалидов / nogironlar uchun qulay","красивый дизайн / chiroyli dizayn","парковочное место / to'xtash joyi","лёгкое строение / yengil qurilish"],"ans":0},
    ]
  },
  3: {  # Medien und Kommunikation
    "vocab_extra":[
      {"de":"die Meinungsfreiheit","ru":"свобода слова","uz":"so'z erkinligi"},
      {"de":"die Pressefreiheit","ru":"свобода прессы","uz":"matbuot erkinligi"},
      {"de":"die Zensur","ru":"цензура","uz":"senzura"},
      {"de":"die Manipulation","ru":"манипуляция","uz":"manipulyatsiya"},
      {"de":"die Desinformation","ru":"дезинформация","uz":"dezinformatsiya"},
      {"de":"die Fake News","ru":"фейковые новости","uz":"soxta yangiliklar"},
      {"de":"der Algorithmus","ru":"алгоритм","uz":"algoritm"},
      {"de":"die Blase","ru":"пузырь (информационный)","uz":"axborot pufagi"},
      {"de":"die Echokammer","ru":"эхо-камера","uz":"aks-sado kamerasi"},
      {"de":"der Influencer","ru":"инфлюенсер","uz":"influenser"},
      {"de":"der Podcast","ru":"подкаст","uz":"podkast"},
      {"de":"das Abonnement","ru":"подписка","uz":"obuna"},
      {"de":"der Datenschutz","ru":"защита данных","uz":"ma'lumotlarni himoya qilish"},
      {"de":"die Privatsphäre","ru":"приватность","uz":"shaxsiy hayot"},
      {"de":"das Netzwerk","ru":"сеть","uz":"tarmoq"},
      {"de":"die Plattform","ru":"платформа","uz":"platforma"},
      {"de":"der Content","ru":"контент","uz":"kontent"},
      {"de":"der Klick","ru":"клик","uz":"klik"},
      {"de":"viral gehen","ru":"стать вирусным","uz":"viral bo'lmoq"},
      {"de":"streamen","ru":"стримить","uz":"strim qilmoq"},
      {"de":"herunterladen","ru":"скачивать","uz":"yuklab olmoq"},
      {"de":"hochladen","ru":"загружать","uz":"yuklash"},
      {"de":"kommentieren","ru":"комментировать","uz":"izoh yozmoq"},
      {"de":"teilen / posten","ru":"делиться / постить","uz":"ulashish / post qilish"},
      {"de":"abonnieren","ru":"подписываться","uz":"obuna bo'lmoq"},
      {"de":"der Kommentar","ru":"комментарий","uz":"izoh"},
      {"de":"die Reichweite","ru":"охват","uz":"qamrov"},
      {"de":"der Hashtag","ru":"хэштег","uz":"xeshteg"},
      {"de":"die Benachrichtigung","ru":"уведомление","uz":"bildirishnoma"},
      {"de":"die Quelle","ru":"источник","uz":"manba"},
      {"de":"glaubwürdig","ru":"заслуживающий доверия","uz":"ishonchli"},
      {"de":"unzuverlässig","ru":"ненадёжный","uz":"ishonchsiz"},
      {"de":"kritisch hinterfragen","ru":"критически осмысливать","uz":"tanqidiy o'ylamoq"},
      {"de":"die Medienkompetenz","ru":"медиаграмотность","uz":"media savodxonlik"},
      {"de":"der Redakteur","ru":"редактор","uz":"muharrir"},
      {"de":"recherchieren","ru":"исследовать, искать информацию","uz":"tadqiq qilmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Fake News' — это / 'Fake News' — bu:",
       "opts":["настоящие новости / haqiqiy yangiliklar","фейковые новости / soxta yangiliklar","старые новости / eski yangiliklar","местные новости / mahalliy yangiliklar"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'abonnieren'? / 'Abonnieren' nima demak?",
       "opts":["скачивать / yuklab olmoq","подписываться / obuna bo'lmoq","загружать / yuklash","комментировать / izoh yozmoq"],"ans":1},
      {"type":"choice","q":"'Die Medienkompetenz' — это / 'Mediakompetensiya' — bu:",
       "opts":["медиаграмотность / media savodxonlik","скорость интернета / internet tezligi","уведомление / bildirishnoma","охват / qamrov"],"ans":0},
      {"type":"choice","q":"'Viral gehen' означает / 'Viral bo'lmoq' demak:",
       "opts":["заразиться / kasallanmoq","стать вирусным / viral bo'lmoq","отписаться / obunani bekor qilmoq","удалить аккаунт / akkauntni o'chirmoq"],"ans":1},
      {"type":"choice","q":"'Glaubwürdig' значит / 'Glaubwürdig' demak:",
       "opts":["ненадёжный / ishonchsiz","скучный / zerikarli","заслуживающий доверия / ishonchli","быстрый / tez"],"ans":2},
      {"type":"choice","q":"Что такое 'die Privatsphäre'? / 'Die Privatsphäre' nima?",
       "opts":["публичное пространство / ommaviy maydon","приватность / shaxsiy hayot","алгоритм / algoritm","редактор / muharrir"],"ans":1},
      {"type":"choice","q":"'Recherchieren' — это / 'Recherchieren' — bu:",
       "opts":["скачивать / yuklab olmoq","стримить / strim qilmoq","исследовать / tadqiq qilmoq","подписываться / obuna bo'lmoq"],"ans":2},
      {"type":"choice","q":"'Die Zensur' означает / 'Senzura' — bu:",
       "opts":["свобода слова / so'z erkinligi","цензура / senzura","источник / manba","платформа / platforma"],"ans":1},
      {"type":"choice","q":"'Kritisch hinterfragen' значит / demak:",
       "opts":["слепо верить / ko'r-ko'rona ishonmoq","критически осмысливать / tanqidiy o'ylamoq","публиковать / nashr qilmoq","загружать / yuklash"],"ans":1},
    ]
  },
  4: {  # Arbeit und Beruf — Karriere
    "vocab_extra":[
      {"de":"die Gehaltserhöhung","ru":"повышение зарплаты","uz":"maosh oshirish"},
      {"de":"die Beförderung","ru":"повышение в должности","uz":"lavozimga ko'tarish"},
      {"de":"die Kündigung","ru":"увольнение","uz":"ishdan bo'shatish"},
      {"de":"die Eigenkündigung","ru":"увольнение по собственному желанию","uz":"o'z xohishi bilan ketish"},
      {"de":"der Aufstieg","ru":"карьерный рост","uz":"martaba o'sishi"},
      {"de":"die Fähigkeit","ru":"способность, умение","uz":"qobiliyat, mahorat"},
      {"de":"die Kompetenz","ru":"компетенция","uz":"kompetentsiya"},
      {"de":"die Weiterbildung","ru":"повышение квалификации","uz":"malakani oshirish"},
      {"de":"das Vorstellungsgespräch","ru":"собеседование","uz":"suhbat (ishga qabul)"},
      {"de":"der Lebenslauf","ru":"резюме","uz":"rezyume"},
      {"de":"das Arbeitszeugnis","ru":"рекомендательное письмо","uz":"tavsiya xati"},
      {"de":"die Probezeit","ru":"испытательный срок","uz":"sinov muddati"},
      {"de":"der Arbeitsvertrag","ru":"трудовой договор","uz":"mehnat shartnomasi"},
      {"de":"die Überstunde","ru":"сверхурочная работа","uz":"qo'shimcha ish vaqti"},
      {"de":"das Homeoffice","ru":"удалённая работа","uz":"uydan ishlash"},
      {"de":"die Selbstständigkeit","ru":"самозанятость","uz":"o'z-o'zini ish bilan ta'minlash"},
      {"de":"der Freelancer","ru":"фрилансер","uz":"frilanser"},
      {"de":"das Netzwerken","ru":"налаживание связей","uz":"aloqalar o'rnatish"},
      {"de":"die Arbeitslosenversicherung","ru":"страховка от безработицы","uz":"ishsizlikdan sug'urta"},
      {"de":"die Rente","ru":"пенсия","uz":"pensiya"},
      {"de":"das Gehalt","ru":"зарплата (оклад)","uz":"maosh (oylik)"},
      {"de":"der Lohn","ru":"зарплата (почасовая)","uz":"maosh (soatbay)"},
      {"de":"die Arbeitsstelle","ru":"рабочее место","uz":"ish joyi"},
      {"de":"die Branche","ru":"отрасль","uz":"soha"},
      {"de":"die Abteilung","ru":"отдел","uz":"bo'lim"},
      {"de":"der Kollege / die Kollegin","ru":"коллега","uz":"hamkasb"},
      {"de":"der Vorgesetzte","ru":"начальник, руководитель","uz":"rahbar"},
      {"de":"die Besprechung","ru":"совещание","uz":"kengash, yig'ilish"},
      {"de":"die Deadline","ru":"дедлайн","uz":"muddat (deadline)"},
      {"de":"das Projekt","ru":"проект","uz":"loyiha"},
      {"de":"delegieren","ru":"делегировать","uz":"vakolat bermoq"},
      {"de":"motivieren","ru":"мотивировать","uz":"motivatsiya bermoq"},
      {"de":"kündigen","ru":"увольнять / увольняться","uz":"ishdan bo'shatmoq"},
      {"de":"bewerben (sich)","ru":"подавать заявку","uz":"ariza bermoq"},
      {"de":"verhandeln","ru":"вести переговоры","uz":"muzokaralar olib bormoq"},
      {"de":"einstellen","ru":"принимать на работу","uz":"ishga qabul qilmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Gehaltserhöhung' — это / bu:",
       "opts":["повышение зарплаты / maosh oshirish","увольнение / ishdan bo'shatish","испытательный срок / sinov muddati","рабочее место / ish joyi"],"ans":0},
      {"type":"choice","q":"Was ist 'das Vorstellungsgespräch'? / 'Vorstellungsgespräch' nima?",
       "opts":["резюме / rezyume","собеседование / suhbat","рекомендательное письмо / tavsiya xati","трудовой договор / mehnat shartnomasi"],"ans":1},
      {"type":"choice","q":"'Sich bewerben' означает / demak:",
       "opts":["увольняться / ishdan ketmoq","подавать заявку / ariza bermoq","делегировать / vakolat bermoq","вести переговоры / muzokaralar olib bormoq"],"ans":1},
      {"type":"choice","q":"'Die Probezeit' — это / bu:",
       "opts":["отпуск / ta'til","сверхурочные / qo'shimcha ish vaqti","испытательный срок / sinov muddati","пенсия / pensiya"],"ans":2},
      {"type":"choice","q":"Что такое 'der Freelancer'? / 'Frilanser' nima?",
       "opts":["государственный служащий / davlat xodimi","фрилансер / frilanser","пенсионер / pensioner","начальник / rahbar"],"ans":1},
      {"type":"choice","q":"'Delegieren' значит / demak:",
       "opts":["мотивировать / motivatsiya bermoq","делегировать / vakolat bermoq","уволить / ishdan bo'shatmoq","нанять / ishga qabul qilmoq"],"ans":1},
      {"type":"choice","q":"'Der Vorgesetzte' — это / bu:",
       "opts":["коллега / hamkasb","стажёр / o'quvchi","начальник / rahbar","клиент / mijoz"],"ans":2},
      {"type":"choice","q":"'Die Weiterbildung' означает / demak:",
       "opts":["школьное образование / maktab ta'limi","повышение квалификации / malakani oshirish","начальное образование / boshlang'ich ta'lim","отдых / dam olish"],"ans":1},
      {"type":"choice","q":"'Verhandeln' — это / bu:",
       "opts":["принимать на работу / ishga qabul qilmoq","вести переговоры / muzokaralar olib bormoq","уволить / ishdan bo'shatmoq","работать удалённо / uydan ishlash"],"ans":1},
    ]
  },
  5: {  # Gesellschaft und soziale Fragen
    "vocab_extra":[
      {"de":"die Gesellschaft","ru":"общество","uz":"jamiyat"},
      {"de":"die Gleichstellung","ru":"равноправие","uz":"tenglik"},
      {"de":"die Diskriminierung","ru":"дискриминация","uz":"kamsitish"},
      {"de":"die Integration","ru":"интеграция","uz":"integratsiya"},
      {"de":"die Migration","ru":"миграция","uz":"migratsiya"},
      {"de":"der Migrant / die Migrantin","ru":"мигрант","uz":"migrant"},
      {"de":"der Flüchtling","ru":"беженец","uz":"qochqin"},
      {"de":"das Asyl","ru":"убежище","uz":"boshpana"},
      {"de":"die Vielfalt","ru":"разнообразие","uz":"xilma-xillik"},
      {"de":"die Toleranz","ru":"толерантность","uz":"bag'rikenglik"},
      {"de":"der Vorurteil","ru":"предрассудок","uz":"xurofot"},
      {"de":"das Klischee","ru":"клише, стереотип","uz":"klishe, stereotip"},
      {"de":"die Armut","ru":"бедность","uz":"qashshoqlik"},
      {"de":"der Reichtum","ru":"богатство","uz":"boylik"},
      {"de":"die Schere (soziale)","ru":"социальное расслоение","uz":"ijtimoiy tabaqalanish"},
      {"de":"das Ehrenamt","ru":"волонтёрство, общественная служба","uz":"ko'ngilli xizmat"},
      {"de":"die Solidarität","ru":"солидарность","uz":"birdamlik"},
      {"de":"das Gemeinwohl","ru":"общественное благо","uz":"jamoat farovonligi"},
      {"de":"die Partizipation","ru":"участие (в жизни общества)","uz":"ishtirok etish"},
      {"de":"die Inklusion","ru":"инклюзия","uz":"inklyuziya"},
      {"de":"der Zusammenhalt","ru":"сплочённость","uz":"hamjihatlik"},
      {"de":"das Engagement","ru":"активное участие","uz":"faollik"},
      {"de":"die Norm","ru":"норма","uz":"norma"},
      {"de":"der Wert","ru":"ценность","uz":"qadriyat"},
      {"de":"die Pflicht","ru":"обязанность","uz":"majburiyat"},
      {"de":"das Recht","ru":"право","uz":"huquq"},
      {"de":"der Bürger / die Bürgerin","ru":"гражданин","uz":"fuqaro"},
      {"de":"die Demokratie","ru":"демократия","uz":"demokratiya"},
      {"de":"die Gerechtigkeit","ru":"справедливость","uz":"adolat"},
      {"de":"die Ungleichheit","ru":"неравенство","uz":"tengsizlik"},
      {"de":"benachteiligt","ru":"находящийся в невыгодном положении","uz":"imkoniyati cheklangan"},
      {"de":"bevorzugt","ru":"привилегированный","uz":"imtiyozli"},
      {"de":"marginalisiert","ru":"маргинализированный","uz":"chetga surilgan"},
      {"de":"die Chancengleichheit","ru":"равные возможности","uz":"teng imkoniyatlar"},
      {"de":"das Sozialsystem","ru":"система социального обеспечения","uz":"ijtimoiy ta'minot tizimi"},
      {"de":"die Sozialhilfe","ru":"социальная помощь","uz":"ijtimoiy yordam"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Toleranz' — это / bu:",
       "opts":["дискриминация / kamsitish","толерантность / bag'rikenglik","бедность / qashshoqlik","предрассудок / xurofot"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'der Flüchtling'? / 'Qochqin' nemischa?",
       "opts":["мигрант / migrant","беженец / qochqin","гражданин / fuqaro","волонтёр / ko'ngilli"],"ans":1},
      {"type":"choice","q":"'Die Vielfalt' означает / demak:",
       "opts":["единство / birlik","разнообразие / xilma-xillik","бедность / qashshoqlik","право / huquq"],"ans":1},
      {"type":"choice","q":"'Das Ehrenamt' — это / bu:",
       "opts":["платная должность / pullik lavozim","волонтёрство / ko'ngilli xizmat","государственная служба / davlat xizmati","пенсия / pensiya"],"ans":1},
      {"type":"choice","q":"'Die Gerechtigkeit' значит / demak:",
       "opts":["несправедливость / adolatsizlik","справедливость / adolat","неравенство / tengsizlik","привилегия / imtiyoz"],"ans":1},
      {"type":"choice","q":"'Benachteiligt' — это человек / bu odam:",
       "opts":["привилегированный / imtiyozli","в невыгодном положении / nochor ahvoldagi","богатый / boy","влиятельный / nufuzli"],"ans":1},
      {"type":"choice","q":"'Die Chancengleichheit' — это / bu:",
       "opts":["равные возможности / teng imkoniyatlar","социальная помощь / ijtimoiy yordam","общественное благо / jamoat farovonligi","сплочённость / hamjihatlik"],"ans":0},
      {"type":"choice","q":"'Die Solidarität' означает / demak:",
       "opts":["конкуренция / raqobat","солидарность / birdamlik","индивидуализм / individualizm","безразличие / befarqlik"],"ans":1},
      {"type":"choice","q":"'Die Integration' в контексте общества — это / jamiyat kontekstida bu:",
       "opts":["разделение / ajralish","интеграция / integratsiya","изоляция / izolyatsiya","дискриминация / kamsitish"],"ans":1},
    ]
  },
  6: {  # Umwelt und Nachhaltigkeit
    "vocab_extra":[
      {"de":"die Nachhaltigkeit","ru":"устойчивое развитие","uz":"barqaror rivojlanish"},
      {"de":"der Klimawandel","ru":"изменение климата","uz":"iqlim o'zgarishi"},
      {"de":"die Erderwärmung","ru":"глобальное потепление","uz":"global isish"},
      {"de":"der Treibhauseffekt","ru":"парниковый эффект","uz":"issiqxona effekti"},
      {"de":"das Treibhausgas","ru":"парниковый газ","uz":"issiqxona gazi"},
      {"de":"der CO2-Ausstoß","ru":"выброс CO2","uz":"CO2 chiqindilari"},
      {"de":"erneuerbare Energien","ru":"возобновляемые источники энергии","uz":"qayta tiklanadigan energiya"},
      {"de":"die Solarenergie","ru":"солнечная энергия","uz":"quyosh energiyasi"},
      {"de":"die Windenergie","ru":"ветровая энергия","uz":"shamol energiyasi"},
      {"de":"die Biomasse","ru":"биомасса","uz":"biomassa"},
      {"de":"die Energiewende","ru":"энергетический переход","uz":"energetik o'tish"},
      {"de":"der Atomausstieg","ru":"отказ от ядерной энергии","uz":"yadro energiyasidan voz kechish"},
      {"de":"der Müll / Abfall","ru":"мусор, отходы","uz":"axlat, chiqindi"},
      {"de":"recyceln","ru":"перерабатывать","uz":"qayta ishlash"},
      {"de":"der Kompost","ru":"компост","uz":"kompost"},
      {"de":"die Plastiktüte","ru":"пластиковый пакет","uz":"plastik sumka"},
      {"de":"biologisch abbaubar","ru":"биологически разлагаемый","uz":"biologik parchalanuvchi"},
      {"de":"der Wasserverbrauch","ru":"потребление воды","uz":"suv sarfi"},
      {"de":"die Dürre","ru":"засуха","uz":"qurg'oqchilik"},
      {"de":"die Überschwemmung","ru":"наводнение","uz":"suv toshqini"},
      {"de":"der Artenschutz","ru":"защита видов","uz":"turlarni himoya qilish"},
      {"de":"die Artenvielfalt","ru":"биоразнообразие","uz":"biologik xilma-xillik"},
      {"de":"der Wald / die Abholzung","ru":"лес / вырубка леса","uz":"o'rmon / o'rmon kesish"},
      {"de":"der Fußabdruck (CO2)","ru":"углеродный след","uz":"uglerod izi"},
      {"de":"verbrauchen","ru":"потреблять","uz":"sarflamoq"},
      {"de":"sparen","ru":"экономить","uz":"tejash"},
      {"de":"schützen","ru":"защищать","uz":"himoya qilmoq"},
      {"de":"verschmutzen","ru":"загрязнять","uz":"ifloslantirmoq"},
      {"de":"die Umweltverschmutzung","ru":"загрязнение окружающей среды","uz":"atrof-muhit ifloslanishi"},
      {"de":"der Naturschutz","ru":"охрана природы","uz":"tabiatni muhofaza qilish"},
      {"de":"ökologisch","ru":"экологичный","uz":"ekologik"},
      {"de":"nachhaltig","ru":"устойчивый","uz":"barqaror"},
      {"de":"klimaneutral","ru":"климатически нейтральный","uz":"iqlim neytral"},
      {"de":"die Petition","ru":"петиция","uz":"ariza (petitsiya)"},
      {"de":"demonstrieren","ru":"демонстрировать, протестовать","uz":"namoyish qilmoq"},
      {"de":"der Aktivismus","ru":"активизм","uz":"aktivizm"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Der Klimawandel' — это / bu:",
       "opts":["изменение климата / iqlim o'zgarishi","загрязнение воздуха / havo ifloslanishi","вырубка леса / o'rmon kesish","солнечная энергия / quyosh energiyasi"],"ans":0},
      {"type":"choice","q":"'Erneuerbare Energien' значит / demak:",
       "opts":["ядерная энергия / yadro energiyasi","традиционное топливо / an'anaviy yoqilg'i","возобновляемая энергия / qayta tiklanadigan energiya","электричество / elektr"],"ans":2},
      {"type":"choice","q":"'Recyceln' — это / bu:",
       "opts":["загрязнять / ifloslantirmoq","перерабатывать / qayta ishlash","сжигать / yoqib yubormoq","захоронить / ko'mmoq"],"ans":1},
      {"type":"choice","q":"Was ist 'die Erderwärmung'? / 'Erderwärmung' nima?",
       "opts":["засуха / qurg'oqchilik","наводнение / suv toshqini","глобальное потепление / global isish","парниковый газ / issiqxona gazi"],"ans":2},
      {"type":"choice","q":"'Nachhaltig' означает / demak:",
       "opts":["загрязняющий / ifloslaydigan","быстрый / tez","устойчивый / barqaror","дорогой / qimmat"],"ans":2},
      {"type":"choice","q":"'Der Artenschutz' — это / bu:",
       "opts":["защита видов / turlarni himoya qilish","охрана леса / o'rmonni muhofaza qilish","переработка мусора / axlatni qayta ishlash","экономия воды / suv tejash"],"ans":0},
      {"type":"choice","q":"'Der CO2-Ausstoß' — это / bu:",
       "opts":["поглощение CO2 / CO2 yutish","выброс CO2 / CO2 chiqindilari","уменьшение CO2 / CO2 kamayishi","нейтрализация CO2 / CO2 neytrallanishi"],"ans":1},
      {"type":"choice","q":"'Klimaneutral' значит / demak:",
       "opts":["загрязняющий климат / iqlimni ifloslaydigan","климатически нейтральный / iqlim neytral","изменяющий климат / iqlimni o'zgartiruvchi","холодный климат / sovuq iqlim"],"ans":1},
      {"type":"choice","q":"'Die Artenvielfalt' — это / bu:",
       "opts":["вымирание видов / turlarning yo'qolishi","один вид / bitta tur","биоразнообразие / biologik xilma-xillik","климатические изменения / iqlim o'zgarishi"],"ans":2},
    ]
  },
  7: {  # Gesundheit und Medizin
    "vocab_extra":[
      {"de":"die Diagnose","ru":"диагноз","uz":"tashxis"},
      {"de":"die Therapie","ru":"терапия","uz":"terapiya"},
      {"de":"die Operation","ru":"операция","uz":"operatsiya"},
      {"de":"der Eingriff","ru":"вмешательство","uz":"aralashuv"},
      {"de":"die Rehabilitation","ru":"реабилитация","uz":"reabilitatsiya"},
      {"de":"die Prävention","ru":"профилактика","uz":"profilaktika"},
      {"de":"der Impfstoff","ru":"вакцина","uz":"vaktsina"},
      {"de":"die Impfung","ru":"вакцинация","uz":"emlash"},
      {"de":"die Nebenwirkung","ru":"побочный эффект","uz":"yon ta'sir"},
      {"de":"das Medikament","ru":"лекарство","uz":"dori"},
      {"de":"das Rezept","ru":"рецепт","uz":"retsept"},
      {"de":"die Krankenkasse","ru":"страховая касса","uz":"sug'urta kassasi"},
      {"de":"der Hausarzt","ru":"участковый врач","uz":"mahalla shifokori"},
      {"de":"der Facharzt","ru":"врач-специалист","uz":"mutaxassis shifokor"},
      {"de":"die Notaufnahme","ru":"скорая помощь / приёмный покой","uz":"tez yordam qabuli"},
      {"de":"stationär","ru":"стационарный","uz":"statsionar"},
      {"de":"ambulant","ru":"амбулаторный","uz":"ambulatoriya"},
      {"de":"chronisch","ru":"хронический","uz":"surunkali"},
      {"de":"akut","ru":"острый, острый (о болезни)","uz":"o'tkir"},
      {"de":"psychisch","ru":"психический","uz":"psixik"},
      {"de":"körperlich","ru":"физический","uz":"jismoniy"},
      {"de":"die Überweisung","ru":"направление (к врачу)","uz":"yo'llanma"},
      {"de":"der Befund","ru":"результат обследования","uz":"tekshiruv natijasi"},
      {"de":"die Blutuntersuchung","ru":"анализ крови","uz":"qon tahlili"},
      {"de":"der Blutdruck","ru":"кровяное давление","uz":"qon bosimi"},
      {"de":"das Herzrasen","ru":"учащённое сердцебиение","uz":"yurak tezlashishi"},
      {"de":"der Schlaganfall","ru":"инсульт","uz":"insult"},
      {"de":"der Herzinfarkt","ru":"инфаркт","uz":"infarkt"},
      {"de":"der Diabetes","ru":"диабет","uz":"diabet"},
      {"de":"die Allergie","ru":"аллергия","uz":"allergiya"},
      {"de":"das Burnout","ru":"выгорание","uz":"burnout (charchash)"},
      {"de":"der Stress","ru":"стресс","uz":"stress"},
      {"de":"die Entspannung","ru":"расслабление","uz":"dam olish, relaksatsiya"},
      {"de":"die Schlafstörung","ru":"нарушение сна","uz":"uyqu buzilishi"},
      {"de":"seelisch","ru":"душевный","uz":"ma'naviy, ruhiy"},
      {"de":"gesund leben","ru":"вести здоровый образ жизни","uz":"sog'lom hayot kechirmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Diagnose' — это / bu:",
       "opts":["терапия / terapiya","диагноз / tashxis","операция / operatsiya","реабилитация / reabilitatsiya"],"ans":1},
      {"type":"choice","q":"'Die Impfung' означает / demak:",
       "opts":["анализ крови / qon tahlili","вакцинация / emlash","операция / operatsiya","диагноз / tashxis"],"ans":1},
      {"type":"choice","q":"'Chronisch' — это болезнь которая / bu kasallik:",
       "opts":["острая, внезапная / o'tkir, to'satdan","хроническая / surunkali","лёгкая / yengil","временная / vaqtinchalik"],"ans":1},
      {"type":"choice","q":"'Der Facharzt' — это / bu:",
       "opts":["участковый врач / mahalla shifokori","врач-специалист / mutaxassis shifokor","хирург / jarroh","медсестра / hamshira"],"ans":1},
      {"type":"choice","q":"'Stationär' означает / demak:",
       "opts":["амбулаторный / ambulatoriya","стационарный / statsionar","домашний / uy sharoitidagi","срочный / shoshilinch"],"ans":1},
      {"type":"choice","q":"'Das Burnout' — это / bu:",
       "opts":["перелом / suyak sinishi","выгорание / charchash sindromu","аллергия / allergiya","инфаркт / infarkt"],"ans":1},
      {"type":"choice","q":"'Die Nebenwirkung' — это / bu:",
       "opts":["основной эффект / asosiy ta'sir","побочный эффект / yon ta'sir","рецепт / retsept","диагноз / tashxis"],"ans":1},
      {"type":"choice","q":"'Ambulant' — лечение которое / davolash bu:",
       "opts":["стационарное / statsionar","в больнице / kasalxonada","амбулаторное / ambulatoriya","хирургическое / jarrohlik"],"ans":2},
      {"type":"choice","q":"'Der Blutdruck' — это / bu:",
       "opts":["анализ крови / qon tahlili","кровяное давление / qon bosimi","сердцебиение / yurak urishi","нарушение сна / uyqu buzilishi"],"ans":1},
    ]
  },
  8: {  # Bildung und lebenslanges Lernen
    "vocab_extra":[
      {"de":"das lebenslanges Lernen","ru":"обучение на протяжении всей жизни","uz":"umrbod o'qish"},
      {"de":"die Hochschulreife","ru":"аттестат зрелости","uz":"oliy maktabga kirish huquqi"},
      {"de":"das Abitur","ru":"аттестат / выпускной экзамен","uz":"attestat (Abitur)"},
      {"de":"der Studiengang","ru":"направление обучения","uz":"ta'lim yo'nalishi"},
      {"de":"der Bachelor","ru":"бакалавр","uz":"bakalavr"},
      {"de":"der Master","ru":"магистр","uz":"magistr"},
      {"de":"die Doktorarbeit","ru":"докторская диссертация","uz":"doktorlik dissertatsiyasi"},
      {"de":"das Stipendium","ru":"стипендия","uz":"stipendiya"},
      {"de":"die Immatrikulation","ru":"зачисление в вуз","uz":"universitetga qabul"},
      {"de":"die Exmatrikulation","ru":"отчисление из вуза","uz":"universitetdan chiqarish"},
      {"de":"die Vorlesung","ru":"лекция","uz":"ma'ruza"},
      {"de":"das Seminar","ru":"семинар","uz":"seminar"},
      {"de":"die Hausarbeit","ru":"курсовая работа","uz":"kurs ishi"},
      {"de":"die Prüfung","ru":"экзамен","uz":"imtihon"},
      {"de":"bestehen","ru":"сдать (экзамен)","uz":"topshirmoq (imtihon)"},
      {"de":"durchfallen","ru":"провалить (экзамен)","uz":"yiqilmoq (imtihonda)"},
      {"de":"wiederholen","ru":"пересдавать","uz":"qayta topshirmoq"},
      {"de":"der Abschluss","ru":"диплом, окончание","uz":"diplom, yakunlash"},
      {"de":"die Ausbildung","ru":"профессиональное обучение","uz":"kasbiy ta'lim"},
      {"de":"der Ausbilder","ru":"наставник, инструктор","uz":"murabbiy"},
      {"de":"die Berufsschule","ru":"профессиональное училище","uz":"kasb-hunar maktabi"},
      {"de":"die Umschulung","ru":"переквалификация","uz":"qayta tayyorlash"},
      {"de":"das Lernziel","ru":"цель обучения","uz":"o'qish maqsadi"},
      {"de":"die Lernstrategie","ru":"стратегия обучения","uz":"o'qish strategiyasi"},
      {"de":"die Lernmotivation","ru":"мотивация к учёбе","uz":"o'qishga motivatsiya"},
      {"de":"der Fernkurs","ru":"дистанционный курс","uz":"masofaviy kurs"},
      {"de":"der Präsenzkurs","ru":"очный курс","uz":"kunduzgi kurs"},
      {"de":"das E-Learning","ru":"электронное обучение","uz":"elektron ta'lim"},
      {"de":"zertifiziert","ru":"сертифицированный","uz":"sertifikatlangan"},
      {"de":"akkreditiert","ru":"аккредитованный","uz":"akkreditatsiyalangan"},
      {"de":"das Zeugnis","ru":"свидетельство, аттестат","uz":"guvohnoma"},
      {"de":"die Note / die Zensur","ru":"оценка","uz":"baho"},
      {"de":"bestehen / durchfallen","ru":"сдать / провалить","uz":"topshirmoq / yiqilmoq"},
      {"de":"fördern","ru":"поощрять, содействовать","uz":"rag'batlantirmoq"},
      {"de":"die Bildungschance","ru":"возможность получить образование","uz":"ta'lim olish imkoniyati"},
      {"de":"die Schulpflicht","ru":"обязательное образование","uz":"majburiy ta'lim"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Das Abitur' — это / bu:",
       "opts":["вступительный экзамен / kirish imtihoni","выпускной аттестат / mezun attestati","стипендия / stipendiya","диссертация / dissertatsiya"],"ans":1},
      {"type":"choice","q":"'Durchfallen' при экзамене означает / imtihonda demak:",
       "opts":["сдать экзамен / imtihon topshirmoq","провалить экзамен / imtihonda yiqilmoq","пересдать / qayta topshirmoq","пропустить / o'tkazib yubormoq"],"ans":1},
      {"type":"choice","q":"'Das Stipendium' — это / bu:",
       "opts":["диплом / diplom","стипендия / stipendiya","лекция / ma'ruza","семинар / seminar"],"ans":1},
      {"type":"choice","q":"'Die Berufsschule' — это / bu:",
       "opts":["университет / universitet","профессиональное училище / kasb-hunar maktabi","начальная школа / boshlang'ich maktab","вечерняя школа / kechki maktab"],"ans":1},
      {"type":"choice","q":"'Die Umschulung' означает / demak:",
       "opts":["повышение квалификации / malakani oshirish","переквалификация / qayta tayyorlash","зачисление / qabul","окончание / yakunlash"],"ans":1},
      {"type":"choice","q":"'Bestehen' (экзамен) — это / bu:",
       "opts":["провалить / yiqilmoq","пропустить / o'tkazib yubormoq","сдать / topshirmoq","отменить / bekor qilmoq"],"ans":2},
      {"type":"choice","q":"'Die Vorlesung' в университете — это / bu:",
       "opts":["семинар / seminar","лекция / ma'ruza","экзамен / imtihon","курсовая работа / kurs ishi"],"ans":1},
      {"type":"choice","q":"'E-Learning' означает / demak:",
       "opts":["очное обучение / kunduzgi o'qish","самостоятельное обучение / mustaqil o'qish","электронное обучение / elektron ta'lim","частное обучение / xususiy o'qish"],"ans":2},
      {"type":"choice","q":"'Die Schulpflicht' — это / bu:",
       "opts":["право на образование / ta'lim olish huquqi","обязательное образование / majburiy ta'lim","государственные экзамены / davlat imtihonlari","бесплатное образование / bepul ta'lim"],"ans":1},
    ]
  },
}

EXT_B1_2 = {
  1: {  # Globalisierung und Wirtschaft
    "vocab_extra":[
      {"de":"die Globalisierung","ru":"глобализация","uz":"globalizatsiya"},
      {"de":"der Weltmarkt","ru":"мировой рынок","uz":"jahon bozori"},
      {"de":"der Freihandel","ru":"свободная торговля","uz":"erkin savdo"},
      {"de":"der Protektionismus","ru":"протекционизм","uz":"protektsionizm"},
      {"de":"der Zoll","ru":"таможенная пошлина","uz":"bojxona to'lovi"},
      {"de":"die Lieferkette","ru":"цепочка поставок","uz":"ta'minot zanjiri"},
      {"de":"die Produktion","ru":"производство","uz":"ishlab chiqarish"},
      {"de":"der Export","ru":"экспорт","uz":"eksport"},
      {"de":"der Import","ru":"импорт","uz":"import"},
      {"de":"die Inflation","ru":"инфляция","uz":"inflyatsiya"},
      {"de":"die Rezession","ru":"рецессия","uz":"retsessiya"},
      {"de":"das Wirtschaftswachstum","ru":"экономический рост","uz":"iqtisodiy o'sish"},
      {"de":"das Bruttoinlandsprodukt (BIP)","ru":"валовой внутренний продукт (ВВП)","uz":"yalpi ichki mahsulot (YaIM)"},
      {"de":"der Wechselkurs","ru":"обменный курс","uz":"valyuta kursi"},
      {"de":"die Währung","ru":"валюта","uz":"valyuta"},
      {"de":"die Investition","ru":"инвестиция","uz":"investitsiya"},
      {"de":"der Aktienmarkt","ru":"фондовый рынок","uz":"fond bozori"},
      {"de":"das Startup","ru":"стартап","uz":"startap"},
      {"de":"die Innovation","ru":"инновация","uz":"innovatsiya"},
      {"de":"der Unternehmer","ru":"предприниматель","uz":"tadbirkor"},
      {"de":"die Konkurrenz","ru":"конкуренция","uz":"raqobat"},
      {"de":"das Monopol","ru":"монополия","uz":"monopoliya"},
      {"de":"der Verbraucher","ru":"потребитель","uz":"iste'molchi"},
      {"de":"der Anbieter","ru":"поставщик, провайдер","uz":"ta'minotchi"},
      {"de":"das Angebot","ru":"предложение (товаров)","uz":"taklif"},
      {"de":"die Nachfrage","ru":"спрос","uz":"talab"},
      {"de":"die Wirtschaftskrise","ru":"экономический кризис","uz":"iqtisodiy inqiroz"},
      {"de":"die Arbeitslosigkeit","ru":"безработица","uz":"ishsizlik"},
      {"de":"das soziale Netz","ru":"социальная сеть безопасности","uz":"ijtimoiy ta'minot tizimi"},
      {"de":"fair trade","ru":"честная торговля","uz":"adolatli savdo"},
      {"de":"der Börsenkurs","ru":"биржевой курс","uz":"birja kursi"},
      {"de":"multinational","ru":"многонациональный","uz":"ko'p millatli"},
      {"de":"die Digitalisierung","ru":"цифровизация","uz":"raqamlashtirish"},
      {"de":"die Automatisierung","ru":"автоматизация","uz":"avtomatlashtirish"},
      {"de":"der Wohlstand","ru":"благосостояние","uz":"farovonlik"},
      {"de":"die Ungleichheit (wirtschaftlich)","ru":"экономическое неравенство","uz":"iqtisodiy tengsizlik"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Globalisierung' — это / bu:",
       "opts":["изоляция / izolyatsiya","глобализация / globalizatsiya","приватизация / xususiylashtirilish","локализация / lokalizatsiya"],"ans":1},
      {"type":"choice","q":"'Die Inflation' означает / demak:",
       "opts":["экономический рост / iqtisodiy o'sish","снижение цен / narxlarning tushishi","инфляция / inflyatsiya","рецессия / retsessiya"],"ans":2},
      {"type":"choice","q":"'Der Export' — это / bu:",
       "opts":["импорт / import","экспорт / eksport","потребление / iste'mol","инвестиции / investitsiya"],"ans":1},
      {"type":"choice","q":"'Das BIP' означает / demak:",
       "opts":["бюджетная политика / byudjet siyosati","валовой внутренний продукт / yalpi ichki mahsulot","биржевой индекс / birja indeksi","торговый баланс / savdo balansi"],"ans":1},
      {"type":"choice","q":"'Die Nachfrage' — это / bu:",
       "opts":["предложение / taklif","спрос / talab","цена / narx","товар / tovar"],"ans":1},
      {"type":"choice","q":"'Fair trade' означает / demak:",
       "opts":["быстрая торговля / tez savdo","честная торговля / adolatli savdo","свободная торговля / erkin savdo","цифровая торговля / raqamli savdo"],"ans":1},
      {"type":"choice","q":"'Die Automatisierung' — это / bu:",
       "opts":["ручной труд / qo'l mehnati","автоматизация / avtomatlashtirish","глобализация / globalizatsiya","приватизация / xususiylashtirilish"],"ans":1},
      {"type":"choice","q":"'Der Wohlstand' значит / demak:",
       "opts":["бедность / qashshoqlik","безработица / ishsizlik","благосостояние / farovonlik","инфляция / inflyatsiya"],"ans":2},
      {"type":"choice","q":"'Das Startup' — это / bu:",
       "opts":["крупная корпорация / yirik korporatsiya","стартап / startap","государственное предприятие / davlat korxonasi","монополия / monopoliya"],"ans":1},
    ]
  },
  2: {  # Politik und Demokratie
    "vocab_extra":[
      {"de":"die Verfassung","ru":"конституция","uz":"konstitutsiya"},
      {"de":"das Grundgesetz","ru":"основной закон","uz":"asosiy qonun"},
      {"de":"der Bundestag","ru":"Бундестаг","uz":"Bundestag"},
      {"de":"der Bundesrat","ru":"Бундесрат","uz":"Bundesrat"},
      {"de":"die Bundesregierung","ru":"федеральное правительство","uz":"federal hukumat"},
      {"de":"der Bundeskanzler","ru":"федеральный канцлер","uz":"federal kansler"},
      {"de":"der Bundesminister","ru":"федеральный министр","uz":"federal ministr"},
      {"de":"die Partei","ru":"партия","uz":"partiya"},
      {"de":"die Wahl","ru":"выборы","uz":"saylov"},
      {"de":"wählen","ru":"голосовать, выбирать","uz":"saylamoq, ovoz bermoq"},
      {"de":"die Koalition","ru":"коалиция","uz":"koalitsiya"},
      {"de":"die Opposition","ru":"оппозиция","uz":"muxolifat"},
      {"de":"der Abgeordnete","ru":"депутат","uz":"deputat"},
      {"de":"das Parlament","ru":"парламент","uz":"parlament"},
      {"de":"abstimmen","ru":"голосовать","uz":"ovoz bermoq"},
      {"de":"regieren","ru":"управлять, править","uz":"boshqarmoq"},
      {"de":"das Gesetz","ru":"закон","uz":"qonun"},
      {"de":"verabschieden (Gesetz)","ru":"принимать (закон)","uz":"qonun qabul qilmoq"},
      {"de":"die Menschenrechte","ru":"права человека","uz":"inson huquqlari"},
      {"de":"die Pressefreiheit","ru":"свобода прессы","uz":"matbuot erkinligi"},
      {"de":"das Wahlrecht","ru":"право голоса","uz":"ovoz berish huquqi"},
      {"de":"die Bürgerrechte","ru":"гражданские права","uz":"fuqarolik huquqlari"},
      {"de":"die Meinungsfreiheit","ru":"свобода мнений","uz":"fikr erkinligi"},
      {"de":"der Rechtsstaat","ru":"правовое государство","uz":"huquqiy davlat"},
      {"de":"die Gewaltenteilung","ru":"разделение властей","uz":"hokimiyatlarning bo'linishi"},
      {"de":"die Judikative","ru":"судебная власть","uz":"sud hokimiyati"},
      {"de":"die Legislative","ru":"законодательная власть","uz":"qonun chiqaruvchi hokimiyat"},
      {"de":"die Exekutive","ru":"исполнительная власть","uz":"ijro etuvchi hokimiyat"},
      {"de":"die Demokratie","ru":"демократия","uz":"demokratiya"},
      {"de":"die Diktatur","ru":"диктатура","uz":"diktatura"},
      {"de":"der Nationalismus","ru":"национализм","uz":"millatchililik"},
      {"de":"die Bürgerinitiative","ru":"гражданская инициатива","uz":"fuqarolik tashabbusi"},
      {"de":"das Referendum","ru":"референдум","uz":"referendum"},
      {"de":"die Volksabstimmung","ru":"всеобщее голосование","uz":"xalq ovoz berishi"},
      {"de":"das Amt","ru":"ведомство, должность","uz":"idora, lavozim"},
      {"de":"die Behörde","ru":"государственный орган","uz":"davlat organi"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Das Grundgesetz' — это / bu:",
       "opts":["конституция Германии / Germaniya konstitutsiyasi","гражданский кодекс / fuqarolik kodeksi","налоговый закон / soliq qonuni","уголовный кодекс / jinoyat kodeksi"],"ans":0},
      {"type":"choice","q":"'Der Bundestag' — это / bu:",
       "opts":["федеральный суд / federal sud","парламент Германии / Germaniya parlamenti","правительство / hukumat","президент / prezident"],"ans":1},
      {"type":"choice","q":"'Die Koalition' — это / bu:",
       "opts":["оппозиция / muxolifat","коалиция / koalitsiya","партия / partiya","выборы / saylov"],"ans":1},
      {"type":"choice","q":"'Abstimmen' означает / demak:",
       "opts":["голосовать / ovoz bermoq","управлять / boshqarmoq","выбирать / tanlash","принимать закон / qonun qabul qilmoq"],"ans":0},
      {"type":"choice","q":"'Die Gewaltenteilung' — это / bu:",
       "opts":["разделение властей / hokimiyatlarning bo'linishi","слияние властей / hokimiyatlarning birlashishi","диктатура / diktatura","монополия власти / hokimiyat monopoliyasi"],"ans":0},
      {"type":"choice","q":"'Der Rechtsstaat' означает / demak:",
       "opts":["полицейское государство / politsiya davlati","правовое государство / huquqiy davlat","диктатура / diktatura","теократия / teokratiya"],"ans":1},
      {"type":"choice","q":"'Die Legislative' — это / bu:",
       "opts":["исполнительная власть / ijro etuvchi hokimiyat","судебная власть / sud hokimiyati","законодательная власть / qonun chiqaruvchi hokimiyat","полиция / politsiya"],"ans":2},
      {"type":"choice","q":"'Das Referendum' — это / bu:",
       "opts":["парламентские дебаты / parlament munozarasi","всеобщее голосование / xalq ovoz berishi","назначение министров / vazirlarni tayinlash","конституционные поправки / konstitutsiya o'zgartirish"],"ans":1},
      {"type":"choice","q":"'Die Menschenrechte' — это / bu:",
       "opts":["законы государства / davlat qonunlari","права человека / inson huquqlari","гражданские обязанности / fuqarolik majburiyatlari","конституция / konstitutsiya"],"ans":1},
    ]
  },
  3: {  # Kunst, Literatur und Kultur
    "vocab_extra":[
      {"de":"das Kunstwerk","ru":"произведение искусства","uz":"san'at asari"},
      {"de":"der Künstler / die Künstlerin","ru":"художник","uz":"rassom"},
      {"de":"der Maler / die Malerin","ru":"живописец","uz":"rassom (bo'yoqchi)"},
      {"de":"die Skulptur","ru":"скульптура","uz":"haykaltaroshlik"},
      {"de":"die Installation","ru":"инсталляция","uz":"installatsiya"},
      {"de":"die Ausstellung","ru":"выставка","uz":"ko'rgazma"},
      {"de":"das Museum","ru":"музей","uz":"muzey"},
      {"de":"die Galerie","ru":"галерея","uz":"galereya"},
      {"de":"das Theaterstück","ru":"театральная пьеса","uz":"teatr pyesasi"},
      {"de":"der Roman","ru":"роман","uz":"roman"},
      {"de":"der Autor / die Autorin","ru":"автор","uz":"muallif"},
      {"de":"die Handlung","ru":"сюжет","uz":"syujet"},
      {"de":"der Protagonist","ru":"главный герой","uz":"bosh qahramon"},
      {"de":"die Metapher","ru":"метафора","uz":"metafora"},
      {"de":"das Symbol","ru":"символ","uz":"ramz"},
      {"de":"die Satire","ru":"сатира","uz":"satirа"},
      {"de":"die Kritik","ru":"критика","uz":"tanqid"},
      {"de":"die Rezension","ru":"рецензия","uz":"retsenziya"},
      {"de":"das Denkmal","ru":"памятник","uz":"yodgorlik"},
      {"de":"das Erbe","ru":"наследие","uz":"meros"},
      {"de":"das Kulturerbe","ru":"культурное наследие","uz":"madaniy meros"},
      {"de":"zeitgenössisch","ru":"современный","uz":"zamonaviy"},
      {"de":"klassisch","ru":"классический","uz":"klassik"},
      {"de":"avantgardistisch","ru":"авангардистский","uz":"avangardistik"},
      {"de":"der Stil","ru":"стиль","uz":"uslub"},
      {"de":"die Epoche","ru":"эпоха","uz":"davr"},
      {"de":"das Mittelalter","ru":"Средневековье","uz":"O'rta asrlar"},
      {"de":"die Renaissance","ru":"Возрождение","uz":"Uyg'onish davri"},
      {"de":"die Romantik","ru":"романтизм","uz":"romantizm"},
      {"de":"der Expressionismus","ru":"экспрессионизм","uz":"ekspressionizm"},
      {"de":"kommentieren","ru":"комментировать","uz":"izoh bermoq"},
      {"de":"interpretieren","ru":"интерпретировать","uz":"talqin qilmoq"},
      {"de":"analysieren","ru":"анализировать","uz":"tahlil qilmoq"},
      {"de":"beschreiben","ru":"описывать","uz":"tasvirlamoq"},
      {"de":"bewundern","ru":"восхищаться","uz":"hayranlik bilan tomosha qilmoq"},
      {"de":"die Kreativität","ru":"творчество","uz":"ijodkorlik"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Ausstellung' — это / bu:",
       "opts":["театр / teatr","выставка / ko'rgazma","библиотека / kutubxona","концерт / konsert"],"ans":1},
      {"type":"choice","q":"'Der Protagonist' — это / bu:",
       "opts":["автор / muallif","главный герой / bosh qahramon","критик / tanqidchi","режиссёр / rejissyor"],"ans":1},
      {"type":"choice","q":"'Interpretieren' означает / demak:",
       "opts":["описывать / tasvirlamoq","интерпретировать / talqin qilmoq","рисовать / rasm chizmoq","строить / qurmoq"],"ans":1},
      {"type":"choice","q":"'Das Kulturerbe' — это / bu:",
       "opts":["современное искусство / zamonaviy san'at","культурное наследие / madaniy meros","государственный музей / davlat muzeyi","художественная школа / san'at maktabi"],"ans":1},
      {"type":"choice","q":"'Zeitgenössisch' означает / demak:",
       "opts":["классический / klassik","средневековый / o'rta asrlik","современный / zamonaviy","авангардистский / avangardistik"],"ans":2},
      {"type":"choice","q":"'Die Metapher' — это / bu:",
       "opts":["метафора / metafora","рифма / qofiya","сатира / satira","символ / ramz"],"ans":0},
      {"type":"choice","q":"'Die Renaissance' — это эпоха / bu davr:",
       "opts":["Средневековья / O'rta asrlar","романтизма / romantizm","Возрождения / Uyg'onish","экспрессионизма / ekspressionizm"],"ans":2},
      {"type":"choice","q":"'Analysieren' значит / demak:",
       "opts":["восхищаться / hayranlik bilan tomosha qilmoq","критиковать / tanqid qilmoq","анализировать / tahlil qilmoq","рисовать / rasm chizmoq"],"ans":2},
      {"type":"choice","q":"'Die Skulptur' — это / bu:",
       "opts":["живопись / rassomlik","скульптура / haykaltaroshlik","литература / adabiyot","музыка / musiqa"],"ans":1},
    ]
  },
  4: {  # Wissenschaft und Technologie
    "vocab_extra":[
      {"de":"die Forschung","ru":"исследование","uz":"tadqiqot"},
      {"de":"der Forscher / die Forscherin","ru":"исследователь","uz":"tadqiqotchi"},
      {"de":"das Labor","ru":"лаборатория","uz":"laboratoriya"},
      {"de":"das Experiment","ru":"эксперимент","uz":"tajriba"},
      {"de":"die Hypothese","ru":"гипотеза","uz":"gipoteza"},
      {"de":"beweisen","ru":"доказывать","uz":"isbotlamoq"},
      {"de":"widerlegen","ru":"опровергать","uz":"rad etmoq"},
      {"de":"die Entdeckung","ru":"открытие","uz":"kashfiyot"},
      {"de":"die Erfindung","ru":"изобретение","uz":"ixtiro"},
      {"de":"der Durchbruch","ru":"прорыв","uz":"yutuq"},
      {"de":"die künstliche Intelligenz (KI)","ru":"искусственный интеллект","uz":"sun'iy intellekt"},
      {"de":"der Algorithmus","ru":"алгоритм","uz":"algoritm"},
      {"de":"die Datenmenge","ru":"объём данных","uz":"ma'lumotlar hajmi"},
      {"de":"die Biotechnologie","ru":"биотехнология","uz":"biotexnologiya"},
      {"de":"die Gentechnik","ru":"генная инженерия","uz":"gen injeneriyasi"},
      {"de":"die Nanotechnologie","ru":"нанотехнология","uz":"nanotexnologiya"},
      {"de":"der Roboter","ru":"робот","uz":"robot"},
      {"de":"die Automatisierung","ru":"автоматизация","uz":"avtomatlashtirish"},
      {"de":"die Raumfahrt","ru":"космонавтика","uz":"kosmonavtika"},
      {"de":"das Teleskop","ru":"телескоп","uz":"teleskop"},
      {"de":"der Satellit","ru":"спутник","uz":"sun'iy yo'ldosh"},
      {"de":"das Quantencomputing","ru":"квантовые вычисления","uz":"kvant hisoblash"},
      {"de":"die Cybersicherheit","ru":"кибербезопасность","uz":"kiberhavfsizlik"},
      {"de":"der Datenschutz","ru":"защита данных","uz":"ma'lumotlarni himoya qilish"},
      {"de":"das Patent","ru":"патент","uz":"patent"},
      {"de":"die Studie","ru":"исследование (научное)","uz":"ilmiy tadqiqot"},
      {"de":"die Statistik","ru":"статистика","uz":"statistika"},
      {"de":"die Methode","ru":"метод","uz":"metod"},
      {"de":"reproduzierbar","ru":"воспроизводимый","uz":"takrorlanadigan"},
      {"de":"peer-reviewed","ru":"рецензируемый","uz":"ekspert ko'rib chiqilgan"},
      {"de":"die Ethik (Wissenschaft)","ru":"этика (в науке)","uz":"etika (fanda)"},
      {"de":"der Fortschritt","ru":"прогресс","uz":"taraqqiyot"},
      {"de":"die Nebenwirkung (Technik)","ru":"побочный эффект (тех.)","uz":"yon ta'sir (tex.)"},
      {"de":"die Lösung","ru":"решение","uz":"yechim"},
      {"de":"entwickeln","ru":"разрабатывать","uz":"ishlab chiqmoq"},
      {"de":"testen","ru":"тестировать","uz":"sinab ko'rmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Hypothese' — это / bu:",
       "opts":["доказательство / dalil","гипотеза / gipoteza","вывод / xulosa","эксперимент / tajriba"],"ans":1},
      {"type":"choice","q":"'Die künstliche Intelligenz' — это / bu:",
       "opts":["биотехнология / biotexnologiya","нанотехнология / nanotexnologiya","искусственный интеллект / sun'iy intellekt","кибербезопасность / kiberhavfsizlik"],"ans":2},
      {"type":"choice","q":"'Beweisen' означает / demak:",
       "opts":["опровергать / rad etmoq","доказывать / isbotlamoq","предполагать / taxmin qilmoq","изучать / o'rganmoq"],"ans":1},
      {"type":"choice","q":"'Die Entdeckung' — это / bu:",
       "opts":["изобретение / ixtiro","открытие / kashfiyot","прорыв / yutuq","лаборатория / laboratoriya"],"ans":1},
      {"type":"choice","q":"'Die Raumfahrt' означает / demak:",
       "opts":["авиация / aviatsiya","космонавтика / kosmonavtika","морская навигация / dengiz navigatsiyasi","робототехника / robototexnika"],"ans":1},
      {"type":"choice","q":"'Reproduzierbar' в науке — это / fanda bu:",
       "opts":["уникальный / noyob","воспроизводимый / takrorlanadigan","секретный / sir","теоретический / nazariy"],"ans":1},
      {"type":"choice","q":"'Das Patent' — это / bu:",
       "opts":["исследование / tadqiqot","лицензия / litsenziya","патент / patent","степень / daraja"],"ans":2},
      {"type":"choice","q":"'Die Gentechnik' — это / bu:",
       "opts":["нанотехнология / nanotexnologiya","генная инженерия / gen injeneriyasi","информационные технологии / IT","квантовые вычисления / kvant hisoblash"],"ans":1},
      {"type":"choice","q":"'Der Fortschritt' значит / demak:",
       "opts":["регресс / regress","прогресс / taraqqiyot","открытие / kashfiyot","изобретение / ixtiro"],"ans":1},
    ]
  },
  5: {  # Geschichte und Erinnerungskultur
    "vocab_extra":[
      {"de":"die Geschichte","ru":"история","uz":"tarix"},
      {"de":"das Ereignis","ru":"событие","uz":"voqea"},
      {"de":"das Jahrhundert","ru":"век, столетие","uz":"asr"},
      {"de":"das Jahrzehnt","ru":"десятилетие","uz":"o'n yillik"},
      {"de":"der Krieg","ru":"война","uz":"urush"},
      {"de":"der Frieden","ru":"мир","uz":"tinchlik"},
      {"de":"der Vertrag","ru":"договор","uz":"shartnoma"},
      {"de":"die Revolution","ru":"революция","uz":"inqilob"},
      {"de":"die Diktatur","ru":"диктатура","uz":"diktatura"},
      {"de":"der Widerstand","ru":"сопротивление","uz":"qarshilik"},
      {"de":"die Erinnerung","ru":"воспоминание","uz":"xotira"},
      {"de":"das Gedächtnis","ru":"память","uz":"xotira (yodda saqlash)"},
      {"de":"die Erinnerungskultur","ru":"культура памяти","uz":"xotira madaniyati"},
      {"de":"das Mahnmal","ru":"мемориал","uz":"memorial"},
      {"de":"das Gedenkstätte","ru":"мемориальный объект","uz":"esdalik joyi"},
      {"de":"der Holocaust","ru":"Холокост","uz":"Holokost"},
      {"de":"die Besatzung","ru":"оккупация","uz":"ishg'ol"},
      {"de":"die Befreiung","ru":"освобождение","uz":"ozod qilish"},
      {"de":"die Wiedervereinigung","ru":"воссоединение","uz":"qayta birlashish"},
      {"de":"die Mauer","ru":"стена","uz":"devor"},
      {"de":"der Kalte Krieg","ru":"холодная война","uz":"sovuq urush"},
      {"de":"die Demokratisierung","ru":"демократизация","uz":"demokratlashtirish"},
      {"de":"die Vergangenheitsbewältigung","ru":"осмысление прошлого","uz":"o'tmishni anglash"},
      {"de":"die Schuld","ru":"вина","uz":"aybdorlik"},
      {"de":"die Verantwortung","ru":"ответственность","uz":"mas'uliyat"},
      {"de":"die Versöhnung","ru":"примирение","uz":"yarashish"},
      {"de":"das Archiv","ru":"архив","uz":"arxiv"},
      {"de":"die Quelle (historisch)","ru":"источник (исторический)","uz":"manba (tarixiy)"},
      {"de":"der Zeuge / die Zeugin","ru":"свидетель","uz":"guvoh"},
      {"de":"die Zeitzeugen","ru":"очевидцы эпохи","uz":"davr guvohlari"},
      {"de":"dokumentieren","ru":"документировать","uz":"hujjatlashtirmoq"},
      {"de":"erinnern (sich)","ru":"вспоминать","uz":"eslash"},
      {"de":"vergessen","ru":"забывать","uz":"unutmoq"},
      {"de":"mahnen","ru":"напоминать (о памяти)","uz":"eslatmoq (xotira haqida)"},
      {"de":"gedenken","ru":"чтить память","uz":"xotirasini ulug'lamoq"},
      {"de":"tradieren","ru":"передавать по наследству","uz":"avlodlarga bermoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Erinnerungskultur' — это / bu:",
       "opts":["историческая наука / tarix fani","культура памяти / xotira madaniyati","политическая культура / siyosiy madaniyat","культура мира / tinchlik madaniyati"],"ans":1},
      {"type":"choice","q":"'Die Wiedervereinigung' — это / bu:",
       "opts":["разделение / bo'linish","воссоединение / qayta birlashish","освобождение / ozod qilish","оккупация / ishg'ol"],"ans":1},
      {"type":"choice","q":"'Die Vergangenheitsbewältigung' означает / demak:",
       "opts":["прославление прошлого / o'tmishni ulug'lash","осмысление прошлого / o'tmishni anglash","забывание прошлого / o'tmishni unutish","изучение прошлого / o'tmishni o'rganish"],"ans":1},
      {"type":"choice","q":"'Das Mahnmal' — это / bu:",
       "opts":["исторический архив / tarixiy arxiv","мемориал / memorial","исторический музей / tarix muzeyi","библиотека / kutubxona"],"ans":1},
      {"type":"choice","q":"'Gedenken' означает / demak:",
       "opts":["забывать / unutmoq","игнорировать / e'tiborsiz qoldirmoq","чтить память / xotirasini ulug'lamoq","изучать / o'rganmoq"],"ans":2},
      {"type":"choice","q":"'Die Besatzung' — это / bu:",
       "opts":["освобождение / ozod qilish","оккупация / ishg'ol","воссоединение / qayta birlashish","примирение / yarashish"],"ans":1},
      {"type":"choice","q":"'Der Zeitzeuge' — это / bu:",
       "opts":["историк / tarixchi","архивариус / arxivchi","очевидец эпохи / davr guvohi","журналист / jurnalist"],"ans":2},
      {"type":"choice","q":"'Die Versöhnung' означает / demak:",
       "opts":["война / urush","конфликт / konflikt","примирение / yarashish","противостояние / qarama-qarshilik"],"ans":2},
      {"type":"choice","q":"'Dokumentieren' значит / demak:",
       "opts":["забывать / unutmoq","документировать / hujjatlashtirmoq","разрушать / yo'q qilmoq","строить / qurmoq"],"ans":1},
    ]
  },
  6: {  # Sprache und Kommunikation — Vertiefung
    "vocab_extra":[
      {"de":"die Muttersprache","ru":"родной язык","uz":"ona tili"},
      {"de":"die Fremdsprache","ru":"иностранный язык","uz":"xorijiy til"},
      {"de":"die Zweitsprache","ru":"второй язык","uz":"ikkinchi til"},
      {"de":"zweisprachig","ru":"двуязычный","uz":"ikki tilli"},
      {"de":"mehrsprachig","ru":"многоязычный","uz":"ko'p tilli"},
      {"de":"der Akzent","ru":"акцент","uz":"aksent"},
      {"de":"der Dialekt","ru":"диалект","uz":"dialekt"},
      {"de":"die Mundart","ru":"наречие, говор","uz":"lahjа"},
      {"de":"die Aussprache","ru":"произношение","uz":"talaffuz"},
      {"de":"die Grammatik","ru":"грамматика","uz":"grammatika"},
      {"de":"der Wortschatz","ru":"словарный запас","uz":"so'z boyligi"},
      {"de":"die Idiom","ru":"идиома","uz":"idioma"},
      {"de":"die Redewendung","ru":"выражение, оборот речи","uz":"so'z birikmasi"},
      {"de":"das Sprichwort","ru":"пословица","uz":"maqol"},
      {"de":"der Slang","ru":"сленг","uz":"sleng"},
      {"de":"formal / informell","ru":"официальный / неофициальный","uz":"rasmiy / norasmiy"},
      {"de":"höflich","ru":"вежливый","uz":"muloyim"},
      {"de":"unhöflich","ru":"невежливый","uz":"qo'pol"},
      {"de":"direkt","ru":"прямой","uz":"to'g'ridan-to'g'ri"},
      {"de":"indirekt","ru":"косвенный","uz":"bilvosita"},
      {"de":"missverständnis","ru":"недоразумение","uz":"tushunmovchilik"},
      {"de":"sich verständigen","ru":"объясняться","uz":"tushuntirmoq"},
      {"de":"übersetzen","ru":"переводить","uz":"tarjima qilmoq"},
      {"de":"dolmetschen","ru":"устно переводить","uz":"og'zaki tarjima qilmoq"},
      {"de":"der Übersetzer","ru":"переводчик","uz":"tarjimon"},
      {"de":"der Dolmetscher","ru":"устный переводчик","uz":"og'zaki tarjimon"},
      {"de":"die Körpersprache","ru":"язык тела","uz":"tana tili"},
      {"de":"die nonverbale Kommunikation","ru":"невербальная коммуникация","uz":"noverbal muloqot"},
      {"de":"der Ton","ru":"тон (голоса)","uz":"ton (ovoz)"},
      {"de":"betonen","ru":"подчёркивать, делать акцент","uz":"ta'kidlamoq"},
      {"de":"paraphrasieren","ru":"перефразировать","uz":"qayta ifodalash"},
      {"de":"zusammenfassen","ru":"резюмировать","uz":"xulosa qilmoq"},
      {"de":"argumentieren","ru":"аргументировать","uz":"dalil keltirmoq"},
      {"de":"überzeugen","ru":"убеждать","uz":"ishontirmoq"},
      {"de":"widersprechen","ru":"возражать","uz":"e'tiroz bildirmoq"},
      {"de":"zustimmen","ru":"соглашаться","uz":"rozi bo'lmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Die Muttersprache' — это / bu:",
       "opts":["иностранный язык / xorijiy til","родной язык / ona tili","второй язык / ikkinchi til","официальный язык / rasmiy til"],"ans":1},
      {"type":"choice","q":"'Dolmetschen' — это / bu:",
       "opts":["письменный перевод / yozma tarjima","устный перевод / og'zaki tarjima","редактирование / tahrirlash","преподавание / o'qitish"],"ans":1},
      {"type":"choice","q":"'Die Redewendung' — это / bu:",
       "opts":["грамматическое правило / grammatik qoida","речевой оборот / so'z birikmasi","произношение / talaffuz","словарный запас / so'z boyligi"],"ans":1},
      {"type":"choice","q":"'Paraphrasieren' значит / demak:",
       "opts":["цитировать / iqtibos keltirmoq","перефразировать / qayta ifodalash","переводить / tarjima qilmoq","суммировать / xulosa qilmoq"],"ans":1},
      {"type":"choice","q":"'Zweisprachig' означает / demak:",
       "opts":["одноязычный / bir tilli","двуязычный / ikki tilli","многоязычный / ko'p tilli","без языка / tilsiz"],"ans":1},
      {"type":"choice","q":"'Die Körpersprache' — это / bu:",
       "opts":["тон голоса / ovoz toni","язык тела / tana tili","диалект / dialekt","акцент / aksent"],"ans":1},
      {"type":"choice","q":"'Widersprechen' означает / demak:",
       "opts":["соглашаться / rozi bo'lmoq","возражать / e'tiroz bildirmoq","убеждать / ishontirmoq","объяснять / tushuntirmoq"],"ans":1},
      {"type":"choice","q":"'Formell' — это стиль речи / nutq uslubi:",
       "opts":["неофициальный / norasmiy","сленговый / slengga asoslangan","официальный / rasmiy","разговорный / so'zlashuv"],"ans":2},
      {"type":"choice","q":"'Das Missverständnis' — это / bu:",
       "opts":["соглашение / kelishuv","понимание / tushunish","недоразумение / tushunmovchilik","диалог / dialog"],"ans":2},
    ]
  },
  7: {  # Reisen und interkulturelle Erfahrungen
    "vocab_extra":[
      {"de":"interkulturell","ru":"межкультурный","uz":"madaniyatlararo"},
      {"de":"der Kulturschock","ru":"культурный шок","uz":"madaniy shok"},
      {"de":"die Anpassung","ru":"адаптация","uz":"moslashish"},
      {"de":"der Austausch","ru":"обмен","uz":"almashuv"},
      {"de":"das Auslandsstudium","ru":"учёба за рубежом","uz":"chet elda o'qish"},
      {"de":"das Au-pair","ru":"молодой человек за границей (au pair)","uz":"au pair"},
      {"de":"das Visum","ru":"виза","uz":"viza"},
      {"de":"die Botschaft","ru":"посольство","uz":"elchixona"},
      {"de":"das Konsulat","ru":"консульство","uz":"konsullik"},
      {"de":"der Reisepass","ru":"паспорт","uz":"pasport"},
      {"de":"die Aufenthaltserlaubnis","ru":"вид на жительство","uz":"yashash ruxsatnomasi"},
      {"de":"die Einwanderung","ru":"иммиграция","uz":"immigratsiya"},
      {"de":"die Auswanderung","ru":"эмиграция","uz":"emigratsiya"},
      {"de":"heimweh haben","ru":"скучать по дому","uz":"uy sog'inch sezmoq"},
      {"de":"sich einleben","ru":"обустраиваться","uz":"o'rganib olmoq"},
      {"de":"die Gastfreundschaft","ru":"гостеприимство","uz":"mehmondo'stlik"},
      {"de":"die Bräuche","ru":"обычаи","uz":"urf-odatlar"},
      {"de":"die Traditionen","ru":"традиции","uz":"an'analar"},
      {"de":"das Tabu","ru":"табу","uz":"tabu"},
      {"de":"der Stereotyp","ru":"стереотип","uz":"stereotip"},
      {"de":"das Vorurteil","ru":"предрассудок","uz":"xurofot"},
      {"de":"offen sein","ru":"быть открытым","uz":"ochiq bo'lmoq"},
      {"de":"respektieren","ru":"уважать","uz":"hurmat qilmoq"},
      {"de":"sich anpassen","ru":"приспосабливаться","uz":"moslashmoq"},
      {"de":"der Kulturvergleich","ru":"сравнение культур","uz":"madaniyatlarni solishtirish"},
      {"de":"das Klima (sozial)","ru":"социальный климат","uz":"ijtimoiy muhit"},
      {"de":"die Sprache als Schlüssel","ru":"язык как ключ","uz":"til - kalit"},
      {"de":"das Reisebudget","ru":"дорожный бюджет","uz":"sayohat byudjeti"},
      {"de":"die Unterkunft","ru":"жильё","uz":"turar joy"},
      {"de":"die Sehenswürdigkeit","ru":"достопримечательность","uz":"ko'rib o'tiladigan joy"},
      {"de":"die Reiseführer","ru":"путеводитель","uz":"sayohat qo'llanmasi"},
      {"de":"besichtigen","ru":"осматривать","uz":"ko'zdan kechirmoq"},
      {"de":"erkunden","ru":"исследовать","uz":"o'rganmoq"},
      {"de":"entdecken","ru":"открывать","uz":"kashf etmoq"},
      {"de":"die Begegnung","ru":"встреча","uz":"uchrashuv"},
      {"de":"der Einheimische","ru":"местный житель","uz":"mahalliy aholi vakili"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Der Kulturschock' — это / bu:",
       "opts":["культурное мероприятие / madaniy tadbir","культурный шок / madaniy shok","культурный обмен / madaniy almashuv","культурное наследие / madaniy meros"],"ans":1},
      {"type":"choice","q":"'Das Auslandsstudium' означает / demak:",
       "opts":["дистанционное обучение / masofaviy o'qish","учёба за рубежом / chet elda o'qish","вечернее обучение / kechki o'qish","самообразование / o'z-o'zini tarbiyalash"],"ans":1},
      {"type":"choice","q":"'Heimweh haben' — это / bu:",
       "opts":["радоваться путешествию / sayohatdan xursand bo'lmoq","скучать по дому / uy sog'inch sezmoq","быть открытым / ochiq bo'lmoq","адаптироваться / moslashmoq"],"ans":1},
      {"type":"choice","q":"'Die Aufenthaltserlaubnis' — это / bu:",
       "opts":["виза / viza","паспорт / pasport","вид на жительство / yashash ruxsatnomasi","гражданство / fuqarolik"],"ans":2},
      {"type":"choice","q":"'Interkulturell' означает / demak:",
       "opts":["внутрикультурный / madaniyat ichida","межкультурный / madaniyatlararo","монокультурный / bir madaniyatli","антикультурный / madaniyatga qarshi"],"ans":1},
      {"type":"choice","q":"'Sich einleben' — это / bu:",
       "opts":["переезжать / ko'chib o'tmoq","обустраиваться / o'rganib olmoq","скучать / sog'inch sezmoq","возвращаться / qaytmoq"],"ans":1},
      {"type":"choice","q":"'Die Gastfreundschaft' — это / bu:",
       "opts":["гостеприимство / mehmondo'stlik","туризм / turizm","путешествие / sayohat","переезд / ko'chib o'tish"],"ans":0},
      {"type":"choice","q":"'Besichtigen' значит / demak:",
       "opts":["строить / qurmoq","покупать / sotib olmoq","осматривать / ko'zdan kechirmoq","есть / yemoq"],"ans":2},
      {"type":"choice","q":"'Der Einheimische' — это / bu:",
       "opts":["турист / turist","путешественник / sayohatchi","местный житель / mahalliy aholi vakili","иностранец / chet ellik"],"ans":2},
    ]
  },
  8: {  # Zukunftsperspektiven und persönliche Ziele
    "vocab_extra":[
      {"de":"die Zukunftsvision","ru":"видение будущего","uz":"kelajak tasavvuri"},
      {"de":"der Lebensplan","ru":"жизненный план","uz":"hayot rejasi"},
      {"de":"das Lebensziel","ru":"жизненная цель","uz":"hayot maqsadi"},
      {"de":"die Priorität","ru":"приоритет","uz":"ustuvorlik"},
      {"de":"der Wunsch","ru":"желание","uz":"istak"},
      {"de":"der Traum","ru":"мечта","uz":"orzu"},
      {"de":"verwirklichen","ru":"реализовывать","uz":"amalga oshirmoq"},
      {"de":"planen","ru":"планировать","uz":"rejalashmoq"},
      {"de":"das Risiko","ru":"риск","uz":"xavf"},
      {"de":"die Chance","ru":"шанс, возможность","uz":"imkoniyat"},
      {"de":"die Herausforderung","ru":"вызов","uz":"qiyinchilik, muammo"},
      {"de":"die Unsicherheit","ru":"неопределённость","uz":"noaniqlik"},
      {"de":"mutig","ru":"смелый","uz":"jasur"},
      {"de":"vorsichtig","ru":"осторожный","uz":"ehtiyotkor"},
      {"de":"entschieden","ru":"решительный","uz":"qat'iy"},
      {"de":"unentschlossen","ru":"нерешительный","uz":"ikkilanuvchi"},
      {"de":"optimistisch","ru":"оптимистичный","uz":"optimistik"},
      {"de":"realistisch","ru":"реалистичный","uz":"realistik"},
      {"de":"das Potenzial","ru":"потенциал","uz":"salohiyat"},
      {"de":"die Fähigkeit","ru":"способность","uz":"qobiliyat"},
      {"de":"sich entwickeln","ru":"развиваться","uz":"rivojlanmoq"},
      {"de":"wachsen","ru":"расти","uz":"o'smoq"},
      {"de":"scheitern","ru":"терпеть неудачу","uz":"muvaffaqiyatsiz bo'lmoq"},
      {"de":"aufgeben","ru":"сдаваться","uz":"taslim bo'lmoq"},
      {"de":"weitermachen","ru":"продолжать","uz":"davom ettirmoq"},
      {"de":"die Balance","ru":"баланс","uz":"muvozanat"},
      {"de":"die Work-Life-Balance","ru":"баланс работы и жизни","uz":"ish va hayot muvozanati"},
      {"de":"der Sinn","ru":"смысл","uz":"ma'no"},
      {"de":"die Bedeutung","ru":"значение","uz":"ahamiyat"},
      {"de":"erfüllt sein","ru":"быть наполненным (смыслом)","uz":"ma'noli bo'lmoq"},
      {"de":"zufrieden","ru":"довольный","uz":"mamnun"},
      {"de":"unzufrieden","ru":"недовольный","uz":"norozi"},
      {"de":"die Selbstverwirklichung","ru":"самореализация","uz":"o'z-o'zini ro'yobga chiqarish"},
      {"de":"das Glück","ru":"счастье","uz":"baxt"},
      {"de":"das Wohlbefinden","ru":"благополучие","uz":"farovonlik"},
      {"de":"nachdenken über","ru":"размышлять о","uz":"o'ylamoq (haqida)"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"'Verwirklichen' означает / demak:",
       "opts":["мечтать / orzulamoq","реализовывать / amalga oshirmoq","планировать / rejalashmoq","сдаваться / taslim bo'lmoq"],"ans":1},
      {"type":"choice","q":"'Die Herausforderung' — это / bu:",
       "opts":["лёгкая задача / oson vazifa","вызов, трудность / qiyinchilik","удача / omad","решение / yechim"],"ans":1},
      {"type":"choice","q":"'Scheitern' означает / demak:",
       "opts":["достигать цели / maqsadga erishmoq","терпеть неудачу / muvaffaqiyatsiz bo'lmoq","рисковать / xavf olmoq","планировать / rejalashmoq"],"ans":1},
      {"type":"choice","q":"'Die Work-Life-Balance' — это / bu:",
       "opts":["только работа / faqat ish","только отдых / faqat dam olish","баланс работы и жизни / ish va hayot muvozanati","рабочий договор / ish shartnomasi"],"ans":2},
      {"type":"choice","q":"'Selbstverwirklichung' означает / demak:",
       "opts":["самокритика / o'z-o'zini tanqid","самореализация / o'z-o'zini ro'yobga chiqarish","самообман / o'zini aldash","самоанализ / o'z-o'zini tahlil qilish"],"ans":1},
      {"type":"choice","q":"'Mutig' — это / bu:",
       "opts":["осторожный / ehtiyotkor","нерешительный / ikkilanuvchi","смелый / jasur","пессимистичный / pessimistik"],"ans":2},
      {"type":"choice","q":"'Die Unsicherheit' означает / demak:",
       "opts":["уверенность / ishonch","определённость / aniqlik","неопределённость / noaniqlik","безопасность / xavfsizlik"],"ans":2},
      {"type":"choice","q":"'Zufrieden' значит / demak:",
       "opts":["недовольный / norozi","грустный / xafa","довольный / mamnun","усталый / charchagan"],"ans":2},
      {"type":"choice","q":"'Der Sinn' в контексте жизни — это / bu:",
       "opts":["шанс / imkoniyat","смысл / ma'no","цель / maqsad","мечта / orzu"],"ans":1},
    ]
  },
}
