"""
Extension: A1.1 + A1.2 — 36 additional vocab words + 9 additional exercises per lesson
After merging: 48 words + 12 exercises per lesson
"""

EXT_A1_1 = {
  1: {  # Kennenlernen
    "vocab_extra":[
      {"de":"Herr","ru":"Господин","uz":"Janob"},
      {"de":"Frau (Anrede)","ru":"Госпожа","uz":"Xonim"},
      {"de":"Bitte","ru":"Пожалуйста","uz":"Iltimos / Marhamat"},
      {"de":"Entschuldigung!","ru":"Извините!","uz":"Kechirasiz!"},
      {"de":"Ja / Nein","ru":"Да / Нет","uz":"Ha / Yo'q"},
      {"de":"Ich verstehe nicht.","ru":"Я не понимаю.","uz":"Men tushunmayapman."},
      {"de":"Bitte wiederholen Sie!","ru":"Повторите, пожалуйста!","uz":"Iltimos, takrorlang!"},
      {"de":"Sprechen Sie Deutsch?","ru":"Вы говорите по-немецки?","uz":"Nemischa gaplashasizmi?"},
      {"de":"Wie bitte?","ru":"Что? / Простите?","uz":"Nima dediingiz?"},
      {"de":"eins / zwei / drei","ru":"один / два / три","uz":"bir / ikki / uch"},
      {"de":"vier / fünf / sechs","ru":"четыре / пять / шесть","uz":"to'rt / besh / olti"},
      {"de":"sieben / acht / neun / zehn","ru":"семь / восемь / девять / десять","uz":"yetti / sakkiz / to'qqiz / o'n"},
      {"de":"Deutschland","ru":"Германия","uz":"Germaniya"},
      {"de":"Österreich","ru":"Австрия","uz":"Avstriya"},
      {"de":"die Schweiz","ru":"Швейцария","uz":"Shveytsariya"},
      {"de":"Russland","ru":"Россия","uz":"Rossiya"},
      {"de":"Usbekistan","ru":"Узбекистан","uz":"O'zbekiston"},
      {"de":"die Türkei","ru":"Турция","uz":"Turkiya"},
      {"de":"die Nationalität","ru":"национальность","uz":"millat"},
      {"de":"deutsch","ru":"немецкий / немец","uz":"nemis"},
      {"de":"russisch","ru":"русский","uz":"rus"},
      {"de":"usbekisch","ru":"узбекский","uz":"o'zbek"},
      {"de":"Gute Nacht!","ru":"Спокойной ночи!","uz":"Xayrli tun!"},
      {"de":"Bis bald!","ru":"До скорого!","uz":"Tez orada ko'rishguncha!"},
      {"de":"Bis morgen!","ru":"До завтра!","uz":"Ertaga ko'rishguncha!"},
      {"de":"das Alter","ru":"возраст","uz":"yosh"},
      {"de":"verheiratet","ru":"женатый / замужем","uz":"turmush qurgan"},
      {"de":"ledig","ru":"холостой / незамужем","uz":"bo'ydoq"},
      {"de":"der Beruf","ru":"профессия","uz":"kasb"},
      {"de":"Angenehm!","ru":"Приятно познакомиться!","uz":"Tanishganimdan xursandman!"},
      {"de":"die Adresse","ru":"адрес","uz":"manzil"},
      {"de":"die Telefonnummer","ru":"номер телефона","uz":"telefon raqami"},
      {"de":"buchstabieren","ru":"писать по буквам","uz":"harflab aytmoq"},
      {"de":"das Alphabet","ru":"алфавит","uz":"alfavit"},
      {"de":"die Sprache","ru":"язык","uz":"til"},
      {"de":"das Land","ru":"страна","uz":"mamlakat"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Wie sagt man 'Спокойной ночи' auf Deutsch?",
       "opts":["Guten Morgen","Gute Nacht","Auf Wiedersehen","Guten Tag"],"ans":1},
      {"type":"fill","q":"___ komme ich aus Usbekistan. (Я...)",
       "opts":["Er","Du","Ich","Wir"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'ledig'?",
       "opts":["женатый","холостой","старый","молодой"],"ans":1},
      {"type":"fill","q":"Fünf + drei = ___",
       "opts":["acht","neun","sieben","zehn"],"ans":0},
      {"type":"choice","q":"Wie heißt 'Германия' auf Deutsch?",
       "opts":["Österreich","Russland","Deutschland","Schweiz"],"ans":2},
      {"type":"fill","q":"Ich ___ nicht. (nicht verstehen)",
       "opts":["verstehe","spreche","komme","heiße"],"ans":0},
      {"type":"choice","q":"Was sagt man, wenn man jemanden nicht versteht?",
       "opts":["Guten Tag!","Bitte wiederholen Sie!","Auf Wiedersehen!","Danke!"],"ans":1},
      {"type":"fill","q":"___ Sie Deutsch? (Говорите ли вы...)",
       "opts":["Kommen","Heißen","Sprechen","Sind"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'Angenehm!'?",
       "opts":["Спокойной ночи!","До свидания!","Приятно познакомиться!","Пожалуйста!"],"ans":2},
    ]
  },
  2: {  # Familie
    "vocab_extra":[
      {"de":"der Onkel","ru":"дядя","uz":"amaki / tog'a"},
      {"de":"die Tante","ru":"тётя","uz":"xola / ammacha"},
      {"de":"der Cousin","ru":"двоюродный брат","uz":"amakivachcha (o'g'il)"},
      {"de":"die Cousine","ru":"двоюродная сестра","uz":"amakivachcha (qiz)"},
      {"de":"der Neffe","ru":"племянник","uz":"jiyani (o'g'il)"},
      {"de":"die Nichte","ru":"племянница","uz":"jiyani (qiz)"},
      {"de":"der Schwiegervater","ru":"свёкор / тесть","uz":"qaynatа"},
      {"de":"die Schwiegermutter","ru":"свекровь / тёща","uz":"qaynonа"},
      {"de":"der Schwager","ru":"зять / шурин","uz":"qaynoga / qudа"},
      {"de":"die Schwägerin","ru":"невестка / золовка","uz":"kelinchilik"},
      {"de":"die Eltern","ru":"родители","uz":"ota-ona"},
      {"de":"die Geschwister","ru":"братья и сёстры","uz":"aka-uka / opa-singil"},
      {"de":"die Großeltern","ru":"бабушка и дедушка","uz":"bobo-buvi"},
      {"de":"das Baby","ru":"малыш / младенец","uz":"chaqaloq"},
      {"de":"der Teenager","ru":"подросток","uz":"o'smir"},
      {"de":"der Erwachsene","ru":"взрослый","uz":"kattalar"},
      {"de":"jung / alt","ru":"молодой / старый","uz":"yosh / keksa"},
      {"de":"Wie alt bist du?","ru":"Сколько тебе лет?","uz":"Necha yoshdasiz?"},
      {"de":"... Jahre alt","ru":"...лет","uz":"... yoshda"},
      {"de":"verheiratet / ledig","ru":"женат / холост","uz":"turmush qurgan / bo'ydoq"},
      {"de":"geschieden","ru":"разведённый","uz":"ajrashgan"},
      {"de":"das Paar","ru":"пара","uz":"juft"},
      {"de":"die Ehe","ru":"брак","uz":"nikoh"},
      {"de":"elf / zwölf / dreizehn","ru":"одиннадцать / двенадцать / тринадцать","uz":"o'n bir / o'n ikki / o'n uch"},
      {"de":"vierzehn / fünfzehn","ru":"четырнадцать / пятнадцать","uz":"o'n to'rt / o'n besh"},
      {"de":"zwanzig / dreißig","ru":"двадцать / тридцать","uz":"yigirma / o'ttiz"},
      {"de":"lieb / nett","ru":"милый / приятный","uz":"sevimli / yoqimli"},
      {"de":"streng","ru":"строгий","uz":"qattiq"},
      {"de":"lustig","ru":"весёлый","uz":"quvnoq"},
      {"de":"ruhig","ru":"спокойный","uz":"tinch"},
      {"de":"die Geburt","ru":"рождение","uz":"tug'ilish"},
      {"de":"geboren am...","ru":"рождённый...","uz":"...da tug'ilgan"},
      {"de":"das Geburtsland","ru":"страна рождения","uz":"tug'ilgan mamlakat"},
      {"de":"adoptiert","ru":"усыновлённый","uz":"asrab olingan"},
      {"de":"die Stiefmutter","ru":"мачеха","uz":"o'gay ona"},
      {"de":"der Stiefvater","ru":"отчим","uz":"o'gay ota"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Neffe'?",
       "opts":["племянница","племянник","дядя","двоюродный брат"],"ans":1},
      {"type":"fill","q":"Wie alt ___ du? (bist/bist/ist/sind)",
       "opts":["ist","sind","bist","bin"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'geschieden'?",
       "opts":["холостой","женатый","разведённый","вдовец"],"ans":2},
      {"type":"fill","q":"Zehn + drei = ___",
       "opts":["zwölf","dreizehn","vierzehn","elf"],"ans":1},
      {"type":"choice","q":"Die Eltern = ?",
       "opts":["бабушка и дедушка","братья и сёстры","родители","тётя и дядя"],"ans":2},
      {"type":"fill","q":"Meine ___ heißt Oma Lena. (бабушка)",
       "opts":["Schwester","Tochter","Großmutter","Tante"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'lustig'?",
       "opts":["строгий","спокойный","весёлый","грустный"],"ans":2},
      {"type":"fill","q":"Er ist ___ Jahre alt. (30)",
       "opts":["zwanzig","dreißig","vierzig","zwölf"],"ans":1},
      {"type":"choice","q":"'die Geschwister' bedeutet...",
       "opts":["родители","братья и сёстры","родственники","дети"],"ans":1},
    ]
  },
  3: {  # Wohnung
    "vocab_extra":[
      {"de":"der Schrank","ru":"шкаф","uz":"shkaf"},
      {"de":"das Sofa","ru":"диван","uz":"divan"},
      {"de":"der Sessel","ru":"кресло","uz":"kreslo"},
      {"de":"die Lampe","ru":"лампа","uz":"chiroq"},
      {"de":"der Teppich","ru":"ковёр","uz":"gilam"},
      {"de":"das Regal","ru":"полка","uz":"javon"},
      {"de":"der Spiegel","ru":"зеркало","uz":"oyna"},
      {"de":"die Badewanne","ru":"ванна","uz":"vanna"},
      {"de":"die Dusche","ru":"душ","uz":"dush"},
      {"de":"das WC / die Toilette","ru":"туалет","uz":"hojatxona"},
      {"de":"der Herd","ru":"плита","uz":"pechka"},
      {"de":"der Geschirrspüler","ru":"посудомоечная машина","uz":"idish yuvish mashinasi"},
      {"de":"der Balkon","ru":"балкон","uz":"balkon"},
      {"de":"der Keller","ru":"подвал","uz":"er osti"},
      {"de":"die Garage","ru":"гараж","uz":"garaj"},
      {"de":"der Garten","ru":"сад / огород","uz":"bog'"},
      {"de":"die Wände","ru":"стены","uz":"devorlar"},
      {"de":"die Decke","ru":"потолок","uz":"ship"},
      {"de":"der Boden / der Fußboden","ru":"пол","uz":"pol"},
      {"de":"hell / dunkel","ru":"светлый / тёмный","uz":"yorug' / qorong'i"},
      {"de":"modern / alt","ru":"современный / старый","uz":"zamonaviy / eski"},
      {"de":"renoviert","ru":"отремонтированный","uz":"ta'mirlangan"},
      {"de":"die Quadratmeter (qm)","ru":"квадратные метры","uz":"kvadrat metr"},
      {"de":"die Miete","ru":"аренда / квартплата","uz":"ijara"},
      {"de":"der Vermieter","ru":"арендодатель","uz":"ijaraberuvchi"},
      {"de":"der Mieter","ru":"арендатор","uz":"ijarachi"},
      {"de":"das Stockwerk / die Etage","ru":"этаж","uz":"qavat"},
      {"de":"das Erdgeschoss","ru":"первый (нулевой) этаж","uz":"birinchi qavat"},
      {"de":"der Aufzug / der Fahrstuhl","ru":"лифт","uz":"lift"},
      {"de":"links / rechts / geradeaus","ru":"налево / направо / прямо","uz":"chapga / o'ngga / to'g'ri"},
      {"de":"oben / unten","ru":"наверху / внизу","uz":"yuqorida / pastda"},
      {"de":"neben / zwischen","ru":"рядом / между","uz":"yonida / orasida"},
      {"de":"wohnen","ru":"жить / проживать","uz":"yashash"},
      {"de":"einziehen","ru":"въезжать","uz":"ko'chib kirmoq"},
      {"de":"ausziehen","ru":"выезжать","uz":"ko'chib chiqmoq"},
      {"de":"möbliert","ru":"меблированный","uz":"mebel bilan"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Aufzug'?",
       "opts":["гараж","лестница","лифт","балкон"],"ans":2},
      {"type":"fill","q":"Die Wohnung ist 60 ___ groß. (квадратных метров)",
       "opts":["Meter","Kilometer","Quadratmeter","Zimmer"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'möbliert'?",
       "opts":["пустой","меблированный","отремонтированный","светлый"],"ans":1},
      {"type":"fill","q":"Das Sofa steht ___ dem Tisch. (перед)",
       "opts":["hinter","neben","vor","über"],"ans":2},
      {"type":"choice","q":"Was ist 'das Erdgeschoss'?",
       "opts":["подвал","первый этаж","чердак","гараж"],"ans":1},
      {"type":"fill","q":"Das Zimmer ist sehr ___. (светлый)",
       "opts":["dunkel","alt","hell","klein"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'einziehen'?",
       "opts":["выезжать","ремонтировать","въезжать","покупать"],"ans":2},
      {"type":"fill","q":"Der Schrank steht ___ dem Bett. (рядом с)",
       "opts":["vor","auf","hinter","neben"],"ans":3},
      {"type":"choice","q":"Was ist 'die Dusche'?",
       "opts":["ванна","зеркало","душ","раковина"],"ans":2},
    ]
  },
  4: {  # Essen und Trinken
    "vocab_extra":[
      {"de":"das Ei","ru":"яйцо","uz":"tuxum"},
      {"de":"die Kartoffel","ru":"картофель","uz":"kartoshka"},
      {"de":"die Tomate","ru":"помидор","uz":"pomidor"},
      {"de":"die Zwiebel","ru":"лук","uz":"piyoz"},
      {"de":"der Salat","ru":"салат","uz":"salat"},
      {"de":"die Suppe","ru":"суп","uz":"sho'rva"},
      {"de":"die Nudeln","ru":"макароны","uz":"makaron"},
      {"de":"der Reis","ru":"рис","uz":"guruch"},
      {"de":"das Hähnchen","ru":"курица","uz":"tovuq"},
      {"de":"die Wurst","ru":"колбаса","uz":"kolbasa"},
      {"de":"der Kuchen","ru":"торт / пирог","uz":"tort / pirog"},
      {"de":"die Schokolade","ru":"шоколад","uz":"shokolad"},
      {"de":"das Eis","ru":"мороженое","uz":"muzqaymoq"},
      {"de":"die Milch","ru":"молоко","uz":"sut"},
      {"de":"der Zucker","ru":"сахар","uz":"shakar"},
      {"de":"das Salz","ru":"соль","uz":"tuz"},
      {"de":"das Öl","ru":"масло (растительное)","uz":"o'simlik yog'i"},
      {"de":"kochen","ru":"готовить","uz":"pishirmoq"},
      {"de":"backen","ru":"печь","uz":"pishirmoq (pechda)"},
      {"de":"braten","ru":"жарить","uz":"qovurmoq"},
      {"de":"schneiden","ru":"резать","uz":"kesmoq"},
      {"de":"essen / trinken","ru":"есть / пить","uz":"yemoq / ichmoq"},
      {"de":"frühstücken / zu Mittag essen","ru":"завтракать / обедать","uz":"nonushta qilmoq / tushlik qilmoq"},
      {"de":"zu Abend essen","ru":"ужинать","uz":"kechki ovqat yemoq"},
      {"de":"satt / hungrig","ru":"сытый / голодный","uz":"to'q / och"},
      {"de":"durstig","ru":"хотеть пить","uz":"chanqagan"},
      {"de":"das Restaurant","ru":"ресторан","uz":"restoran"},
      {"de":"das Café","ru":"кафе","uz":"kafe"},
      {"de":"bestellen","ru":"заказывать","uz":"buyurtma bermoq"},
      {"de":"die Rechnung","ru":"счёт","uz":"hisob-kitob"},
      {"de":"die Portion","ru":"порция","uz":"porsiya"},
      {"de":"süß / sauer / salzig","ru":"сладкий / кислый / солёный","uz":"shirin / nordon / sho'r"},
      {"de":"scharf","ru":"острый","uz":"achchiq"},
      {"de":"frisch / alt","ru":"свежий / несвежий","uz":"yangi / eski"},
      {"de":"bio","ru":"органический","uz":"organik"},
      {"de":"vegetarisch","ru":"вегетарианский","uz":"vegetarian"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Kartoffel'?",
       "opts":["помидор","лук","картофель","морковь"],"ans":2},
      {"type":"fill","q":"Ich bin sehr ___. Ich möchte essen. (голодный)",
       "opts":["satt","durstig","hungrig","müde"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'bestellen'?",
       "opts":["платить","заказывать","готовить","есть"],"ans":1},
      {"type":"fill","q":"Der Kaffee ist zu ___. Ich mag keinen Zucker. (сладкий)",
       "opts":["scharf","süß","sauer","salzig"],"ans":1},
      {"type":"choice","q":"Was ist 'das Hähnchen'?",
       "opts":["рыба","свинина","курица","говядина"],"ans":2},
      {"type":"fill","q":"Wir ___ Spaghetti zum Abendessen. (готовим)",
       "opts":["essen","kaufen","kochen","braten"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'frisch'?",
       "opts":["несвежий","солёный","свежий","острый"],"ans":2},
      {"type":"fill","q":"Ich möchte die ___, bitte. (счёт)",
       "opts":["Speisekarte","Rechnung","Portion","Bestellung"],"ans":1},
      {"type":"choice","q":"Was ist 'die Suppe'?",
       "opts":["десерт","суп","основное блюдо","закуска"],"ans":1},
    ]
  },
  5: {  # Mein Tag
    "vocab_extra":[
      {"de":"Montag / Dienstag","ru":"понедельник / вторник","uz":"dushanba / seshanba"},
      {"de":"Mittwoch / Donnerstag","ru":"среда / четверг","uz":"chorshanba / payshanba"},
      {"de":"Freitag / Samstag / Sonntag","ru":"пятница / суббота / воскресенье","uz":"juma / shanba / yakshanba"},
      {"de":"Januar / Februar / März","ru":"январь / февраль / март","uz":"yanvar / fevral / mart"},
      {"de":"April / Mai / Juni","ru":"апрель / май / июнь","uz":"aprel / may / iyun"},
      {"de":"Juli / August / September","ru":"июль / август / сентябрь","uz":"iyul / avgust / sentabr"},
      {"de":"Oktober / November / Dezember","ru":"октябрь / ноябрь / декабрь","uz":"oktabr / noyabr / dekabr"},
      {"de":"Wie spät ist es?","ru":"Который час?","uz":"Soat necha bo'ldi?"},
      {"de":"Es ist 8 Uhr.","ru":"Сейчас 8 часов.","uz":"Soat 8 bo'ldi."},
      {"de":"Viertel nach / vor","ru":"четверть после / до","uz":"chorak o'tgan / qolgan"},
      {"de":"halb neun (8:30)","ru":"половина девятого","uz":"soat 8 yarim"},
      {"de":"die Minute / die Stunde","ru":"минута / час","uz":"daqiqa / soat"},
      {"de":"zuerst / dann / danach","ru":"сначала / потом / после","uz":"avval / keyin / so'ngra"},
      {"de":"früh / spät","ru":"рано / поздно","uz":"erta / kech"},
      {"de":"pünktlich","ru":"вовремя","uz":"o'z vaqtida"},
      {"de":"sich waschen","ru":"умываться","uz":"yuvindirmoq"},
      {"de":"sich anziehen","ru":"одеваться","uz":"kiyinmoq"},
      {"de":"sich die Zähne putzen","ru":"чистить зубы","uz":"tish tozalamoq"},
      {"de":"das Mittagessen","ru":"обед","uz":"tushlik"},
      {"de":"das Abendessen","ru":"ужин","uz":"kechki ovqat"},
      {"de":"das Frühstück","ru":"завтрак","uz":"nonushta"},
      {"de":"der Wecker","ru":"будильник","uz":"soat (qo'ng'iroqli)"},
      {"de":"schlafen","ru":"спать","uz":"uxlamoq"},
      {"de":"aufwachen","ru":"просыпаться","uz":"uyg'onmoq"},
      {"de":"nach Hause kommen","ru":"возвращаться домой","uz":"uyga qaytmoq"},
      {"de":"die Mittagspause","ru":"обеденный перерыв","uz":"tushlik tanaffusi"},
      {"de":"der Feierabend","ru":"конец рабочего дня","uz":"ish kuni tugashi"},
      {"de":"das Wochenende","ru":"выходные","uz":"dam olish kuni"},
      {"de":"täglich","ru":"ежедневно","uz":"har kuni"},
      {"de":"wöchentlich","ru":"еженедельно","uz":"har hafta"},
      {"de":"normalerweise","ru":"обычно","uz":"odatda"},
      {"de":"regelmäßig","ru":"регулярно","uz":"muntazam"},
      {"de":"selten","ru":"редко","uz":"kamdan-kam"},
      {"de":"oft / häufig","ru":"часто","uz":"ko'p"},
      {"de":"nie","ru":"никогда","uz":"hech qachon"},
      {"de":"die Routine","ru":"распорядок","uz":"tartib"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was kommt nach Montag?",
       "opts":["Mittwoch","Freitag","Dienstag","Donnerstag"],"ans":2},
      {"type":"fill","q":"Es ist halb neun = ___",
       "opts":["8:15","8:30","9:30","9:15"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'pünktlich'?",
       "opts":["рано","поздно","вовремя","быстро"],"ans":2},
      {"type":"fill","q":"___ stehe ich auf, dann frühstücke ich. (Сначала)",
       "opts":["Danach","Dann","Zuerst","Später"],"ans":2},
      {"type":"choice","q":"Welcher Monat kommt nach März?",
       "opts":["Februar","Mai","Januar","April"],"ans":3},
      {"type":"fill","q":"Ich ___ jeden Morgen um 7 Uhr auf. (aufwachen)",
       "opts":["gehe","wache","stehe","komme"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'selten'?",
       "opts":["часто","никогда","регулярно","редко"],"ans":3},
      {"type":"fill","q":"Wie ___ ist es? Es ist 10 Uhr. (который час?)",
       "opts":["viel","spät","alt","lange"],"ans":1},
      {"type":"choice","q":"Was ist 'der Feierabend'?",
       "opts":["обеденный перерыв","праздник","конец рабочего дня","выходной"],"ans":2},
    ]
  },
  6: {  # Einkaufen
    "vocab_extra":[
      {"de":"das Geschäft / der Laden","ru":"магазин","uz":"do'kon"},
      {"de":"die Bäckerei","ru":"булочная","uz":"non do'koni"},
      {"de":"die Metzgerei","ru":"мясная лавка","uz":"go'sht do'koni"},
      {"de":"die Drogerie","ru":"магазин косметики","uz":"dorixona (kosmetika)"},
      {"de":"der Markt","ru":"рынок","uz":"bozor"},
      {"de":"das Einkaufszentrum","ru":"торговый центр","uz":"savdo markazi"},
      {"de":"der Euro","ru":"евро","uz":"yevro"},
      {"de":"der Cent","ru":"цент","uz":"sent"},
      {"de":"das Wechselgeld","ru":"сдача","uz":"qaytim pul"},
      {"de":"der Kassenbon","ru":"кассовый чек","uz":"kassa cheki"},
      {"de":"die Quittung","ru":"квитанция","uz":"kvitansiya"},
      {"de":"reduziert / im Angebot","ru":"со скидкой / по акции","uz":"chegirma bilan"},
      {"de":"der Rabatt","ru":"скидка","uz":"chegirma"},
      {"de":"das Sonderangebot","ru":"специальное предложение","uz":"maxsus taklif"},
      {"de":"suchen","ru":"искать","uz":"qidirmoq"},
      {"de":"finden","ru":"находить","uz":"topmoq"},
      {"de":"nehmen","ru":"брать","uz":"olmoq"},
      {"de":"bestellen","ru":"заказывать","uz":"buyurtma bermoq"},
      {"de":"umtauschen","ru":"обменивать","uz":"almashtirmoq"},
      {"de":"zurückgeben","ru":"возвращать","uz":"qaytarmoq"},
      {"de":"das Kilogramm / das Gramm","ru":"килограмм / грамм","uz":"kilogramm / gramm"},
      {"de":"die Flasche","ru":"бутылка","uz":"shisha"},
      {"de":"die Dose","ru":"банка (консервная)","uz":"banka"},
      {"de":"die Tüte","ru":"пакет","uz":"paket"},
      {"de":"der Einkaufswagen","ru":"тележка (магазинная)","uz":"savatcha (supermarket)"},
      {"de":"der Einkaufskorb","ru":"корзина","uz":"savat"},
      {"de":"die Öffnungszeiten","ru":"часы работы","uz":"ish vaqti"},
      {"de":"geöffnet / geschlossen","ru":"открыто / закрыто","uz":"ochiq / yopiq"},
      {"de":"Haben Sie...?","ru":"У вас есть...?","uz":"Sizda ... bormi?"},
      {"de":"Kann ich helfen?","ru":"Могу ли я помочь?","uz":"Yordam bera olamanmi?"},
      {"de":"das Angebot","ru":"предложение","uz":"taklif"},
      {"de":"die Qualität","ru":"качество","uz":"sifat"},
      {"de":"günstig","ru":"выгодный","uz":"arzonli"},
      {"de":"preiswert","ru":"недорогой","uz":"narxi maqul"},
      {"de":"das Pfand","ru":"залог (за бутылку)","uz":"garov (idish uchun)"},
      {"de":"die Mehrwertsteuer (MwSt.)","ru":"НДС","uz":"QQS"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Bäckerei'?",
       "opts":["мясная лавка","булочная","рынок","аптека"],"ans":1},
      {"type":"fill","q":"Das kostet 5 Euro und 50 ___. (центов)",
       "opts":["Cent","Euro","Mark","Pfennig"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'umtauschen'?",
       "opts":["покупать","заказывать","обменивать","искать"],"ans":2},
      {"type":"fill","q":"Das Produkt ist ___. Es kostet nur 2 Euro. (выгодный)",
       "opts":["teuer","preiswert","schlecht","alt"],"ans":1},
      {"type":"choice","q":"Was ist 'das Wechselgeld'?",
       "opts":["скидка","цена","сдача","чек"],"ans":2},
      {"type":"fill","q":"Ich suche einen ___. (тележку для покупок)",
       "opts":["Kassenbon","Rabatt","Einkaufswagen","Laden"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'geöffnet'?",
       "opts":["закрыто","дорого","открыто","продаётся"],"ans":2},
      {"type":"fill","q":"Kann ich das ___ zurückgeben? (вернуть)",
       "opts":["umtauschen","kaufen","nehmen","finden"],"ans":0},
      {"type":"choice","q":"Was ist 'der Rabatt'?",
       "opts":["цена","скидка","квитанция","залог"],"ans":1},
    ]
  },
  7: {  # Freizeit und Hobbys
    "vocab_extra":[
      {"de":"das Fußball","ru":"футбол","uz":"futbol"},
      {"de":"das Tennis","ru":"теннис","uz":"tennis"},
      {"de":"das Basketball","ru":"баскетбол","uz":"basketbol"},
      {"de":"das Schwimmen","ru":"плавание","uz":"suzish"},
      {"de":"das Laufen / Joggen","ru":"бег","uz":"yugurish"},
      {"de":"das Radfahren","ru":"езда на велосипеде","uz":"velosipedda yurish"},
      {"de":"das Yoga","ru":"йога","uz":"yoga"},
      {"de":"die Gitarre spielen","ru":"играть на гитаре","uz":"gitara chalmoq"},
      {"de":"das Klavier spielen","ru":"играть на пианино","uz":"pianino chalmoq"},
      {"de":"malen / zeichnen","ru":"рисовать","uz":"chizmoq / bo'yamoq"},
      {"de":"basteln","ru":"мастерить / рукодельничать","uz":"qurollar yasash"},
      {"de":"wandern","ru":"ходить в походы","uz":"sayohat qilmoq (piyoda)"},
      {"de":"campen","ru":"ходить в кемпинг","uz":"lager qilmoq"},
      {"de":"angeln","ru":"рыбачить","uz":"baliq ovlamoq"},
      {"de":"stricken","ru":"вязать","uz":"to'qimoq"},
      {"de":"nähen","ru":"шить","uz":"tikmoq"},
      {"de":"sammeln","ru":"коллекционировать","uz":"yig'moq"},
      {"de":"das Konzert","ru":"концерт","uz":"konsert"},
      {"de":"das Museum","ru":"музей","uz":"muzey"},
      {"de":"die Ausstellung","ru":"выставка","uz":"ko'rgazma"},
      {"de":"das Stadion","ru":"стадион","uz":"stadion"},
      {"de":"das Schwimmbad","ru":"бассейн","uz":"basseyn"},
      {"de":"die Sporthalle","ru":"спортзал","uz":"sport zali"},
      {"de":"der Sportverein","ru":"спортивный клуб","uz":"sport klubi"},
      {"de":"trainieren","ru":"тренироваться","uz":"mashq qilmoq"},
      {"de":"das Spiel","ru":"игра","uz":"o'yin"},
      {"de":"gewinnen","ru":"выигрывать","uz":"yutmoq"},
      {"de":"verlieren","ru":"проигрывать","uz":"yutqazmoq"},
      {"de":"das Team","ru":"команда","uz":"jamoa"},
      {"de":"der Wettkampf","ru":"соревнование","uz":"musobaqa"},
      {"de":"spannend / aufregend","ru":"захватывающий / волнующий","uz":"qiziqarli / hayajonli"},
      {"de":"entspannen","ru":"расслабляться","uz":"dam olmoq"},
      {"de":"Freizeit haben","ru":"иметь свободное время","uz":"bo'sh vaqt bo'lmoq"},
      {"de":"ausgehen","ru":"выходить (в свет)","uz":"tashqariga chiqmoq"},
      {"de":"Freunde treffen","ru":"встречаться с друзьями","uz":"do'stlar bilan uchrashmoq"},
      {"de":"die Party","ru":"вечеринка","uz":"ziyofat"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was bedeutet 'wandern'?",
       "opts":["плавать","ходить в походы","танцевать","рисовать"],"ans":1},
      {"type":"fill","q":"Ich spiele gern ___. (футбол)",
       "opts":["Tennis","Basketball","Fußball","Volleyball"],"ans":2},
      {"type":"choice","q":"Was ist 'das Schwimmbad'?",
       "opts":["стадион","спортзал","бассейн","каток"],"ans":2},
      {"type":"fill","q":"Unser Team hat das Spiel ___. (выиграло)",
       "opts":["verloren","gespielt","gewonnen","gemacht"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'entspannen'?",
       "opts":["тренироваться","расслабляться","соревноваться","выигрывать"],"ans":1},
      {"type":"fill","q":"Ich ___ gern Gitarre. (играю)",
       "opts":["spiele","mache","lerne","höre"],"ans":0},
      {"type":"choice","q":"Was ist 'der Wettkampf'?",
       "opts":["тренировка","команда","игра","соревнование"],"ans":3},
      {"type":"fill","q":"Am Wochenende ___ ich Freunde. (встречаюсь)",
       "opts":["sehe","treffe","besuche","finde"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'basteln'?",
       "opts":["коллекционировать","вязать","мастерить","шить"],"ans":2},
    ]
  },
  8: {  # In der Stadt
    "vocab_extra":[
      {"de":"die Ampel","ru":"светофор","uz":"svetofor"},
      {"de":"der Zebrastreifen","ru":"пешеходный переход","uz":"piyodalar o'tish joyi"},
      {"de":"die Kreuzung","ru":"перекрёсток","uz":"chorrah"},
      {"de":"die Brücke","ru":"мост","uz":"ko'prik"},
      {"de":"der Platz","ru":"площадь","uz":"maydon"},
      {"de":"das Stadtzentrum","ru":"центр города","uz":"shahar markazi"},
      {"de":"der Vorort","ru":"пригород","uz":"shahar chetı"},
      {"de":"die U-Bahn","ru":"метро","uz":"metro"},
      {"de":"die Straßenbahn","ru":"трамвай","uz":"tramvay"},
      {"de":"der Bus","ru":"автобус","uz":"avtobus"},
      {"de":"die Haltestelle","ru":"остановка","uz":"bekat"},
      {"de":"das Taxi","ru":"такси","uz":"taksi"},
      {"de":"zu Fuß","ru":"пешком","uz":"piyoda"},
      {"de":"das Fahrrad","ru":"велосипед","uz":"velosiped"},
      {"de":"das Auto","ru":"автомобиль","uz":"mashina"},
      {"de":"das Kino","ru":"кинотеатр","uz":"kinoteatr"},
      {"de":"das Theater","ru":"театр","uz":"teatr"},
      {"de":"das Restaurant","ru":"ресторан","uz":"restoran"},
      {"de":"das Hotel","ru":"отель","uz":"mehmonxona"},
      {"de":"das Postamt","ru":"почта","uz":"pochta"},
      {"de":"das Polizeirevier","ru":"полицейский участок","uz":"politsiya bo'limi"},
      {"de":"die Feuerwehr","ru":"пожарная часть","uz":"o't o'chirish xizmati"},
      {"de":"das Krankenhaus","ru":"больница","uz":"kasalxona"},
      {"de":"die Schule","ru":"школа","uz":"maktab"},
      {"de":"die Universität","ru":"университет","uz":"universitet"},
      {"de":"weit / nah","ru":"далеко / близко","uz":"uzoq / yaqin"},
      {"de":"in der Nähe von","ru":"рядом с","uz":"yonida"},
      {"de":"gegenüber","ru":"напротив","uz":"qarshisida"},
      {"de":"an der Ecke","ru":"на углу","uz":"burchakda"},
      {"de":"die erste Straße links","ru":"первый поворот налево","uz":"birinchi ko'chada chapga"},
      {"de":"überqueren","ru":"пересекать","uz":"kesib o'tmoq"},
      {"de":"abbiegen","ru":"поворачивать","uz":"burilmoq"},
      {"de":"der Stadtplan","ru":"карта города","uz":"shahar xaritasi"},
      {"de":"Wie weit ist es?","ru":"Как далеко это?","uz":"Bu qancha uzoqlikda?"},
      {"de":"Zu Fuß dauert es...","ru":"Пешком это займёт...","uz":"Piyoda ... vaqt ketadi"},
      {"de":"mit dem Bus fahren","ru":"ехать на автобусе","uz":"avtobus bilan bormoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Ampel'?",
       "opts":["перекрёсток","пешеходный переход","светофор","мост"],"ans":2},
      {"type":"fill","q":"Ich fahre mit ___ U-Bahn. (артикль: die → mit der)",
       "opts":["dem","der","die","den"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'gegenüber'?",
       "opts":["рядом","напротив","за","перед"],"ans":1},
      {"type":"fill","q":"Die Haltestelle ist ___ der Ecke. (на углу)",
       "opts":["in","an","auf","bei"],"ans":1},
      {"type":"choice","q":"Was ist 'das Polizeirevier'?",
       "opts":["больница","пожарная часть","полицейский участок","почта"],"ans":2},
      {"type":"fill","q":"Gehen Sie geradeaus und dann ___. (налево)",
       "opts":["rechts","geradeaus","links","zurück"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'überqueren'?",
       "opts":["поворачивать","пересекать","идти прямо","искать"],"ans":1},
      {"type":"fill","q":"___ Fuß dauert es 10 Minuten. (пешком)",
       "opts":["Mit","Zu","Mit dem","Auf"],"ans":1},
      {"type":"choice","q":"Was ist 'der Zebrastreifen'?",
       "opts":["светофор","тротуар","пешеходный переход","перекрёсток"],"ans":2},
    ]
  },
}

EXT_A1_2 = {
  1: {  # Sprachen & Konnektoren
    "vocab_extra":[
      {"de":"Englisch","ru":"английский","uz":"inglizcha"},
      {"de":"Französisch","ru":"французский","uz":"fransuzcha"},
      {"de":"Spanisch","ru":"испанский","uz":"ispancha"},
      {"de":"Chinesisch","ru":"китайский","uz":"xitoycha"},
      {"de":"Arabisch","ru":"arabский","uz":"arabcha"},
      {"de":"Türkisch","ru":"турецкий","uz":"turkcha"},
      {"de":"Japanisch","ru":"японский","uz":"yaponcha"},
      {"de":"Polnisch","ru":"польский","uz":"polyakcha"},
      {"de":"die Grammatik","ru":"грамматика","uz":"grammatika"},
      {"de":"der Wortschatz","ru":"словарный запас","uz":"lug'at boyligi"},
      {"de":"die Aussprache","ru":"произношение","uz":"talaffuz"},
      {"de":"die Übung","ru":"упражнение","uz":"mashq"},
      {"de":"üben","ru":"практиковаться","uz":"mashq qilmoq"},
      {"de":"wiederholen","ru":"повторять","uz":"takrorlash"},
      {"de":"auswendig lernen","ru":"учить наизусть","uz":"yod olmoq"},
      {"de":"nachschlagen","ru":"смотреть в словаре","uz":"lug'atdan qidirmoq"},
      {"de":"das Wörterbuch","ru":"словарь","uz":"lug'at"},
      {"de":"der Fehler","ru":"ошибка","uz":"xato"},
      {"de":"korrigieren","ru":"исправлять","uz":"to'g'rilamoq"},
      {"de":"der Unterricht","ru":"урок / занятие","uz":"dars"},
      {"de":"die Prüfung","ru":"экзамен","uz":"imtihon"},
      {"de":"bestehen","ru":"сдать (экзамен)","uz":"o'tmoq (imtihon)"},
      {"de":"das Zertifikat","ru":"сертификат","uz":"sertifikat"},
      {"de":"der Muttersprachler","ru":"носитель языка","uz":"ona tilida gaplashuvchi"},
      {"de":"zweisprachig","ru":"двуязычный","uz":"ikki tilli"},
      {"de":"der Akzent","ru":"акцент","uz":"aksent"},
      {"de":"flüssig","ru":"бегло","uz":"ravon"},
      {"de":"Anfänger","ru":"начинающий","uz":"boshlang'ich"},
      {"de":"Fortgeschrittener","ru":"продвинутый","uz":"ilg'or"},
      {"de":"trotzdem","ru":"тем не менее","uz":"shunga qaramay"},
      {"de":"außerdem","ru":"кроме того","uz":"bundan tashqari"},
      {"de":"deshalb","ru":"поэтому","uz":"shuning uchun"},
      {"de":"obwohl","ru":"хотя","uz":"garchi"},
      {"de":"weil","ru":"потому что","uz":"chunki"},
      {"de":"wenn","ru":"когда / если","uz":"agar / qachon"},
      {"de":"dass","ru":"что (союз)","uz":"... deb (bog'lovchi)"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Welche Sprache spricht man in Frankreich?",
       "opts":["Spanisch","Englisch","Französisch","Italienisch"],"ans":2},
      {"type":"fill","q":"Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte. (потому что)",
       "opts":["aber","oder","weil","und"],"ans":2},
      {"type":"choice","q":"Was ist 'das Wörterbuch'?",
       "opts":["учебник","тетрадь","словарь","словарный запас"],"ans":2},
      {"type":"fill","q":"Er spricht Englisch ___, ohne Akzent. (свободно)",
       "opts":["gut","langsam","fließend","laut"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'korrigieren'?",
       "opts":["практиковаться","учить наизусть","исправлять","повторять"],"ans":2},
      {"type":"fill","q":"Ich weiß, ___ er Deutsch lernt. (что — союз)",
       "opts":["weil","obwohl","wenn","dass"],"ans":3},
      {"type":"choice","q":"Was bedeutet 'zweisprachig'?",
       "opts":["одноязычный","многоязычный","двуязычный","безъязычный"],"ans":2},
      {"type":"fill","q":"Er macht viele ___. (ошибок)",
       "opts":["Übungen","Fehler","Wörter","Kurse"],"ans":1},
      {"type":"choice","q":"Was ist ein 'Anfänger'?",
       "opts":["продвинутый","эксперт","начинающий","преподаватель"],"ans":2},
    ]
  },
  2: {  # Kleidung und Mode
    "vocab_extra":[
      {"de":"die Mütze","ru":"шапка","uz":"shapka"},
      {"de":"der Hut","ru":"шляпа","uz":"shlyapa"},
      {"de":"der Schal","ru":"шарф","uz":"sharf"},
      {"de":"die Handschuhe","ru":"перчатки","uz":"qo'lqop"},
      {"de":"die Socken","ru":"носки","uz":"paypoq"},
      {"de":"die Strümpfe","ru":"чулки / колготки","uz":"paypoqlar"},
      {"de":"die Stiefel","ru":"сапоги","uz":"etik"},
      {"de":"die Sandalen","ru":"сандалии","uz":"sandal"},
      {"de":"der Gürtel","ru":"ремень","uz":"kamar"},
      {"de":"die Krawatte","ru":"галстук","uz":"galstuk"},
      {"de":"der Anzug","ru":"костюм","uz":"kostyum"},
      {"de":"das T-Shirt","ru":"футболка","uz":"futbolka"},
      {"de":"die Jeans","ru":"джинсы","uz":"jins"},
      {"de":"der Mantel","ru":"пальто","uz":"palto"},
      {"de":"der Regenmantel","ru":"плащ","uz":"yomg'ir palto"},
      {"de":"die Uniform","ru":"форма","uz":"forma"},
      {"de":"das Kostüm","ru":"дамский костюм","uz":"ayollar kostyumi"},
      {"de":"das Kleid (lang)","ru":"длинное платье","uz":"uzun ko'ylak"},
      {"de":"die Bluse","ru":"блузка","uz":"bluzka"},
      {"de":"gelb / orange","ru":"жёлтый / оранжевый","uz":"sariq / to'q sariq"},
      {"de":"lila / rosa","ru":"фиолетовый / розовый","uz":"binafsha / pushti"},
      {"de":"braun / grau","ru":"коричневый / серый","uz":"jigarrang / kulrang"},
      {"de":"bunt","ru":"разноцветный","uz":"rangli"},
      {"de":"gestreift","ru":"полосатый","uz":"yo'l-yo'l"},
      {"de":"kariert","ru":"клетчатый","uz":"katakli"},
      {"de":"einfarbig","ru":"однотонный","uz":"bir rangli"},
      {"de":"modisch","ru":"модный","uz":"moda"},
      {"de":"altmodisch","ru":"немодный","uz":"eski moda"},
      {"de":"eng / weit","ru":"узкий / широкий","uz":"tor / keng"},
      {"de":"kurz / lang","ru":"короткий / длинный","uz":"qisqa / uzun"},
      {"de":"die Baumwolle","ru":"хлопок","uz":"paxta"},
      {"de":"die Wolle","ru":"шерсть","uz":"jun"},
      {"de":"die Seide","ru":"шёлк","uz":"ipak"},
      {"de":"das Leder","ru":"кожа","uz":"teri"},
      {"de":"waschen","ru":"стирать","uz":"yuvmoq"},
      {"de":"bügeln","ru":"гладить (утюгом)","uz":"dazmollash"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was sind 'die Handschuhe'?",
       "opts":["носки","шарф","перчатки","шапка"],"ans":2},
      {"type":"fill","q":"Das Hemd ist ___. Es hat Streifen. (полосатый)",
       "opts":["kariert","gestreift","bunt","einfarbig"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'modisch'?",
       "opts":["немодный","старый","модный","дешёвый"],"ans":2},
      {"type":"fill","q":"Die Hose ist zu ___. Ich brauche eine größere. (узкая)",
       "opts":["weit","kurz","eng","lang"],"ans":2},
      {"type":"choice","q":"Was ist 'die Baumwolle'?",
       "opts":["шёлк","шерсть","кожа","хлопок"],"ans":3},
      {"type":"fill","q":"Welche ___ hat das Kleid? Es ist rot. (цвет)",
       "opts":["Größe","Farbe","Länge","Form"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'bügeln'?",
       "opts":["стирать","сушить","гладить утюгом","вешать"],"ans":2},
      {"type":"fill","q":"Er trägt einen ___. (галстук)",
       "opts":["Schal","Gürtel","Hut","Krawatte"],"ans":3},
      {"type":"choice","q":"Was sind 'die Stiefel'?",
       "opts":["сандалии","кроссовки","сапоги","туфли"],"ans":2},
    ]
  },
  3: {  # Gesundheit und Körper
    "vocab_extra":[
      {"de":"der Arm","ru":"рука (от плеча)","uz":"qo'l (yelkadan)"},
      {"de":"das Knie","ru":"колено","uz":"tizza"},
      {"de":"der Fuß","ru":"ступня / нога","uz":"oyoq"},
      {"de":"der Finger","ru":"палец","uz":"barmoq"},
      {"de":"der Hals","ru":"шея / горло","uz":"bo'yin / tomoq"},
      {"de":"die Schulter","ru":"плечо","uz":"yelka"},
      {"de":"die Brust","ru":"грудь","uz":"ko'krak"},
      {"de":"das Ohr","ru":"ухо","uz":"quloq"},
      {"de":"das Auge","ru":"глаз","uz":"ko'z"},
      {"de":"die Nase","ru":"нос","uz":"burun"},
      {"de":"der Mund","ru":"рот","uz":"og'iz"},
      {"de":"die Zähne","ru":"зубы","uz":"tishlar"},
      {"de":"das Fieber","ru":"жар / температура","uz":"isitma"},
      {"de":"der Husten","ru":"кашель","uz":"yo'tal"},
      {"de":"der Schnupfen","ru":"насморк","uz":"tumov"},
      {"de":"die Erkältung","ru":"простуда","uz":"sovqotish"},
      {"de":"die Grippe","ru":"грипп","uz":"gripp"},
      {"de":"sich erholen","ru":"выздоравливать","uz":"tuzalmoq"},
      {"de":"das Rezept","ru":"рецепт","uz":"retsept"},
      {"de":"die Apotheke","ru":"аптека","uz":"dorixona"},
      {"de":"das Pflaster","ru":"пластырь","uz":"yopishqoq plastin"},
      {"de":"die Salbe","ru":"мазь","uz":"malham"},
      {"de":"der Verband","ru":"повязка / бинт","uz":"bog'lam"},
      {"de":"die Blutgruppe","ru":"группа крови","uz":"qon guruhi"},
      {"de":"allergisch gegen","ru":"аллергичный на","uz":"... ga allergiyasi bor"},
      {"de":"Ich bin gegen Penicillin allergisch.","ru":"У меня аллергия на пенициллин.","uz":"Menga penitsillin yoqmaydi."},
      {"de":"sich verletzen","ru":"получить травму","uz":"jarohatlash"},
      {"de":"brechen / gebrochen","ru":"сломать","uz":"sindirmoq"},
      {"de":"die Verletzung","ru":"травма","uz":"jarohat"},
      {"de":"der Krankenwagen","ru":"скорая помощь","uz":"tez yordam mashinasi"},
      {"de":"der Notfall","ru":"экстренный случай","uz":"favqulodda holat"},
      {"de":"Hilfe!","ru":"Помогите!","uz":"Yordam!"},
      {"de":"Rufen Sie den Arzt!","ru":"Вызовите врача!","uz":"Shifokor chaqiring!"},
      {"de":"das Wartezimmer","ru":"приёмная","uz":"kutish xonasi"},
      {"de":"die Krankenversicherung","ru":"медицинская страховка","uz":"tibbiy sug'urta"},
      {"de":"der Krankenschein","ru":"больничный лист","uz":"kasallik varaqasi"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was sind 'die Zähne'?",
       "opts":["пальцы","зубы","ногти","ресницы"],"ans":1},
      {"type":"fill","q":"Ich habe ___. Meine Nase läuft. (насморк)",
       "opts":["Fieber","Husten","Schnupfen","Bauchschmerzen"],"ans":2},
      {"type":"choice","q":"Was ist 'die Apotheke'?",
       "opts":["больница","клиника","аптека","кабинет врача"],"ans":2},
      {"type":"fill","q":"Er hat sich das Bein ___. (сломал)",
       "opts":["verletzt","gebrochen","geschnitten","verbrannt"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'sich erholen'?",
       "opts":["заболеть","получить травму","выздоравливать","кашлять"],"ans":2},
      {"type":"fill","q":"Rufen Sie ___! (скорую помощь)",
       "opts":["den Arzt","den Krankenwagen","die Polizei","die Feuerwehr"],"ans":1},
      {"type":"choice","q":"Was ist 'die Grippe'?",
       "opts":["кашель","насморк","простуда","грипп"],"ans":3},
      {"type":"fill","q":"Ich bin ___ Penicillin allergisch. (аллергичный на)",
       "opts":["mit","für","gegen","von"],"ans":2},
      {"type":"choice","q":"Was ist 'das Rezept'?",
       "opts":["аптека","лекарство","рецепт","больничный"],"ans":2},
    ]
  },
  4: {  # Arbeit und Beruf
    "vocab_extra":[
      {"de":"der Architekt","ru":"архитектор","uz":"me'mor"},
      {"de":"der Rechtsanwalt","ru":"адвокат","uz":"advokat"},
      {"de":"der Buchhalter","ru":"бухгалтер","uz":"buxgalter"},
      {"de":"der Programmierer","ru":"программист","uz":"dasturchi"},
      {"de":"der Krankenpfleger","ru":"медбрат / медсестра","uz":"hamshira"},
      {"de":"der Elektriker","ru":"электрик","uz":"elektrik"},
      {"de":"der Mechaniker","ru":"механик","uz":"mexanik"},
      {"de":"der Fahrer","ru":"водитель","uz":"haydovchi"},
      {"de":"der Koch","ru":"повар","uz":"oshpaz"},
      {"de":"der Friseur","ru":"парикмахер","uz":"sartarosh"},
      {"de":"der Polizist","ru":"полицейский","uz":"politsiyachi"},
      {"de":"der Soldat","ru":"солдат","uz":"askar"},
      {"de":"die Firma","ru":"фирма / компания","uz":"firma / kompaniya"},
      {"de":"die Abteilung","ru":"отдел","uz":"bo'lim"},
      {"de":"die Besprechung","ru":"совещание","uz":"kengash"},
      {"de":"der Kollege","ru":"коллега","uz":"hamkasb"},
      {"de":"der Vorgesetzte","ru":"руководитель","uz":"rahbar"},
      {"de":"der Angestellte","ru":"служащий","uz":"xodim"},
      {"de":"der Selbstständige","ru":"частный предприниматель","uz":"yakka tartibdagi tadbirkor"},
      {"de":"die Arbeitszeit","ru":"рабочее время","uz":"ish vaqti"},
      {"de":"die Pause","ru":"перерыв","uz":"tanaffus"},
      {"de":"die Kündigung","ru":"увольнение","uz":"ishdan bo'shatish"},
      {"de":"die Stelle suchen","ru":"искать работу","uz":"ish qidirmoq"},
      {"de":"sich bewerben","ru":"подавать заявку","uz":"ariza bermoq"},
      {"de":"das Vorstellungsgespräch","ru":"собеседование","uz":"suhbat"},
      {"de":"einstellen","ru":"принять на работу","uz":"ishga olmoq"},
      {"de":"die Probezeit","ru":"испытательный срок","uz":"sinov muddati"},
      {"de":"das Gehalt","ru":"оклад","uz":"maosh"},
      {"de":"die Gehaltserhöhung","ru":"повышение зарплаты","uz":"maosh oshirish"},
      {"de":"Urlaub nehmen","ru":"взять отпуск","uz":"ta'til olmoq"},
      {"de":"der Krankenurlaub","ru":"больничный","uz":"kasallik ta'tili"},
      {"de":"Homeoffice","ru":"удалённая работа","uz":"uydan ishlash"},
      {"de":"die Schichtarbeit","ru":"сменная работа","uz":"smenali ish"},
      {"de":"der Streik","ru":"забастовка","uz":"ish tashlash"},
      {"de":"der Gewerkschaft","ru":"профсоюз","uz":"kasaba uyushma"},
      {"de":"Vollzeit / Teilzeit","ru":"полный / неполный день","uz":"to'liq / qisman ish kuni"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Rechtsanwalt'?",
       "opts":["инженер","бухгалтер","адвокат","программист"],"ans":2},
      {"type":"fill","q":"Ich ___ mich für die Stelle beworben. (подал заявку, Perfekt)",
       "opts":["habe","bin","hatte","wurde"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'die Probezeit'?",
       "opts":["отпуск","испытательный срок","перерыв","увольнение"],"ans":1},
      {"type":"fill","q":"Er arbeitet ___, von 9 bis 17 Uhr. (полный рабочий день)",
       "opts":["Teilzeit","Schicht","Vollzeit","Homeoffice"],"ans":2},
      {"type":"choice","q":"Was ist 'die Abteilung'?",
       "opts":["совещание","фирма","коллега","отдел"],"ans":3},
      {"type":"fill","q":"Er hat eine ___. Er verlässt die Firma. (увольнение)",
       "opts":["Pause","Kündigung","Besprechung","Gehaltserhöhung"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'sich bewerben'?",
       "opts":["принять на работу","уволить","подавать заявку","работать"],"ans":2},
      {"type":"fill","q":"Ich nehme nächsten Monat ___. (отпуск)",
       "opts":["Urlaub","Pause","Schicht","Kündigung"],"ans":0},
      {"type":"choice","q":"Was ist 'der Vorgesetzte'?",
       "opts":["коллега","служащий","руководитель","секретарь"],"ans":2},
    ]
  },
  5: {  # Reisen und Verkehr
    "vocab_extra":[
      {"de":"das Schiff","ru":"корабль","uz":"kema"},
      {"de":"die Fähre","ru":"паром","uz":"parom"},
      {"de":"das Motorrad","ru":"мотоцикл","uz":"mototsikl"},
      {"de":"die Autobahn","ru":"автобан / шоссе","uz":"avtomobil yo'li"},
      {"de":"das Gleis","ru":"железнодорожный путь","uz":"temir yo'l"},
      {"de":"der Bahnsteig","ru":"платформа","uz":"platforma"},
      {"de":"der Schalter","ru":"касса / стойка","uz":"kassa / stend"},
      {"de":"die Abfahrt","ru":"отправление","uz":"jo'nab ketish"},
      {"de":"die Ankunft","ru":"прибытие","uz":"kelish"},
      {"de":"die Verspätung","ru":"опоздание / задержка","uz":"kechikish"},
      {"de":"pünktlich ankommen","ru":"прибыть вовремя","uz":"o'z vaqtida kelmoq"},
      {"de":"das Gepäck","ru":"багаж","uz":"yuk"},
      {"de":"der Rucksack","ru":"рюкзак","uz":"ryukzak"},
      {"de":"das Handgepäck","ru":"ручная кладь","uz":"qo'l yuki"},
      {"de":"einchecken","ru":"регистрироваться","uz":"ro'yxatdan o'tmoq"},
      {"de":"das Gate","ru":"выход на посадку","uz":"gate"},
      {"de":"der Grenzübergang","ru":"пограничный переход","uz":"chegara o'tish punkti"},
      {"de":"die Zollkontrolle","ru":"таможенный контроль","uz":"bojxona nazorati"},
      {"de":"der Reisepass","ru":"загранпаспорт","uz":"xorijiy pasport"},
      {"de":"das Visum","ru":"виза","uz":"viza"},
      {"de":"die Versicherung","ru":"страховка","uz":"sug'urta"},
      {"de":"das Reisebüro","ru":"туристическое бюро","uz":"turizm agentligi"},
      {"de":"die Unterkunft","ru":"жильё / размещение","uz":"turar joy"},
      {"de":"das Hostel","ru":"хостел","uz":"hostel"},
      {"de":"die Pension","ru":"пансион / гостевой дом","uz":"pansion"},
      {"de":"die Rezeption","ru":"ресепшн","uz":"retseptsiya"},
      {"de":"das Frühstück inklusive","ru":"завтрак включён","uz":"nonushta kiritilgan"},
      {"de":"die Halbpension","ru":"полупансион","uz":"yarim pansion"},
      {"de":"das Doppelzimmer","ru":"двухместный номер","uz":"ikki kishilik xona"},
      {"de":"das Einzelzimmer","ru":"одноместный номер","uz":"bir kishilik xona"},
      {"de":"die Seite im Internet suchen","ru":"искать в интернете","uz":"internetdan qidirmoq"},
      {"de":"online buchen","ru":"бронировать онлайн","uz":"onlayn band qilmoq"},
      {"de":"stornieren","ru":"отменять бронь","uz":"bekor qilmoq"},
      {"de":"der Reiseführer (Buch)","ru":"путеводитель","uz":"qo'llanma"},
      {"de":"die Landkarte","ru":"географическая карта","uz":"geografik xarita"},
      {"de":"die Währung","ru":"валюта","uz":"valyuta"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Verspätung'?",
       "opts":["прибытие","отправление","задержка","расписание"],"ans":2},
      {"type":"fill","q":"Der Zug fährt von Gleis ___ ab. (путь/платформа)",
       "opts":["Gate","Gleis","Schiff","Bahnsteig"],"ans":3},
      {"type":"choice","q":"Was bedeutet 'stornieren'?",
       "opts":["бронировать","регистрироваться","отменять бронь","платить"],"ans":2},
      {"type":"fill","q":"Ich habe ein ___ gebucht. Wir sind zwei Personen. (двухместный)",
       "opts":["Einzelzimmer","Hostel","Doppelzimmer","Pension"],"ans":2},
      {"type":"choice","q":"Was ist 'das Handgepäck'?",
       "opts":["чемодан","рюкзак","ручная кладь","большой багаж"],"ans":2},
      {"type":"fill","q":"Sie müssen durch die ___. (таможенный контроль)",
       "opts":["Zollkontrolle","Rezeption","Abfahrt","Ankunft"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'Frühstück inklusive'?",
       "opts":["завтрак платный","завтрак не включён","завтрак включён","только ужин"],"ans":2},
      {"type":"fill","q":"Ich brauche ein ___ für die Einreise. (визу)",
       "opts":["Reisepass","Ticket","Visum","Versicherung"],"ans":2},
      {"type":"choice","q":"Was ist 'die Rezeption'?",
       "opts":["ресторан","ресепшн","номер","гараж"],"ans":1},
    ]
  },
  6: {  # Das Wetter
    "vocab_extra":[
      {"de":"die Wolke / bewölkt","ru":"облако / облачный","uz":"bulut / bulutli"},
      {"de":"der Donner","ru":"гром","uz":"momaqaldiroq"},
      {"de":"der Blitz","ru":"молния","uz":"chaqmoq"},
      {"de":"das Gewitter","ru":"гроза","uz":"bo'ron"},
      {"de":"der Nebel / nebelig","ru":"туман / туманный","uz":"tuman / tumanli"},
      {"de":"der Frost","ru":"мороз","uz":"ayoz"},
      {"de":"das Eis (auf der Straße)","ru":"лёд (на дороге)","uz":"muz (yo'lda)"},
      {"de":"der Hagel","ru":"град","uz":"do'l"},
      {"de":"tauen","ru":"таять","uz":"erish"},
      {"de":"gefrieren","ru":"замерзать","uz":"muzlash"},
      {"de":"die Wettervorhersage","ru":"прогноз погоды","uz":"ob-havo bashorati"},
      {"de":"der Wetterbericht","ru":"метеосводка","uz":"ob-havo hisoboti"},
      {"de":"das Thermometer","ru":"термометр","uz":"termometr"},
      {"de":"die Luftfeuchtigkeit","ru":"влажность воздуха","uz":"havo namligi"},
      {"de":"der Luftdruck","ru":"атмосферное давление","uz":"atmosfera bosimi"},
      {"de":"Grad Celsius","ru":"градусы Цельсия","uz":"Selsiy darajasi"},
      {"de":"minus 5 Grad","ru":"минус 5 градусов","uz":"minus 5 daraja"},
      {"de":"angenehm","ru":"приятный","uz":"yoqimli"},
      {"de":"unangenehm","ru":"неприятный","uz":"yoqimsiz"},
      {"de":"schwül","ru":"душный","uz":"bo'g'uvchi"},
      {"de":"trocken / feucht","ru":"сухой / влажный","uz":"quruq / nam"},
      {"de":"der Regenschirm","ru":"зонт","uz":"soyabon"},
      {"de":"die Sonnenbrille","ru":"солнечные очки","uz":"quyosh ko'zoynagi"},
      {"de":"die Sonnencreme","ru":"крем от загара","uz":"quyoshdan himoya kremi"},
      {"de":"sich sonnen","ru":"загорать","uz":"quyoshda yotmoq"},
      {"de":"der Schneemann","ru":"снеговик","uz":"qo'g'irchoq (qordan)"},
      {"de":"Ski fahren","ru":"кататься на лыжах","uz":"changida uchmoq"},
      {"de":"das Hochwasser","ru":"наводнение","uz":"toshqin"},
      {"de":"die Dürre","ru":"засуха","uz":"qurg'oqchilik"},
      {"de":"der Sturm","ru":"шторм / буря","uz":"bo'ron"},
      {"de":"der Orkan","ru":"ураган","uz":"dovul"},
      {"de":"das Klima","ru":"климат","uz":"iqlim"},
      {"de":"das Kontinentalklima","ru":"континентальный климат","uz":"kontinental iqlim"},
      {"de":"der Klimawandel","ru":"изменение климата","uz":"iqlim o'zgarishi"},
      {"de":"der Treibhauseffekt","ru":"парниковый эффект","uz":"issiqxona effekti"},
      {"de":"global erwärmen","ru":"глобальное потепление","uz":"global isish"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Gewitter'?",
       "opts":["туман","снегопад","гроза","засуха"],"ans":2},
      {"type":"fill","q":"Es sind minus 10 ___. (градусов Цельсия)",
       "opts":["Grad Celsius","Kilometer","Meter","Stunden"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'schwül'?",
       "opts":["морозный","сухой","душный","ветреный"],"ans":2},
      {"type":"fill","q":"Vergiss den ___ nicht! Es regnet heute. (зонт)",
       "opts":["Mantel","Regenschirm","Schal","Hut"],"ans":1},
      {"type":"choice","q":"Was ist 'der Klimawandel'?",
       "opts":["прогноз погоды","изменение климата","парниковый эффект","засуха"],"ans":1},
      {"type":"fill","q":"Im Winter ___  das Wasser. (замерзает)",
       "opts":["taut","gefriert","regnet","schneit"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'die Dürre'?",
       "opts":["наводнение","гроза","засуха","ураган"],"ans":2},
      {"type":"fill","q":"Morgen gibt es laut ___ Regen. (прогнозу погоды)",
       "opts":["Thermometer","Wettervorhersage","Luftdruck","Klima"],"ans":1},
      {"type":"choice","q":"Was ist 'der Hagel'?",
       "opts":["снег","дождь","туман","град"],"ans":3},
    ]
  },
  7: {  # Feste und Feiern
    "vocab_extra":[
      {"de":"das Silvester","ru":"Новый год (31 декабря)","uz":"Yangi yil arafasi"},
      {"de":"der Neujahrstag","ru":"Новый год (1 января)","uz":"Yangi yil (1-yanvar)"},
      {"de":"der Karneval / der Fasching","ru":"карнавал","uz":"karnaval"},
      {"de":"der Muttertag","ru":"День матери","uz":"Onalar kuni"},
      {"de":"der Valentinstag","ru":"День святого Валентина","uz":"Sevgililer kuni"},
      {"de":"die Hochzeit","ru":"свадьба","uz":"to'y"},
      {"de":"die Taufe","ru":"крещение","uz":"suvga cho'mdirish"},
      {"de":"die Konfirmation","ru":"конфирмация","uz":"konfirmatsiya"},
      {"de":"die Jubiläum","ru":"юбилей","uz":"yubiley"},
      {"de":"das Festessen","ru":"праздничный ужин","uz":"bayramona ziyofat"},
      {"de":"der Sekt","ru":"шампанское","uz":"shampan"},
      {"de":"der Wein","ru":"вино","uz":"vino"},
      {"de":"anstoßen","ru":"чокаться","uz":"qadah ko'tarmoq"},
      {"de":"auf jemanden trinken","ru":"пить за кого-то","uz":"kimningdir sharafiga ichmoq"},
      {"de":"der Glückwunsch","ru":"поздравление","uz":"tabrik"},
      {"de":"Herzlichen Glückwunsch!","ru":"Поздравляю!","uz":"Tabriklayman!"},
      {"de":"Alles Gute!","ru":"Всего хорошего!","uz":"Omad tilayman!"},
      {"de":"die Einladung","ru":"приглашение","uz":"taklif"},
      {"de":"eingeladen sein","ru":"быть приглашённым","uz":"taklif qilingan bo'lmoq"},
      {"de":"die Dekoration","ru":"украшение","uz":"bezatish"},
      {"de":"der Luftballon","ru":"воздушный шар","uz":"sharlar"},
      {"de":"das Konfetti","ru":"конфетти","uz":"serpantin"},
      {"de":"die Girlande","ru":"гирлянда","uz":"girlyanda"},
      {"de":"das Feuerwerk","ru":"фейерверк","uz":"otashin"},
      {"de":"die Weihnachtsbäckerei","ru":"рождественская выпечка","uz":"Rojdestvo pishiriqlar"},
      {"de":"der Lebkuchen","ru":"пряник","uz":"zanjabil pechen'e"},
      {"de":"der Weihnachtsmarkt","ru":"рождественская ярмарка","uz":"Rojdestvo yarmarkasi"},
      {"de":"das Adventskalender","ru":"адвент-календарь","uz":"Advent taqvim"},
      {"de":"die Weihnachtsgans","ru":"рождественский гусь","uz":"Rojdestvo g'ozi"},
      {"de":"der Osterhas","ru":"пасхальный кролик","uz":"Pasxa quyoni"},
      {"de":"das Osterei","ru":"пасхальное яйцо","uz":"Pasxa tuxumi"},
      {"de":"fröhlich / lustig","ru":"весёлый / смешной","uz":"quvnoq / kulgili"},
      {"de":"gemütlich","ru":"уютный","uz":"qulay / iliq"},
      {"de":"festlich","ru":"праздничный","uz":"bayramlık"},
      {"de":"zusammen feiern","ru":"праздновать вместе","uz":"birgalikda nishonlamoq"},
      {"de":"das Programm / die Musik","ru":"программа / музыка","uz":"dastur / musiqa"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Silvester'?",
       "opts":["День матери","Пасха","Новый год (31 декабря)","Рождество"],"ans":2},
      {"type":"fill","q":"Wir ___ auf das neue Jahr an. (чокаемся)",
       "opts":["stoßen an","feiern","trinken","tanzen"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'gemütlich'?",
       "opts":["громкий","праздничный","уютный","грустный"],"ans":2},
      {"type":"fill","q":"Herzlichen ___! Du hast Geburtstag! (поздравление)",
       "opts":["Dank","Glückwunsch","Gruß","Abend"],"ans":1},
      {"type":"choice","q":"Was ist 'der Weihnachtsmarkt'?",
       "opts":["рождественская выпечка","рождественская ярмарка","адвент-календарь","пряники"],"ans":1},
      {"type":"fill","q":"Ich bin zur Hochzeit ___. (приглашён)",
       "opts":["eingeladen","eingeführt","eingeschlossen","eingestellt"],"ans":0},
      {"type":"choice","q":"Was ist 'der Lebkuchen'?",
       "opts":["шампанское","гирлянда","пряник","конфетти"],"ans":2},
      {"type":"fill","q":"Das Fest ist sehr ___. Alle haben Spaß! (весёлый)",
       "opts":["langweilig","traurig","festlich","fröhlich"],"ans":3},
      {"type":"choice","q":"Was bedeutet 'anstoßen'?",
       "opts":["петь","чокаться","танцевать","украшать"],"ans":1},
    ]
  },
  8: {  # Pläne und Zukunft
    "vocab_extra":[
      {"de":"der Wunsch","ru":"желание","uz":"istak"},
      {"de":"die Hoffnung","ru":"надежда","uz":"umid"},
      {"de":"die Absicht","ru":"намерение","uz":"niyat"},
      {"de":"vorhaben","ru":"планировать","uz":"niyat qilmoq"},
      {"de":"beabsichtigen","ru":"намереваться","uz":"niyat qilmoq"},
      {"de":"planen","ru":"планировать","uz":"rejalashtirishmoq"},
      {"de":"sich vornehmen","ru":"ставить себе задачу","uz":"o'z oldiga maqsad qo'ymoq"},
      {"de":"das Ziel","ru":"цель","uz":"maqsad"},
      {"de":"der Schritt","ru":"шаг","uz":"qadam"},
      {"de":"die Herausforderung","ru":"вызов","uz":"qiyinchilik"},
      {"de":"erfolgreich sein","ru":"быть успешным","uz":"muvaffaqiyatli bo'lmoq"},
      {"de":"scheitern","ru":"терпеть неудачу","uz":"muvaffaqiyatsiz bo'lmoq"},
      {"de":"weitermachen","ru":"продолжать","uz":"davom ettirmoq"},
      {"de":"aufgeben","ru":"сдаваться","uz":"taslim bo'lmoq"},
      {"de":"kämpfen für","ru":"бороться за","uz":"kurashmoq"},
      {"de":"das Diplom","ru":"диплом","uz":"diplom"},
      {"de":"der Masterabschluss","ru":"степень магистра","uz":"magistrlik darajasi"},
      {"de":"die Promotion","ru":"докторантура","uz":"doktorantura"},
      {"de":"der Doktortitel","ru":"степень доктора","uz":"doktorlik darajasi"},
      {"de":"ins Ausland gehen","ru":"уехать за рубеж","uz":"xorijga ketmoq"},
      {"de":"ein Unternehmen gründen","ru":"открыть предприятие","uz":"korxona ochmoq"},
      {"de":"Karriere machen","ru":"делать карьеру","uz":"karyera qilmoq"},
      {"de":"die Work-Life-Balance","ru":"баланс работы и жизни","uz":"ish-hayot balansi"},
      {"de":"in Rente gehen","ru":"выйти на пенсию","uz":"pensiyaga chiqmoq"},
      {"de":"der Ruhestand","ru":"пенсионный возраст","uz":"pensiya yoshi"},
      {"de":"das Erbe","ru":"наследство","uz":"meros"},
      {"de":"sparen","ru":"копить / экономить","uz":"tejash / yig'ish"},
      {"de":"investieren","ru":"инвестировать","uz":"investitsiya qilmoq"},
      {"de":"die Zukunftsperspektiven","ru":"перспективы на будущее","uz":"kelajak istiqbollari"},
      {"de":"nachhaltig leben","ru":"жить устойчиво","uz":"barqaror yashash"},
      {"de":"die Welt bereisen","ru":"путешествовать по миру","uz":"dunyoni sayohat qilmoq"},
      {"de":"Kinder bekommen","ru":"иметь детей","uz":"bola ko'rmoq"},
      {"de":"ein Haus kaufen","ru":"купить дом","uz":"uy sotib olmoq"},
      {"de":"glücklich sein","ru":"быть счастливым","uz":"baxtli bo'lmoq"},
      {"de":"realistisch / idealistisch","ru":"реалистичный / идеалистичный","uz":"realistik / idealistik"},
      {"de":"kurzfristig / langfristig","ru":"краткосрочный / долгосрочный","uz":"qisqa muddatli / uzoq muddatli"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was bedeutet 'scheitern'?",
       "opts":["успевать","планировать","терпеть неудачу","продолжать"],"ans":2},
      {"type":"fill","q":"Ich ___ vor, ins Ausland zu gehen. (планирую)",
       "opts":["habe","nehme","mache","gehe"],"ans":0},
      {"type":"choice","q":"Was ist 'die Herausforderung'?",
       "opts":["успех","цель","вызов/трудность","шаг"],"ans":2},
      {"type":"fill","q":"Er möchte ein Unternehmen ___. (открыть)",
       "opts":["machen","gründen","kaufen","finden"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'aufgeben'?",
       "opts":["продолжать","добиться","сдаваться","планировать"],"ans":2},
      {"type":"fill","q":"Ich spare Geld, um ein Haus zu ___. (купить)",
       "opts":["kaufen","bauen","mieten","suchen"],"ans":0},
      {"type":"choice","q":"Was ist 'der Masterabschluss'?",
       "opts":["диплом бакалавра","степень магистра","докторантура","сертификат"],"ans":1},
      {"type":"fill","q":"___ habe ich viele Ziele. (долгосрочные)",
       "opts":["Kurzfristig","Langfristig","Realistisch","Idealistisch"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'in Rente gehen'?",
       "opts":["начать работу","делать карьеру","выйти на пенсию","уехать за рубеж"],"ans":2},
    ]
  },
}
