"""
Extension: A2.1 + A2.2 — 36 additional vocab words + 9 additional exercises per lesson
After merging: 48 words + 12 exercises per lesson
"""

EXT_A2_1 = {
  1: {  # Biografien und Lebenslauf
    "vocab_extra":[
      {"de":"die Kindheit","ru":"детство","uz":"bolalik"},
      {"de":"die Jugend","ru":"юность","uz":"yoshlik"},
      {"de":"das Erwachsenenalter","ru":"взрослый возраст","uz":"voyaga yetganlik"},
      {"de":"der Rentner","ru":"пенсионер","uz":"pensioner"},
      {"de":"die Vergangenheit","ru":"прошлое","uz":"o'tmish"},
      {"de":"die Gegenwart","ru":"настоящее","uz":"hozir"},
      {"de":"die Zukunft","ru":"будущее","uz":"kelajak"},
      {"de":"der Werdegang","ru":"карьерный путь","uz":"karyera yo'li"},
      {"de":"die Grundschule","ru":"начальная школа","uz":"boshlang'ich maktab"},
      {"de":"die Hauptschule","ru":"основная школа","uz":"asosiy maktab"},
      {"de":"das Gymnasium","ru":"гимназия","uz":"gimnaziya"},
      {"de":"die Berufsschule","ru":"профессиональная школа","uz":"kasb-hunar maktabi"},
      {"de":"das Abitur","ru":"аттестат зрелости","uz":"maktab attestati"},
      {"de":"der Hochschulabschluss","ru":"высшее образование","uz":"oliy ma'lumot"},
      {"de":"der Bachelor","ru":"бакалавр","uz":"bakalavr"},
      {"de":"der Master","ru":"магистр","uz":"magistr"},
      {"de":"promovieren","ru":"защитить диссертацию","uz":"dissertatsiya himoya qilmoq"},
      {"de":"das Stipendium","ru":"стипендия","uz":"stipendiya"},
      {"de":"die Lehre / Ausbildung","ru":"ученичество","uz":"shogirdlik"},
      {"de":"das Praktikum","ru":"практика","uz":"amaliyot"},
      {"de":"die Laufbahn","ru":"карьерная лестница","uz":"karyera zinapoyasi"},
      {"de":"die Ernennung","ru":"назначение","uz":"tayinlash"},
      {"de":"befördern","ru":"повышать (по службе)","uz":"lavozimini oshirmoq"},
      {"de":"der Ruhestand","ru":"пенсия","uz":"pensiya"},
      {"de":"sich niederlassen","ru":"обосноваться","uz":"joylashmoq"},
      {"de":"auswandern","ru":"эмигрировать","uz":"emigratsiya qilmoq"},
      {"de":"einwandern","ru":"иммигрировать","uz":"immigratsiya qilmoq"},
      {"de":"die Herkunft","ru":"происхождение","uz":"kelib chiqish"},
      {"de":"stolz auf","ru":"гордый (чем-то)","uz":"... bilan faxrlanmoq"},
      {"de":"das Vorbild","ru":"образец для подражания","uz":"ibrat namunasi"},
      {"de":"inspirieren","ru":"вдохновлять","uz":"ilhomlantirmoq"},
      {"de":"die Biografie lesen","ru":"читать биографию","uz":"biografiya o'qimoq"},
      {"de":"berühmt werden","ru":"стать знаменитым","uz":"mashhur bo'lmoq"},
      {"de":"die Leistung","ru":"достижение","uz":"yutuq"},
      {"de":"auszeichnen","ru":"награждать","uz":"mukofotlamoq"},
      {"de":"der Preis / die Auszeichnung","ru":"приз / награда","uz":"mukofot"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Abitur'?",
       "opts":["диплом вуза","аттестат зрелости","профессиональная школа","стипендия"],"ans":1},
      {"type":"fill","q":"Er ___ früher als Arzt. (работал, Prät.)",
       "opts":["arbeitete","hatte","wurde","war"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'auswandern'?",
       "opts":["иммигрировать","обосноваться","эмигрировать","путешествовать"],"ans":2},
      {"type":"fill","q":"Sie hat ihr Studium mit dem ___ abgeschlossen. (высшее образование)",
       "opts":["Abitur","Praktikum","Hochschulabschluss","Stipendium"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'befördern'?",
       "opts":["уволить","назначить","повысить по службе","нанять"],"ans":2},
      {"type":"fill","q":"Er war sehr ___ auf seine Tochter. (гордый — auf+Akk.)",
       "opts":["stolz","froh","glücklich","zufrieden"],"ans":0},
      {"type":"choice","q":"Was ist 'das Praktikum'?",
       "opts":["стажировка","ученичество","стипендия","практика"],"ans":3},
      {"type":"fill","q":"Sie ___ viele Leistungen in ihrer Karriere. (достигла)",
       "opts":["hatte","zeigte","erzielte","machte"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'promovieren'?",
       "opts":["учиться в школе","получить бакалавра","защитить диссертацию","стажироваться"],"ans":2},
    ]
  },
  2: {  # Wohnen und Umziehen
    "vocab_extra":[
      {"de":"das Apartment","ru":"апартаменты","uz":"apartament"},
      {"de":"das Reihenhaus","ru":"таунхаус","uz":"qatorli uy"},
      {"de":"das Einfamilienhaus","ru":"особняк","uz":"alohida uy"},
      {"de":"die WG (Wohngemeinschaft)","ru":"коммунальная квартира","uz":"umumiy kvartira"},
      {"de":"das Studentenwohnheim","ru":"студенческое общежитие","uz":"talabalar yotoqxonasi"},
      {"de":"die Einzimmerwohnung","ru":"однокомнатная квартира","uz":"bir xonali kvartira"},
      {"de":"der Mietvertrag","ru":"договор аренды","uz":"ijara shartnomasi"},
      {"de":"unterschreiben","ru":"подписывать","uz":"imzolash"},
      {"de":"die Nebenkosten","ru":"коммунальные платежи","uz":"kommunal to'lovlar"},
      {"de":"die Stromrechnung","ru":"счёт за электричество","uz":"elektr hisob-fakturasi"},
      {"de":"die Wasserrechnung","ru":"счёт за воду","uz":"suv hisob-fakturasi"},
      {"de":"die Heizung","ru":"отопление","uz":"isitish"},
      {"de":"das Internet / der Router","ru":"интернет / роутер","uz":"internet / router"},
      {"de":"der Hausmeister","ru":"управдом / дворник","uz":"uy boshqaruvchisi"},
      {"de":"die Hausverwaltung","ru":"управляющая компания","uz":"uy boshqaruvi"},
      {"de":"die Besichtigung","ru":"осмотр","uz":"ko'zdan kechirish"},
      {"de":"das Exposé","ru":"описание объекта","uz":"mulk ta'rifi"},
      {"de":"die Maklergebühr","ru":"комиссия агента","uz":"agent komissiyasi"},
      {"de":"der Immobilienmakler","ru":"риелтор","uz":"rieltor"},
      {"de":"das Objekt","ru":"объект недвижимости","uz":"ko'chmas mulk ob'ekti"},
      {"de":"zentral gelegen","ru":"центрально расположенный","uz":"markazda joylashgan"},
      {"de":"ruhige Lage","ru":"тихое расположение","uz":"sokin joylashuv"},
      {"de":"die Ausstattung","ru":"оснащение","uz":"jihozlanish"},
      {"de":"der Parkplatz","ru":"парковочное место","uz":"parkovka joyi"},
      {"de":"der Dachboden","ru":"чердак","uz":"tom osti"},
      {"de":"die Waschküche","ru":"прачечная","uz":"kir yuvxona"},
      {"de":"der Fahrradkeller","ru":"велопарковка","uz":"velosiped parkingı"},
      {"de":"die Reparatur","ru":"ремонт","uz":"ta'mirlash"},
      {"de":"streichen","ru":"красить (стены)","uz":"bo'yamoq (devorlar)"},
      {"de":"tapezieren","ru":"клеить обои","uz":"devor qog'ozi yopishtirmoq"},
      {"de":"der Umzugswagen","ru":"грузовик для переезда","uz":"ko'chish mashinasi"},
      {"de":"einpacken / auspacken","ru":"упаковывать / распаковывать","uz":"qadoqlash / qadoqdan chiqarish"},
      {"de":"die Ummeldung","ru":"перерегистрация","uz":"qayta ro'yxatdan o'tish"},
      {"de":"anmelden","ru":"регистрироваться","uz":"ro'yxatdan o'tmoq"},
      {"de":"das Einwohnermeldeamt","ru":"паспортный стол","uz":"pasport stoli"},
      {"de":"nachbarschaftlich","ru":"соседский","uz":"qo'shnilik"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'eine WG'?",
       "opts":["особняк","коммунальная квартира","общежитие","таунхаус"],"ans":1},
      {"type":"fill","q":"Ich muss mich beim ___ anmelden. (паспортный стол)",
       "opts":["Makler","Hausmeister","Einwohnermeldeamt","Vermieter"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'tapezieren'?",
       "opts":["красить стены","клеить обои","ремонтировать","убирать"],"ans":1},
      {"type":"fill","q":"Die Wohnung ist ___ gelegen — direkt im Zentrum. (центрально)",
       "opts":["ruhig","zentral","schön","groß"],"ans":1},
      {"type":"choice","q":"Was ist 'die Maklergebühr'?",
       "opts":["залог","коммунальные платежи","комиссия агента","цена аренды"],"ans":2},
      {"type":"fill","q":"Ich ___ alle Sachen beim Umzug ein. (упаковываю)",
       "opts":["packe","bringe","nehme","stelle"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'die Ausstattung'?",
       "opts":["аренда","осмотр","оснащение","управление"],"ans":2},
      {"type":"fill","q":"Das Haus hat eine ___. Ich kann mein Auto dort stellen. (парковку)",
       "opts":["Waschküche","Garage","Heizung","Besichtigung"],"ans":1},
      {"type":"choice","q":"Was ist 'die Ummeldung'?",
       "opts":["регистрация","перерегистрация","снятие с учёта","подписание"],"ans":1},
    ]
  },
  3: {  # Medien und Kommunikation
    "vocab_extra":[
      {"de":"der Podcast","ru":"подкаст","uz":"podcast"},
      {"de":"der Blog","ru":"блог","uz":"blog"},
      {"de":"der Vlog","ru":"видеоблог","uz":"videoblog"},
      {"de":"der Influencer","ru":"инфлюенсер","uz":"influencer"},
      {"de":"viral gehen","ru":"стать вирусным","uz":"virusga aylanmoq"},
      {"de":"teilen / sharen","ru":"делиться","uz":"ulashmoq"},
      {"de":"liken","ru":"лайкать","uz":"layk bosmoq"},
      {"de":"der Feed","ru":"лента","uz":"tasma"},
      {"de":"das Profil","ru":"профиль","uz":"profil"},
      {"de":"die Privatsphäre","ru":"конфиденциальность","uz":"maxfiylik"},
      {"de":"der Datenschutz","ru":"защита данных","uz":"ma'lumotlarni himoya qilish"},
      {"de":"hacken","ru":"взламывать","uz":"xakerlash"},
      {"de":"der Spam","ru":"спам","uz":"spam"},
      {"de":"die Fake News","ru":"фейковые новости","uz":"soxta yangiliklar"},
      {"de":"Desinformation","ru":"дезинформация","uz":"dezinformatsiya"},
      {"de":"der Algorithmus","ru":"алгоритм","uz":"algoritm"},
      {"de":"streamen","ru":"стримить","uz":"to'g'ridan-to'g'ri efir"},
      {"de":"herunterladen","ru":"скачивать","uz":"yuklab olmoq"},
      {"de":"hochladen","ru":"загружать","uz":"yuklash"},
      {"de":"die Medienkompetenz","ru":"медиаграмотность","uz":"media savodxonligi"},
      {"de":"glaubwürdig","ru":"заслуживающий доверия","uz":"ishonchli"},
      {"de":"die Quelle prüfen","ru":"проверять источник","uz":"manba tekshirmoq"},
      {"de":"das Urheberrecht","ru":"авторское право","uz":"mualliflik huquqi"},
      {"de":"die Übertragung","ru":"трансляция","uz":"translyatsiya"},
      {"de":"live senden","ru":"транслировать в прямом эфире","uz":"to'g'ridan-to'g'ri uzatmoq"},
      {"de":"der Kommentar","ru":"комментарий","uz":"izoh"},
      {"de":"der Abonnent","ru":"подписчик","uz":"obunachi"},
      {"de":"kündigen (Abonnement)","ru":"отменять подписку","uz":"obunani bekor qilmoq"},
      {"de":"die Reichweite","ru":"охват","uz":"qamrov"},
      {"de":"das Netzwerk","ru":"сеть","uz":"tarmoq"},
      {"de":"offline / online","ru":"офлайн / онлайн","uz":"oflayn / onlayn"},
      {"de":"der Browser","ru":"браузер","uz":"brauzer"},
      {"de":"die Suchmaschine","ru":"поисковик","uz":"qidiruv tizimi"},
      {"de":"das Kabel / kabellos","ru":"провод / беспроводной","uz":"kabel / simsiz"},
      {"de":"die Meldung","ru":"уведомление","uz":"bildirishnoma"},
      {"de":"benachrichtigen","ru":"уведомлять","uz":"xabar bermoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was bedeutet 'viral gehen'?",
       "opts":["стать популярным в интернете","заразиться","стримить","загружать"],"ans":0},
      {"type":"fill","q":"Ich ___ das Video auf YouTube hoch. (загружаю)",
       "opts":["teile","lade","schicke","lese"],"ans":1},
      {"type":"choice","q":"Was sind 'Fake News'?",
       "opts":["реальные новости","видеоблог","фейковые новости","прямой эфир"],"ans":2},
      {"type":"fill","q":"Man sollte immer die ___ prüfen. (источник)",
       "opts":["Quelle","Reichweite","Meldung","Übertragung"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'der Datenschutz'?",
       "opts":["авторское право","защита данных","конфиденциальность","алгоритм"],"ans":1},
      {"type":"fill","q":"Er hat 10.000 ___. (подписчиков)",
       "opts":["Kommentare","Abonnenten","Likes","Profile"],"ans":1},
      {"type":"choice","q":"Was ist 'die Medienkompetenz'?",
       "opts":["подписка","медиаграмотность","спам","охват"],"ans":1},
      {"type":"fill","q":"Das Video ___ gerade live gesendet. (транслируется)",
       "opts":["wird","ist","hat","wurde"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'hacken'?",
       "opts":["загружать","делиться","лайкать","взламывать"],"ans":3},
    ]
  },
  4: {  # Gesundheit und Ernährung
    "vocab_extra":[
      {"de":"die Vollwertkost","ru":"полноценное питание","uz":"to'liq qiymatli ovqat"},
      {"de":"die Kohlenhydrate","ru":"углеводы","uz":"uglevodlar"},
      {"de":"das Eiweiß / Protein","ru":"белок","uz":"protein"},
      {"de":"das Fett","ru":"жир","uz":"yog'"},
      {"de":"die Ballaststoffe","ru":"клетчатка","uz":"tolalar"},
      {"de":"die Spurenelemente","ru":"микроэлементы","uz":"mikroelementlar"},
      {"de":"die Mahlzeit","ru":"приём пищи","uz":"ovqat qabul qilish"},
      {"de":"nüchtern","ru":"натощак","uz":"och qoringa"},
      {"de":"der Appetit","ru":"аппетит","uz":"ishtaha"},
      {"de":"das Übergewicht","ru":"лишний вес","uz":"ortiqcha vazn"},
      {"de":"das Untergewicht","ru":"недостаточный вес","uz":"yetarli bo'lmagan vazn"},
      {"de":"der Body-Mass-Index (BMI)","ru":"индекс массы тела","uz":"tana massasi indeksi"},
      {"de":"der Blutdruck","ru":"кровяное давление","uz":"qon bosimi"},
      {"de":"der Blutzucker","ru":"уровень сахара в крови","uz":"qondagi shakar miqdori"},
      {"de":"der Cholesterin","ru":"холестерин","uz":"xolesterin"},
      {"de":"Blut abnehmen","ru":"брать кровь","uz":"qon olmoq"},
      {"de":"die Untersuchung","ru":"обследование","uz":"tekshiruv"},
      {"de":"das Röntgen","ru":"рентген","uz":"rentgen"},
      {"de":"der Ultraschall","ru":"УЗИ","uz":"ultratovush"},
      {"de":"die Operation","ru":"операция","uz":"jarrohlik operatsiyasi"},
      {"de":"betäuben","ru":"обезболивать","uz":"og'riqni qoldirmoq"},
      {"de":"die Narkose","ru":"наркоз","uz":"narkoz"},
      {"de":"sich erholen","ru":"восстанавливаться","uz":"tiklash"},
      {"de":"die Reha","ru":"реабилитация","uz":"reabilitatsiya"},
      {"de":"psychisch gesund","ru":"психически здоровый","uz":"ruhiy sog'lom"},
      {"de":"der Therapeut","ru":"терапевт","uz":"terapevt"},
      {"de":"die Beratung","ru":"консультация","uz":"maslahat"},
      {"de":"Burnout","ru":"выгорание","uz":"charchash"},
      {"de":"der Schlafmangel","ru":"недосыпание","uz":"uyqusizlik"},
      {"de":"die Entspannung","ru":"расслабление","uz":"dam olish"},
      {"de":"meditieren","ru":"медитировать","uz":"meditatsiya qilmoq"},
      {"de":"der Fastentag","ru":"разгрузочный день","uz":"ro'za kuni"},
      {"de":"der Smoothie","ru":"смузи","uz":"smuzi"},
      {"de":"superfood","ru":"суперпродукт","uz":"superfud"},
      {"de":"glutenfrei","ru":"без глютена","uz":"glutensiz"},
      {"de":"laktosefrei","ru":"без лактозы","uz":"laktozasiz"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was sind 'Kohlenhydrate'?",
       "opts":["белки","жиры","углеводы","витамины"],"ans":2},
      {"type":"fill","q":"Der Arzt misst meinen ___. (кровяное давление)",
       "opts":["Blutdruck","Blutzucker","Cholesterin","BMI"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'nüchtern'?",
       "opts":["сытый","натощак","голодный","довольный"],"ans":1},
      {"type":"fill","q":"Das Essen ist ___, ohne Gluten. (без глютена)",
       "opts":["vegetarisch","glutenfrei","laktosefrei","bio"],"ans":1},
      {"type":"choice","q":"Was ist 'die Reha'?",
       "opts":["операция","наркоз","реабилитация","обследование"],"ans":2},
      {"type":"fill","q":"Er hat ___. Er schläft nur 4 Stunden. (недосыпание)",
       "opts":["Übergewicht","Burnout","Schlafmangel","Appetit"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'meditieren'?",
       "opts":["лечиться","расслабляться","медитировать","консультироваться"],"ans":2},
      {"type":"fill","q":"Der Arzt macht ein ___. (рентген)",
       "opts":["Ultraschall","Röntgen","Blutdruck","Blut"],"ans":1},
      {"type":"choice","q":"Was ist 'das Eiweiß'?",
       "opts":["углевод","жир","клетчатка","белок"],"ans":3},
    ]
  },
  5: {  # Natur und Umwelt
    "vocab_extra":[
      {"de":"der Regenwald","ru":"тропический лес","uz":"tropik o'rmon"},
      {"de":"die Wüste","ru":"пустыня","uz":"cho'l"},
      {"de":"die Steppe","ru":"степь","uz":"dasht"},
      {"de":"der Gletscher","ru":"ледник","uz":"muzlik"},
      {"de":"der Vulkan","ru":"вулкан","uz":"vulqon"},
      {"de":"das Erdbeben","ru":"землетрясение","uz":"zilzila"},
      {"de":"die Überschwemmung","ru":"наводнение","uz":"sel"},
      {"de":"der Waldbrand","ru":"лесной пожар","uz":"o'rmon yong'ini"},
      {"de":"die Artenvielfalt","ru":"биоразнообразие","uz":"biologik xilma-xillik"},
      {"de":"das Ökosystem","ru":"экосистема","uz":"ekosistema"},
      {"de":"der Lebensraum","ru":"среда обитания","uz":"yashash muhiti"},
      {"de":"das Aussterben","ru":"вымирание","uz":"yo'q bo'lib ketish"},
      {"de":"bedrohte Arten","ru":"исчезающие виды","uz":"yo'qolayotgan turlar"},
      {"de":"der Naturschutz","ru":"охрана природы","uz":"tabiatni muhofaza qilish"},
      {"de":"das Biosphärenreservat","ru":"биосферный заповедник","uz":"biosfera qo'riqxonasi"},
      {"de":"die Solaranlage","ru":"солнечная батарея","uz":"quyosh paneli"},
      {"de":"die Windkraftanlage","ru":"ветряная мельница","uz":"shamol turbinasi"},
      {"de":"der Atomstrom","ru":"атомная энергия","uz":"atom energiyasi"},
      {"de":"fossile Brennstoffe","ru":"ископаемое топливо","uz":"qazib olinadigan yoqilg'i"},
      {"de":"der CO2-Fußabdruck","ru":"углеродный след","uz":"uglerod izi"},
      {"de":"Treibhausgase","ru":"парниковые газы","uz":"issiqxona gazlari"},
      {"de":"die Erderwärmung","ru":"глобальное потепление","uz":"yer isishi"},
      {"de":"das Ozonloch","ru":"озоновая дыра","uz":"ozon teshigi"},
      {"de":"die Umweltverschmutzung","ru":"загрязнение окружающей среды","uz":"atrof-muhitni ifloslantirish"},
      {"de":"die Wasserverschmutzung","ru":"загрязнение воды","uz":"suvni ifloslantirish"},
      {"de":"die Luftverschmutzung","ru":"загрязнение воздуха","uz":"havoni ifloslantirish"},
      {"de":"der Plastikmüll","ru":"пластиковые отходы","uz":"plastik chiqindi"},
      {"de":"die Mülltrennung","ru":"сортировка мусора","uz":"chiqindi saralash"},
      {"de":"die Kompostierung","ru":"компостирование","uz":"kompostlash"},
      {"de":"nachhaltig produzieren","ru":"производить устойчиво","uz":"barqaror ishlab chiqarish"},
      {"de":"die Elektromobilität","ru":"электромобильность","uz":"elektr transport"},
      {"de":"der Fußabdruck reduzieren","ru":"уменьшать след","uz":"izni kamaytirmoq"},
      {"de":"das Klimaabkommen","ru":"климатическое соглашение","uz":"iqlim shartnomasi"},
      {"de":"die Umweltorganisation","ru":"экологическая организация","uz":"ekologik tashkilot"},
      {"de":"demonstrieren für","ru":"демонстрировать за","uz":"namoyish qilmoq"},
      {"de":"aktivistisch","ru":"активистский","uz":"aktivistik"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Aussterben'?",
       "opts":["размножение","биоразнообразие","вымирание","охрана природы"],"ans":2},
      {"type":"fill","q":"Die Windkraftanlage produziert ___ Energie. (возобновляемую)",
       "opts":["fossile","atomare","erneuerbare","schmutzige"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'die Mülltrennung'?",
       "opts":["компостирование","загрязнение","сортировка мусора","утилизация"],"ans":2},
      {"type":"fill","q":"Das ___ ist bedroht. (биоразнообразие)",
       "opts":["Ökosystem","Lebensraum","Aussterben","Artenvielfalt"],"ans":3},
      {"type":"choice","q":"Was sind 'fossile Brennstoffe'?",
       "opts":["солнечная энергия","ветровая энергия","ископаемое топливо","атомная энергия"],"ans":2},
      {"type":"fill","q":"Die ___ steigt wegen Treibhausgasen. (температура Земли)",
       "opts":["Luftverschmutzung","Erderwärmung","Überschwemmung","Dürre"],"ans":1},
      {"type":"choice","q":"Was ist 'das Biosphärenreservat'?",
       "opts":["загрязнённая зона","экологическая организация","биосферный заповедник","климатическое соглашение"],"ans":2},
      {"type":"fill","q":"Wir müssen den CO2-___ reduzieren. (след)",
       "opts":["Abgase","Fußabdruck","Ausstoß","Verbrauch"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'demonstrieren für'?",
       "opts":["протестовать против","демонстрировать за","игнорировать","молчать о"],"ans":1},
    ]
  },
  6: {  # Kulturleben und Ausgehen
    "vocab_extra":[
      {"de":"die Oper","ru":"опера","uz":"opera"},
      {"de":"die Symphonie","ru":"симфония","uz":"simfoniya"},
      {"de":"das Ballett","ru":"балет","uz":"balet"},
      {"de":"die Galerie","ru":"галерея","uz":"galereya"},
      {"de":"die Vernissage","ru":"вернисаж","uz":"vernisaj"},
      {"de":"der Regisseur","ru":"режиссёр","uz":"rejissor"},
      {"de":"der Schauspieler","ru":"актёр","uz":"artist"},
      {"de":"die Schauspielerin","ru":"актриса","uz":"aktrisа"},
      {"de":"der Sänger / die Sängerin","ru":"певец / певица","uz":"qo'shiqchi"},
      {"de":"der Maler","ru":"художник","uz":"rassom"},
      {"de":"der Bildhauer","ru":"скульптор","uz":"haykaltarosh"},
      {"de":"das Gemälde","ru":"картина","uz":"rasm"},
      {"de":"die Skulptur","ru":"скульптура","uz":"haykaltaroshlik"},
      {"de":"die Fotografie","ru":"фотография","uz":"fotografiya"},
      {"de":"die Literatur","ru":"литература","uz":"adabiyot"},
      {"de":"der Roman","ru":"роман","uz":"roman"},
      {"de":"die Kurzgeschichte","ru":"рассказ","uz":"qissa"},
      {"de":"der Dichter","ru":"поэт","uz":"shoir"},
      {"de":"das Gedicht","ru":"стихотворение","uz":"she'r"},
      {"de":"das Drama","ru":"драма","uz":"drama"},
      {"de":"die Komödie","ru":"комедия","uz":"komediya"},
      {"de":"der Thriller","ru":"триллер","uz":"triller"},
      {"de":"die Dokumentation","ru":"документальный фильм","uz":"hujjatli film"},
      {"de":"die Filmkritik","ru":"кинокритика","uz":"film sharhi"},
      {"de":"der Bestseller","ru":"бестселлер","uz":"bestseller"},
      {"de":"das Kulturgut","ru":"культурное достояние","uz":"madaniy meros"},
      {"de":"das Weltkulturerbe","ru":"всемирное культурное наследие","uz":"jahon madaniy merosi"},
      {"de":"der Kulturbetrieb","ru":"культурная индустрия","uz":"madaniyat sanoati"},
      {"de":"die Kulturhauptstadt","ru":"культурная столица","uz":"madaniyat poytaxti"},
      {"de":"das Kulturfestival","ru":"культурный фестиваль","uz":"madaniy festival"},
      {"de":"der Eintritt (frei)","ru":"вход (бесплатный)","uz":"kirish (bepul)"},
      {"de":"die Abendkasse","ru":"вечерняя касса","uz":"kechki kassa"},
      {"de":"Karten im Voraus kaufen","ru":"купить билеты заранее","uz":"oldindan chipta sotib olmoq"},
      {"de":"ausverkauft","ru":"распродан","uz":"sotilgan"},
      {"de":"der Beifall / klatschen","ru":"аплодисменты / хлопать","uz":"qarsak / chapak chalmoq"},
      {"de":"der Vorhang fällt","ru":"занавес падает","uz":"parda tushmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Vernissage'?",
       "opts":["концерт","вернисаж","опера","балет"],"ans":1},
      {"type":"fill","q":"Das Theater ist ___. Es gibt keine Karten mehr. (распродан)",
       "opts":["beliebt","geschlossen","ausverkauft","geöffnet"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'der Beifall'?",
       "opts":["занавес","рецензия","аплодисменты","постановка"],"ans":2},
      {"type":"fill","q":"Ich möchte Karten ___ kaufen. (заранее)",
       "opts":["später","abends","im Voraus","spontan"],"ans":2},
      {"type":"choice","q":"Was ist 'die Dokumentation'?",
       "opts":["комедия","триллер","документальный фильм","драма"],"ans":2},
      {"type":"fill","q":"Das ___ ist Weltkulturerbe. (культурное достояние)",
       "opts":["Kulturgut","Kulturbetrieb","Festival","Theater"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'das Weltkulturerbe'?",
       "opts":["культурная столица","всемирное культурное наследие","бестселлер","культурный фестиваль"],"ans":1},
      {"type":"fill","q":"Der Vorhang ___. Die Vorstellung ist zu Ende. (падает)",
       "opts":["öffnet","fällt","steigt","schwebt"],"ans":1},
      {"type":"choice","q":"Was ist 'der Regisseur'?",
       "opts":["актёр","певец","режиссёр","поэт"],"ans":2},
    ]
  },
  7: {  # Arbeitswelt und Karriere
    "vocab_extra":[
      {"de":"die Stellenanzeige","ru":"объявление о работе","uz":"ish e'loni"},
      {"de":"das Anforderungsprofil","ru":"требования к кандидату","uz":"nomzodga qo'yiladigan talablar"},
      {"de":"der Lebenslauf (tabellarisch)","ru":"резюме (таблицей)","uz":"rezyume (jadval)"},
      {"de":"das Anschreiben","ru":"сопроводительное письмо","uz":"qo'shimcha xat"},
      {"de":"die Referenz","ru":"рекомендация","uz":"tavsiya"},
      {"de":"der Headhunter","ru":"хедхантер","uz":"headhunter"},
      {"de":"das Assessment Center","ru":"центр оценки","uz":"assessment markazi"},
      {"de":"die Gehaltsverhandlung","ru":"переговоры о зарплате","uz":"maosh bo'yicha muzokaralar"},
      {"de":"das Gehaltsgespräch","ru":"разговор о зарплате","uz":"maosh suhbati"},
      {"de":"die Arbeitnehmerrechte","ru":"права работников","uz":"ishchi huquqlari"},
      {"de":"die Arbeitgeberpflichten","ru":"обязанности работодателя","uz":"ish beruvchi majburiyatlari"},
      {"de":"das Arbeitsverhältnis","ru":"трудовые отношения","uz":"mehnat munosabatlari"},
      {"de":"befristet / unbefristet","ru":"срочный / бессрочный","uz":"muddatli / muddatsiz"},
      {"de":"der Elternzeit","ru":"отпуск по уходу за ребёнком","uz":"bola tarbiyalash ta'tili"},
      {"de":"die Mutterschutzzeit","ru":"декретный отпуск","uz":"tug'ruqdan keyin ta'til"},
      {"de":"das Home Office","ru":"удалённая работа","uz":"uydan ishlash"},
      {"de":"agiles Arbeiten","ru":"гибкая методология работы","uz":"moslashuvchan ish usuli"},
      {"de":"das Start-up","ru":"стартап","uz":"startup"},
      {"de":"der Freelancer","ru":"фрилансер","uz":"frilanser"},
      {"de":"das Netzwerken","ru":"нетворкинг","uz":"networking"},
      {"de":"LinkedIn / Xing","ru":"профессиональные сети","uz":"professional tarmoqlar"},
      {"de":"berufliche Weiterbildung","ru":"профессиональное развитие","uz":"kasbiy rivojlanish"},
      {"de":"das Coaching","ru":"коучинг","uz":"kouching"},
      {"de":"der Mentor","ru":"наставник","uz":"mentor"},
      {"de":"die Work-Life-Balance","ru":"баланс работы и жизни","uz":"ish-hayot balansi"},
      {"de":"die Burnout-Prävention","ru":"профилактика выгорания","uz":"charchashni oldini olish"},
      {"de":"die Erfolgsmessung","ru":"измерение результатов","uz":"natijalarni o'lchash"},
      {"de":"das Feedback geben","ru":"давать обратную связь","uz":"fikr-mulohaza bermoq"},
      {"de":"das Teambuilding","ru":"командообразование","uz":"jamoa qurish"},
      {"de":"die Führungskraft","ru":"руководитель","uz":"rahbar"},
      {"de":"die Unternehmenskultur","ru":"корпоративная культура","uz":"korporativ madaniyat"},
      {"de":"das Leitbild","ru":"миссия компании","uz":"kompaniya missiyasi"},
      {"de":"der Mehrwert","ru":"добавленная ценность","uz":"qo'shimcha qiymat"},
      {"de":"Umsatz steigern","ru":"увеличивать оборот","uz":"aylanmani oshirmoq"},
      {"de":"Kosten senken","ru":"снижать затраты","uz":"xarajatlarni kamaytirmoq"},
      {"de":"profitabel","ru":"прибыльный","uz":"foydali"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Anschreiben'?",
       "opts":["резюме","рекомендация","сопроводительное письмо","объявление о работе"],"ans":2},
      {"type":"fill","q":"Der Vertrag ist ___. Er endet nach 2 Jahren. (срочный)",
       "opts":["unbefristet","befristet","agil","remote"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'die Gehaltsverhandlung'?",
       "opts":["объявление о зарплате","переговоры о зарплате","выплата зарплаты","повышение зарплаты"],"ans":1},
      {"type":"fill","q":"Sie ist ___ in der Firma. (руководитель)",
       "opts":["Freelancer","Führungskraft","Mentor","Headhunter"],"ans":1},
      {"type":"choice","q":"Was ist 'das Teambuilding'?",
       "opts":["нетворкинг","коучинг","командообразование","миссия компании"],"ans":2},
      {"type":"fill","q":"Ich arbeite als ___ — ohne festen Arbeitgeber. (фрилансер)",
       "opts":["Mentor","Coach","Freelancer","Headhunter"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'Umsatz steigern'?",
       "opts":["снижать затраты","увеличивать оборот","измерять результаты","давать обратную связь"],"ans":1},
      {"type":"fill","q":"Die ___ ist wichtig für das Wohlbefinden. (баланс работы и жизни)",
       "opts":["Unternehmenskultur","Work-Life-Balance","Burnout-Prävention","Erfolgsmessung"],"ans":1},
      {"type":"choice","q":"Was ist 'profitabel'?",
       "opts":["убыточный","нейтральный","прибыльный","бесплатный"],"ans":2},
    ]
  },
  8: {  # Reisen und Tourismus
    "vocab_extra":[
      {"de":"die Kreuzfahrt","ru":"круиз","uz":"kruiz"},
      {"de":"die Safari","ru":"сафари","uz":"safari"},
      {"de":"der Urlaub","ru":"отпуск","uz":"ta'til"},
      {"de":"die Reisebeschränkungen","ru":"ограничения на поездки","uz":"sayohat cheklovlari"},
      {"de":"die Einreisebestimmungen","ru":"правила въезда","uz":"kirish qoidalari"},
      {"de":"das Transitvisum","ru":"транзитная виза","uz":"tranzit viza"},
      {"de":"die Sehenswürdigkeiten besichtigen","ru":"осматривать достопримечательности","uz":"diqqatga sazovor joylarni ko'rmoq"},
      {"de":"der Reiseführer (Person)","ru":"гид","uz":"gid"},
      {"de":"die Stadtrundfahrt","ru":"экскурсия по городу (на транспорте)","uz":"shahar bo'ylab avtomobil sayohati"},
      {"de":"die Stadtführung (zu Fuß)","ru":"пешая экскурсия","uz":"piyoda shahar sayohati"},
      {"de":"die Besichtigung","ru":"осмотр","uz":"ko'zdan kechirish"},
      {"de":"der Eintrittspreis","ru":"стоимость входа","uz":"kirish narxi"},
      {"de":"das Tourismusministerium","ru":"министерство туризма","uz":"turizm vazirligi"},
      {"de":"das Massentourismus","ru":"массовый туризм","uz":"ommaviy turizm"},
      {"de":"der Ökotourismus","ru":"экотуризм","uz":"ekoturizm"},
      {"de":"das Backpacking","ru":"бэкпекинг","uz":"ryuksak bilan sayohat"},
      {"de":"Rucksacktourist","ru":"турист с рюкзаком","uz":"ryuksak bilan sayohatchı"},
      {"de":"die All-inclusive-Reise","ru":"путёвка «всё включено»","uz":"\"hammasi kiritilgan\" sayohat"},
      {"de":"die Pauschalreise","ru":"туристический пакет","uz":"turistik paket"},
      {"de":"der Reiseveranstalter","ru":"туроператор","uz":"turizm operatori"},
      {"de":"der Reiseschaden","ru":"ущерб от поездки","uz":"sayohat zarari"},
      {"de":"die Reisekrankenversicherung","ru":"туристическая медицинская страховка","uz":"turist tibbiy sug'urtasi"},
      {"de":"der Kulturaustausch","ru":"культурный обмен","uz":"madaniyat almashinuvi"},
      {"de":"der Gastgeber","ru":"хозяин","uz":"mezbon"},
      {"de":"der Couchsurfer","ru":"каучсёрфер","uz":"couchsurfer"},
      {"de":"das Airbnb","ru":"аирбнб (аренда жилья)","uz":"xususiy turar joy ijarasi"},
      {"de":"die Unterkunft buchen","ru":"бронировать жильё","uz":"turar joy band qilmoq"},
      {"de":"früh buchen","ru":"бронировать заранее","uz":"oldindan band qilmoq"},
      {"de":"last minute","ru":"в последний момент","uz":"so'nggi lahzada"},
      {"de":"die Hochsaison","ru":"высокий сезон","uz":"yuqori mavsum"},
      {"de":"die Nebensaison","ru":"низкий сезон","uz":"past mavsum"},
      {"de":"die Heimreise","ru":"обратная дорога домой","uz":"uyga qaytish"},
      {"de":"der Jetlag","ru":"джетлаг","uz":"jetlag"},
      {"de":"Fotos machen","ru":"делать фото","uz":"suratga olmoq"},
      {"de":"die Erinnerungsfotos","ru":"памятные фото","uz":"xotira rasmlari"},
      {"de":"das Reisetagebuch","ru":"путевой дневник","uz":"sayohat kundaligi"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'die Kreuzfahrt'?",
       "opts":["сафари","экскурсия","круиз","пешая прогулка"],"ans":2},
      {"type":"fill","q":"Ich buche eine ___ Reise — alles ist dabei. (путёвку всё включено)",
       "opts":["Pauschalreise","Backpacking","Safari","Kreuzfahrt"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'der Jetlag'?",
       "opts":["задержка рейса","смена часовых поясов","джетлаг","усталость от поездки"],"ans":2},
      {"type":"fill","q":"In der ___ ist alles teurer. (высокий сезон)",
       "opts":["Nebensaison","Hochsaison","Reisezeit","Hauptzeit"],"ans":1},
      {"type":"choice","q":"Was ist 'der Ökotourismus'?",
       "opts":["массовый туризм","бэкпекинг","экотуризм","круиз"],"ans":2},
      {"type":"fill","q":"Er schreibt alles in sein ___. (путевой дневник)",
       "opts":["Reisetagebuch","Reiseführer","Souvenir","Exposé"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'last minute'?",
       "opts":["заблаговременно","в последний момент","слишком поздно","за месяц"],"ans":1},
      {"type":"fill","q":"Die ___ überprüft alle Dokumente. (правила въезда)",
       "opts":["Einreisebestimmungen","Zollkontrolle","Reisekasse","Buchung"],"ans":0},
      {"type":"choice","q":"Was ist 'der Kulturaustausch'?",
       "opts":["культурный шок","культурный обмен","культурная столица","культурное наследие"],"ans":1},
    ]
  },
}

EXT_A2_2 = {
  1: {  # Schule und Bildung
    "vocab_extra":[
      {"de":"der Stundenplan","ru":"расписание","uz":"dars jadvali"},
      {"de":"das Fach","ru":"предмет","uz":"fan"},
      {"de":"Mathematik","ru":"математика","uz":"matematika"},
      {"de":"Physik","ru":"физика","uz":"fizika"},
      {"de":"Chemie","ru":"химия","uz":"kimyo"},
      {"de":"Biologie","ru":"биология","uz":"biologiya"},
      {"de":"Geschichte","ru":"история","uz":"tarix"},
      {"de":"Geografie","ru":"география","uz":"geografiya"},
      {"de":"Kunst","ru":"изобразительное искусство","uz":"tasviriy san'at"},
      {"de":"Musik","ru":"музыка","uz":"musiqa"},
      {"de":"Sport","ru":"физкультура","uz":"jismoniy tarbiya"},
      {"de":"Informatik","ru":"информатика","uz":"informatika"},
      {"de":"Wirtschaft","ru":"экономика","uz":"iqtisodiyot"},
      {"de":"die Klasse","ru":"класс","uz":"sinf"},
      {"de":"der Schüler","ru":"ученик","uz":"o'quvchi"},
      {"de":"die Lehrerin","ru":"учительница","uz":"o'qituvchi (ayol)"},
      {"de":"der Direktor","ru":"директор","uz":"direktor"},
      {"de":"die Schulpflicht","ru":"обязательное образование","uz":"majburiy ta'lim"},
      {"de":"das Schuljahr","ru":"учебный год","uz":"o'quv yili"},
      {"de":"das Halbjahr","ru":"полугодие","uz":"yarim yillik"},
      {"de":"die Ferien","ru":"каникулы","uz":"ta'til"},
      {"de":"das Klassenzimmer","ru":"классная комната","uz":"sinf xonasi"},
      {"de":"die Tafel","ru":"доска","uz":"doska"},
      {"de":"der Stift / der Kugelschreiber","ru":"карандаш / ручка","uz":"qalam / ruchka"},
      {"de":"das Heft","ru":"тетрадь","uz":"daftar"},
      {"de":"das Lehrbuch","ru":"учебник","uz":"darslik"},
      {"de":"die Hausaufgaben machen","ru":"делать домашнее задание","uz":"uy vazifasini bajarmoq"},
      {"de":"schwänzen","ru":"прогуливать (уроки)","uz":"darsni qochirmoq"},
      {"de":"der Abschluss","ru":"окончание / выпуск","uz":"bitirish"},
      {"de":"das Abitur machen","ru":"сдать аттестат","uz":"attestat olmoq"},
      {"de":"der Numerus clausus (NC)","ru":"минимальный балл","uz":"minimal ball"},
      {"de":"das Stipendium beantragen","ru":"подавать на стипендию","uz":"stipendiyaga ariza bermoq"},
      {"de":"das duale Ausbildungssystem","ru":"дуальная система образования","uz":"ikkilamchi ta'lim tizimi"},
      {"de":"der Ausbilder","ru":"наставник (производственный)","uz":"ustoz (ishlab chiqarish)"},
      {"de":"die Gesellenprüfung","ru":"квалификационный экзамен","uz":"malaka imtihoni"},
      {"de":"der Meistertitel","ru":"звание мастера","uz":"usta unvoni"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Stundenplan'?",
       "opts":["учебник","расписание","тетрадь","оценка"],"ans":1},
      {"type":"fill","q":"Er hat die ___ bestanden. (квалификационный экзамен)",
       "opts":["Prüfung","Gesellenprüfung","Abitur","Note"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'schwänzen'?",
       "opts":["учиться усердно","прогуливать уроки","сдавать экзамен","получать оценку"],"ans":1},
      {"type":"fill","q":"Das ___ dauert von August bis Juli. (учебный год)",
       "opts":["Halbjahr","Schuljahr","Semester","Quartal"],"ans":1},
      {"type":"choice","q":"Was ist 'das duale Ausbildungssystem'?",
       "opts":["дистанционное образование","дуальная система","частная школа","университет"],"ans":1},
      {"type":"fill","q":"Die Schüler haben drei Wochen ___. (каникулы)",
       "opts":["Ferien","Pausen","Stunden","Fächer"],"ans":0},
      {"type":"choice","q":"Was bedeutet 'der Numerus clausus'?",
       "opts":["минимальный балл для вуза","название экзамена","вид стипендии","тип школы"],"ans":0},
      {"type":"fill","q":"Er macht das ___. Er verlässt die Schule nach 12 Jahren. (аттестат)",
       "opts":["Abitur","Praktikum","Stipendium","Studium"],"ans":0},
      {"type":"choice","q":"Was ist 'der Ausbilder'?",
       "opts":["ученик","директор","учитель","наставник на производстве"],"ans":3},
    ]
  },
  2: {  # Technik im Alltag
    "vocab_extra":[
      {"de":"das Betriebssystem","ru":"операционная система","uz":"operatsion tizim"},
      {"de":"der Arbeitsspeicher (RAM)","ru":"оперативная память","uz":"operativ xotira"},
      {"de":"die Festplatte","ru":"жёсткий диск","uz":"qattiq disk"},
      {"de":"der USB-Stick","ru":"флешка","uz":"flesh-disk"},
      {"de":"der Drucker","ru":"принтер","uz":"printer"},
      {"de":"der Scanner","ru":"сканер","uz":"skaner"},
      {"de":"die Webcam","ru":"веб-камера","uz":"veb-kamera"},
      {"de":"der Kopfhörer","ru":"наушники","uz":"quloqchin"},
      {"de":"der Lautsprecher","ru":"динамик","uz":"dinamik"},
      {"de":"der Monitor","ru":"монитор","uz":"monitor"},
      {"de":"die Maus (Computer)","ru":"мышь (компьютерная)","uz":"sichqoncha"},
      {"de":"die Tastatur","ru":"клавиатура","uz":"klaviatura"},
      {"de":"das Passwort","ru":"пароль","uz":"parol"},
      {"de":"das WLAN / WiFi","ru":"WiFi","uz":"WiFi"},
      {"de":"die Verbindung","ru":"соединение","uz":"ulanish"},
      {"de":"abstürzen","ru":"зависать / рушиться","uz":"ishdan chiqmoq"},
      {"de":"neu starten","ru":"перезагружать","uz":"qayta ishga tushirmoq"},
      {"de":"sichern / backup","ru":"создавать резервную копию","uz":"zaxira nusxa yaratmoq"},
      {"de":"löschen","ru":"удалять","uz":"o'chirmoq"},
      {"de":"kopieren / einfügen","ru":"копировать / вставить","uz":"nusxa ko'chirish / joylash"},
      {"de":"das Update installieren","ru":"устанавливать обновление","uz":"yangilanishni o'rnatmoq"},
      {"de":"der Virenscanner","ru":"антивирус","uz":"antivirus"},
      {"de":"verschlüsseln","ru":"шифровать","uz":"shifrlash"},
      {"de":"die Zwei-Faktor-Authentifizierung","ru":"двухфакторная аутентификация","uz":"ikki bosqichli autentifikatsiya"},
      {"de":"die Datensicherheit","ru":"безопасность данных","uz":"ma'lumotlar xavfsizligi"},
      {"de":"der QR-Code","ru":"QR-код","uz":"QR-kod"},
      {"de":"der digitale Ausweis","ru":"цифровое удостоверение","uz":"raqamli guvohnoma"},
      {"de":"die KI (Künstliche Intelligenz)","ru":"ИИ","uz":"Sun'iy intellekt"},
      {"de":"maschinelles Lernen","ru":"машинное обучение","uz":"mashinali o'rganish"},
      {"de":"der Chatbot","ru":"чат-бот","uz":"chatbot"},
      {"de":"die Automatisierung","ru":"автоматизация","uz":"avtomatlashtirish"},
      {"de":"der 3D-Drucker","ru":"3D-принтер","uz":"3D-printer"},
      {"de":"das Smart Home","ru":"умный дом","uz":"aqlli uy"},
      {"de":"der Sprachassistent","ru":"голосовой помощник","uz":"ovozli yordamchi"},
      {"de":"die Blockchain","ru":"блокчейн","uz":"blokcheyn"},
      {"de":"der Avatar","ru":"аватар","uz":"avatar"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Arbeitsspeicher'?",
       "opts":["жёсткий диск","флешка","оперативная память","монитор"],"ans":2},
      {"type":"fill","q":"Mein Computer ist ___. Ich muss ihn neu starten. (завис)",
       "opts":["kaputt","abgestürzt","gelöscht","aktualisiert"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'sichern'?",
       "opts":["удалять","шифровать","копировать","создавать резервную копию"],"ans":3},
      {"type":"fill","q":"Ich benutze einen ___ gegen Viren. (антивирус)",
       "opts":["Router","Virenscanner","Drucker","Scanner"],"ans":1},
      {"type":"choice","q":"Was ist 'das Smart Home'?",
       "opts":["умный телефон","умный дом","умная машина","умная камера"],"ans":1},
      {"type":"fill","q":"Er spricht mit dem ___. (голосовым помощником)",
       "opts":["Chatbot","Sprachassistent","Avatar","Monitor"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'die Automatisierung'?",
       "opts":["машинное обучение","блокчейн","автоматизация","шифрование"],"ans":2},
      {"type":"fill","q":"Das ___ läuft auf Windows. (операционная система)",
       "opts":["Betriebssystem","Programm","Update","Passwort"],"ans":0},
      {"type":"choice","q":"Was ist 'die Zwei-Faktor-Authentifizierung'?",
       "opts":["двойное шифрование","двухфакторная аутентификация","два пароля","двойная защита"],"ans":1},
    ]
  },
  3: {  # Dienstleistungen und Behörden
    "vocab_extra":[
      {"de":"das Standesamt","ru":"ЗАГС","uz":"fuqarolik holati aktlari idorasi"},
      {"de":"das Finanzamt","ru":"налоговая инспекция","uz":"soliq inspeksiyasi"},
      {"de":"die Ausländerbehörde","ru":"отдел по делам иностранцев","uz":"chet elliklar bo'limi"},
      {"de":"das Arbeitsamt / Jobcenter","ru":"центр занятости","uz":"bandlik markazi"},
      {"de":"die Krankenkasse","ru":"касса медицинского страхования","uz":"tibbiy sug'urta kassasi"},
      {"de":"die Rentenversicherung","ru":"пенсионное страхование","uz":"pensiya sug'urtasi"},
      {"de":"die Steuererklärung","ru":"налоговая декларация","uz":"soliq deklaratsiyasi"},
      {"de":"der Personalausweis","ru":"паспорт (внутренний)","uz":"ichki pasport"},
      {"de":"der Reisepass","ru":"загранпаспорт","uz":"xorijiy pasport"},
      {"de":"die Aufenthaltserlaubnis","ru":"вид на жительство","uz":"yashash ruxsati"},
      {"de":"das Einbürgerungsverfahren","ru":"процедура натурализации","uz":"fuqarolikka qabul qilish"},
      {"de":"die Staatsbürgerschaft","ru":"гражданство","uz":"fuqarolik"},
      {"de":"beglaubigen","ru":"заверять","uz":"tasdiqlash"},
      {"de":"notariell beglaubigt","ru":"нотариально заверенный","uz":"notarial tasdiqlangan"},
      {"de":"die Übersetzung (amtlich)","ru":"официальный перевод","uz":"rasmiy tarjima"},
      {"de":"der Dolmetscher","ru":"переводчик (устный)","uz":"tarjimon (og'zaki)"},
      {"de":"die Vollmacht","ru":"доверенность","uz":"ishonch xati"},
      {"de":"vertreten","ru":"представлять","uz":"vakil bo'lmoq"},
      {"de":"einreichen","ru":"подавать (документы)","uz":"topshirmoq"},
      {"de":"die Frist","ru":"срок / дедлайн","uz":"muddat"},
      {"de":"ablaufen","ru":"истекать (о сроке)","uz":"muddati o'tmoq"},
      {"de":"verlängern","ru":"продлевать","uz":"uzaytirmoq"},
      {"de":"die Bescheinigung","ru":"справка","uz":"ma'lumotnoma"},
      {"de":"das Attest","ru":"медицинская справка","uz":"tibbiy ma'lumotnoma"},
      {"de":"die Urkunde","ru":"свидетельство (рождения и пр.)","uz":"guvohnoma"},
      {"de":"die Geburtsurkunde","ru":"свидетельство о рождении","uz":"tug'ilganlik guvohnomasi"},
      {"de":"die Heiratsurkunde","ru":"свидетельство о браке","uz":"nikoh guvohnomasi"},
      {"de":"das Melderegister","ru":"реестр регистрации","uz":"ro'yxatga olish rejestri"},
      {"de":"die Bürokratie","ru":"бюрократия","uz":"byurokratiya"},
      {"de":"der Antrag stellen","ru":"подавать заявление","uz":"ariza bermoq"},
      {"de":"der Widerspruch","ru":"возражение / апелляция","uz":"e'tiroz"},
      {"de":"die Behörde","ru":"ведомство","uz":"idora"},
      {"de":"das Amt","ru":"учреждение","uz":"muassasa"},
      {"de":"online erledigen","ru":"оформлять онлайн","uz":"onlayn hal qilmoq"},
      {"de":"die Wartenummer ziehen","ru":"взять талон","uz":"talon olmoq"},
      {"de":"das E-Government","ru":"электронное правительство","uz":"elektron hukumat"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Standesamt'?",
       "opts":["налоговая","центр занятости","ЗАГС","паспортный стол"],"ans":2},
      {"type":"fill","q":"Ich muss meine ___ bis April einreichen. (налоговую декларацию)",
       "opts":["Bescheinigung","Vollmacht","Steuererklärung","Urkunde"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'beglaubigen'?",
       "opts":["подавать заявление","заверять","продлевать","переводить"],"ans":1},
      {"type":"fill","q":"Der ___ übersetzt mündlich. (устный переводчик)",
       "opts":["Notar","Anwalt","Dolmetscher","Vertreter"],"ans":2},
      {"type":"choice","q":"Was ist 'die Aufenthaltserlaubnis'?",
       "opts":["гражданство","вид на жительство","доверенность","виза"],"ans":1},
      {"type":"fill","q":"Das Dokument ___ nächsten Monat ab. (истекает)",
       "opts":["verlängert","läuft","endet","läuft ab"],"ans":3},
      {"type":"choice","q":"Was bedeutet 'die Vollmacht'?",
       "opts":["справка","свидетельство","доверенность","заявление"],"ans":2},
      {"type":"fill","q":"Ich möchte meine Aufenthaltserlaubnis ___. (продлить)",
       "opts":["einreichen","beglaubigen","verlängern","vertreten"],"ans":2},
      {"type":"choice","q":"Was ist 'das E-Government'?",
       "opts":["электронная коммерция","электронное правительство","онлайн-магазин","интернет-банк"],"ans":1},
    ]
  },
  4: {  # Sport und Fitness
    "vocab_extra":[
      {"de":"das Aufwärmen","ru":"разминка","uz":"isitish"},
      {"de":"das Abkühlen","ru":"заминка","uz":"sovutish"},
      {"de":"der Trainingsplan","ru":"план тренировок","uz":"mashq rejasi"},
      {"de":"die Wiederholung (Rep)","ru":"повторение","uz":"takrorlash"},
      {"de":"der Satz (Set)","ru":"подход","uz":"set"},
      {"de":"die Hantel","ru":"гантель","uz":"gantel"},
      {"de":"die Langhanteln","ru":"штанга","uz":"shtanga"},
      {"de":"das Laufband","ru":"беговая дорожка","uz":"yugurish polkasi"},
      {"de":"das Fahrradergometer","ru":"велотренажёр","uz":"velotrenajer"},
      {"de":"der Crosstrainer","ru":"эллиптический тренажёр","uz":"elliptik trenajer"},
      {"de":"die Körperhaltung","ru":"осанка","uz":"postura"},
      {"de":"die Flexibilität","ru":"гибкость","uz":"egiluvchanlik"},
      {"de":"die Koordination","ru":"координация","uz":"koordinatsiya"},
      {"de":"die Reaktion","ru":"реакция","uz":"reaktsiya"},
      {"de":"das Gleichgewicht","ru":"равновесие","uz":"muvozanat"},
      {"de":"muskelaufbau","ru":"наращивание мышц","uz":"mushak to'plash"},
      {"de":"Fettabbau","ru":"сжигание жира","uz":"yog' yoqish"},
      {"de":"das Ausdauertraining","ru":"кардио-тренировка","uz":"chidamlilik mashqi"},
      {"de":"das Krafttraining","ru":"силовая тренировка","uz":"kuch mashqi"},
      {"de":"der Wettkampfsport","ru":"соревновательный спорт","uz":"musobaqaviy sport"},
      {"de":"der Amateursport","ru":"любительский спорт","uz":"havaskorlik sporti"},
      {"de":"der Profisport","ru":"профессиональный спорт","uz":"professional sport"},
      {"de":"das Olympische Spiele","ru":"Олимпийские игры","uz":"Olimpiya o'yinlari"},
      {"de":"die Weltmeisterschaft","ru":"чемпионат мира","uz":"jahon chempionati"},
      {"de":"die Europameisterschaft","ru":"чемпионат Европы","uz":"Yevropa chempionati"},
      {"de":"der Schiedsrichter","ru":"судья","uz":"hakam"},
      {"de":"die Mannschaft / das Team","ru":"команда","uz":"jamoa"},
      {"de":"der Kapitän","ru":"капитан","uz":"kapitan"},
      {"de":"der Trainer","ru":"тренер","uz":"trener"},
      {"de":"das Tor","ru":"гол / ворота","uz":"gol / darvoza"},
      {"de":"schießen","ru":"бить (по мячу)","uz":"zarba urmoq"},
      {"de":"der Spielstand","ru":"счёт игры","uz":"o'yin hisobi"},
      {"de":"die Verlängerung","ru":"дополнительное время","uz":"qo'shimcha vaqt"},
      {"de":"der Elfmeter / Penalty","ru":"пенальти","uz":"jarima zarbasi"},
      {"de":"der Pokal","ru":"кубок","uz":"kubоk"},
      {"de":"die Medaille","ru":"медаль","uz":"medal"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Aufwärmen'?",
       "opts":["силовая тренировка","разминка","заминка","кардио"],"ans":1},
      {"type":"fill","q":"Er macht 3 ___ mit je 12 Wiederholungen. (подхода)",
       "opts":["Sätze","Runden","Übungen","Wiederholungen"],"ans":0},
      {"type":"choice","q":"Was ist 'die Weltmeisterschaft'?",
       "opts":["Олимпийские игры","кубок","чемпионат мира","чемпионат Европы"],"ans":2},
      {"type":"fill","q":"Der ___ pfeift Abseits. (судья)",
       "opts":["Trainer","Kapitän","Schiedsrichter","Spieler"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'der Fettabbau'?",
       "opts":["наращивание мышц","сжигание жира","кардио-тренировка","разминка"],"ans":1},
      {"type":"fill","q":"Das Spiel geht in die ___. Es steht 1:1. (дополнительное время)",
       "opts":["Pause","Verlängerung","Halbzeit","Nachspielzeit"],"ans":1},
      {"type":"choice","q":"Was ist 'die Medaille'?",
       "opts":["кубок","призовой фонд","медаль","трофей"],"ans":2},
      {"type":"fill","q":"Ich trainiere meine ___ mit Yoga. (гибкость)",
       "opts":["Kraft","Ausdauer","Koordination","Flexibilität"],"ans":3},
      {"type":"choice","q":"Was bedeutet 'das Krafttraining'?",
       "opts":["кардио-тренировка","силовая тренировка","разминка","аэробика"],"ans":1},
    ]
  },
  5: {  # Familie und Generationen
    "vocab_extra":[
      {"de":"der Stammbaum","ru":"генеалогическое дерево","uz":"nasl daraxti"},
      {"de":"die Ahnen","ru":"предки","uz":"ajdodlar"},
      {"de":"die Nachkommen","ru":"потомки","uz":"avlodlar"},
      {"de":"das Erbe (Tradition)","ru":"наследие","uz":"meros"},
      {"de":"die Generationenlücke","ru":"разрыв между поколениями","uz":"avlodlar o'rtasidagi farq"},
      {"de":"die Fürsorge","ru":"уход / забота","uz":"g'amxo'rlik"},
      {"de":"der Pflegefall","ru":"лежачий больной","uz":"parvarishga muhtoj odam"},
      {"de":"die Altenpflege","ru":"уход за пожилыми","uz":"keksalarga g'amxo'rlik"},
      {"de":"das Pflegeheim","ru":"дом престарелых","uz":"keksalar uyi"},
      {"de":"die Kinderbetreuung","ru":"уход за детьми","uz":"bolalarga g'amxo'rlik"},
      {"de":"die Kita (Kindertagesstätte)","ru":"детский сад","uz":"bolalar bog'chasi"},
      {"de":"der Hort","ru":"продлёнка / группа продлённого дня","uz":"maktabdan keyingi guruh"},
      {"de":"alleinerziehend","ru":"одинокий родитель","uz":"yakka ota-ona"},
      {"de":"die Patchworkfamilie","ru":"смешанная семья","uz":"aralash oila"},
      {"de":"die Adoptivfamilie","ru":"приёмная семья","uz":"asrab oluvchi oila"},
      {"de":"die Gleichberechtigung","ru":"равноправие","uz":"teng huquqlilik"},
      {"de":"die Rollenverteilung","ru":"распределение ролей","uz":"rollarni taqsimlash"},
      {"de":"das Patriarchat","ru":"патриархат","uz":"patriarxat"},
      {"de":"das Matriarchat","ru":"матриархат","uz":"matriarxat"},
      {"de":"der Generationenvertrag","ru":"межпоколенческий договор","uz":"avlodlararo shartnoma"},
      {"de":"das Kindergeld","ru":"детское пособие","uz":"bola nafaqasi"},
      {"de":"das Elterngeld","ru":"родительское пособие","uz":"ota-ona nafaqasi"},
      {"de":"die Rente","ru":"пенсия","uz":"pensiya"},
      {"de":"der Demograf","ru":"демограф","uz":"demograf"},
      {"de":"die Bevölkerungsalterung","ru":"старение населения","uz":"aholi qariishi"},
      {"de":"der Geburtenrückgang","ru":"снижение рождаемости","uz":"tug'ilishning pasayishi"},
      {"de":"die Einwanderung","ru":"иммиграция","uz":"immigratsiya"},
      {"de":"multikulturelles Zusammenleben","ru":"многокультурное сосуществование","uz":"ko'p madaniyatli birgalikda yashash"},
      {"de":"der Integrationsprozess","ru":"процесс интеграции","uz":"integratsiya jarayoni"},
      {"de":"das Heimweh","ru":"ностальгия","uz":"uyga qaytish ishtiyoqi"},
      {"de":"die Verwurzelung","ru":"укоренённость","uz":"ildiz otganlik"},
      {"de":"die kulturelle Identität","ru":"культурная идентичность","uz":"madaniy o'zlik"},
      {"de":"der Respekt vor Älteren","ru":"уважение к пожилым","uz":"keksalarga hurmat"},
      {"de":"die Familiengeschichte","ru":"история семьи","uz":"oila tarixi"},
      {"de":"die Familienfeier","ru":"семейное торжество","uz":"oilaviy bayram"},
      {"de":"zusammenhalten","ru":"держаться вместе","uz":"birgalikda turmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Stammbaum'?",
       "opts":["история семьи","генеалогическое дерево","семейный альбом","семейное торжество"],"ans":1},
      {"type":"fill","q":"Sie ist ___erziehend. Sie hat keine Partner. (одинокий родитель)",
       "opts":["allein","einzel","solo","selbst"],"ans":0},
      {"type":"choice","q":"Was ist 'die Kita'?",
       "opts":["продлёнка","начальная школа","детский сад","дом престарелых"],"ans":2},
      {"type":"fill","q":"Der ___ beschreibt eine sinkende Geburtenrate. (снижение рождаемости)",
       "opts":["Stammbaum","Generationenvertrag","Geburtenrückgang","Demografe"],"ans":2},
      {"type":"choice","q":"Was ist 'das Elterngeld'?",
       "opts":["детское пособие","пенсия","родительское пособие","алименты"],"ans":2},
      {"type":"fill","q":"Die ___ ist wichtig: alle haben gleiche Rechte. (равноправие)",
       "opts":["Rollenverteilung","Gleichberechtigung","Fürsorge","Demografie"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'zusammenhalten'?",
       "opts":["спорить","держаться вместе","расставаться","игнорировать"],"ans":1},
      {"type":"fill","q":"Er lebt im ___. Er ist 90 Jahre alt. (дом престарелых)",
       "opts":["Hort","Pflegeheim","Kindergarten","Wohnheim"],"ans":1},
      {"type":"choice","q":"Was ist 'das Heimweh'?",
       "opts":["укоренённость","интеграция","ностальгия","идентичность"],"ans":2},
    ]
  },
  6: {  # Essen gehen / Restaurant
    "vocab_extra":[
      {"de":"das Amuse-Bouche","ru":"закуска от шефа","uz":"oshpazdan taom"},
      {"de":"der Aperitif","ru":"аперитив","uz":"aperitiv"},
      {"de":"der Digestif","ru":"дижестив","uz":"dijestiv"},
      {"de":"die Weinkarte","ru":"карта вин","uz":"vino ro'yxati"},
      {"de":"der Sommelier","ru":"сомелье","uz":"someler"},
      {"de":"das Tagesmenü","ru":"бизнес-ланч / дневное меню","uz":"kunlik menyu"},
      {"de":"à la carte","ru":"по меню","uz":"menyudan tanlash"},
      {"de":"die Allergenkennzeichnung","ru":"маркировка аллергенов","uz":"allergen belgilash"},
      {"de":"vegan","ru":"веган","uz":"vegan"},
      {"de":"halal","ru":"халяль","uz":"halol"},
      {"de":"koscher","ru":"кошерный","uz":"koʻsher"},
      {"de":"die Spezialität des Hauses","ru":"фирменное блюдо","uz":"uy ixtisosligi"},
      {"de":"das Saisongemüse","ru":"сезонные овощи","uz":"mavsumiy sabzavotlar"},
      {"de":"frisch zubereitet","ru":"свежеприготовленный","uz":"yangi tayyorlangan"},
      {"de":"hausgemacht","ru":"домашнего приготовления","uz":"uyda tayyorlangan"},
      {"de":"die Küche (Stil)","ru":"кухня (стиль)","uz":"oshxona (uslub)"},
      {"de":"die asiatische / mediterrane Küche","ru":"азиатская / средиземноморская кухня","uz":"osiyo / o'rta yer dengizi oshxonasi"},
      {"de":"die Küchenutensilien","ru":"кухонная утварь","uz":"oshxona jihozlari"},
      {"de":"das Rezept nachkochen","ru":"готовить по рецепту","uz":"retsept bo'yicha pishirmoq"},
      {"de":"würzen","ru":"приправлять","uz":"ziravorlash"},
      {"de":"die Gewürze","ru":"специи","uz":"ziravorlar"},
      {"de":"mild / scharf","ru":"мягкий / острый","uz":"yumshoq / achchiq"},
      {"de":"das Buffet","ru":"шведский стол","uz":"bufet"},
      {"de":"das Catering","ru":"кейтеринг","uz":"keytering"},
      {"de":"der Caterer","ru":"поставщик питания","uz":"ovqat yetkazib beruvchi"},
      {"de":"die Tischreservierung","ru":"бронирование стола","uz":"stol band qilish"},
      {"de":"der Stammgast","ru":"постоянный клиент","uz":"doimiy mijoz"},
      {"de":"der Michelin-Stern","ru":"звезда Мишлена","uz":"Mishlen yulduzi"},
      {"de":"gehobene Gastronomie","ru":"ресторан высокой кухни","uz":"yuqori darajali restoran"},
      {"de":"die Kritik / Bewertung","ru":"отзыв / оценка","uz":"sharh / baho"},
      {"de":"der Stammlokal","ru":"любимый ресторан","uz":"sevimli restoran"},
      {"de":"mitnehmen / Lieferung","ru":"навынос / доставка","uz":"olib ketish / yetkazib berish"},
      {"de":"die App-Bestellung","ru":"заказ через приложение","uz":"ilova orqali buyurtma"},
      {"de":"Delivery-Dienste","ru":"службы доставки","uz":"yetkazib berish xizmatlari"},
      {"de":"das Trinkwasser","ru":"питьевая вода","uz":"ichimlik suvi"},
      {"de":"die Portion für zwei","ru":"порция на двоих","uz":"ikki kishilik porsiya"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Sommelier'?",
       "opts":["официант","повар","сомелье","управляющий"],"ans":2},
      {"type":"fill","q":"Das Essen ist ___. Es enthält keine tierischen Produkte. (веган)",
       "opts":["vegetarisch","halal","vegan","koscher"],"ans":2},
      {"type":"choice","q":"Was bedeutet 'hausgemacht'?",
       "opts":["свежеприготовленный","сезонный","домашнего приготовления","фирменный"],"ans":2},
      {"type":"fill","q":"Ich möchte einen Tisch für heute Abend ___. (забронировать)",
       "opts":["bestellen","reservieren","buchen","kaufen"],"ans":1},
      {"type":"choice","q":"Was ist 'das Tagesmenü'?",
       "opts":["фирменное блюдо","меню","бизнес-ланч","карта вин"],"ans":2},
      {"type":"fill","q":"Das Restaurant hat einen ___. Das Essen ist sehr gut! (звезду Мишлена)",
       "opts":["Stammgast","Michelin-Stern","Aperitif","Catering"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'würzen'?",
       "opts":["готовить","нарезать","приправлять","жарить"],"ans":2},
      {"type":"fill","q":"Ich bestellte über die ___ ein Essen. (приложение)",
       "opts":["Tischreservierung","Weinkarte","App-Bestellung","Kritik"],"ans":2},
      {"type":"choice","q":"Was ist 'à la carte'?",
       "opts":["по меню","шведский стол","бизнес-ланч","комплексный обед"],"ans":0},
    ]
  },
  7: {  # Politik und Gesellschaft
    "vocab_extra":[
      {"de":"die Verfassung","ru":"конституция","uz":"konstitutsiya"},
      {"de":"das Grundgesetz","ru":"основной закон","uz":"asosiy qonun"},
      {"de":"der Bundestag","ru":"бундестаг","uz":"Bundestag"},
      {"de":"der Bundesrat","ru":"бундесрат","uz":"Bundesrat"},
      {"de":"der Bundeskanzler","ru":"федеральный канцлер","uz":"federal kantsler"},
      {"de":"der Bundespräsident","ru":"федеральный президент","uz":"federal prezident"},
      {"de":"der Landtag","ru":"ландтаг","uz":"Landtag"},
      {"de":"die Koalition","ru":"коалиция","uz":"koalitsiya"},
      {"de":"die Opposition","ru":"оппозиция","uz":"oppozitsiya"},
      {"de":"der Abgeordnete","ru":"депутат","uz":"deputat"},
      {"de":"der Wahlkampf","ru":"предвыборная кампания","uz":"saylov kampaniyasi"},
      {"de":"das Wahlprogramm","ru":"предвыборная программа","uz":"saylov dasturi"},
      {"de":"abstimmen","ru":"голосовать","uz":"ovoz bermoq"},
      {"de":"die Volksabstimmung","ru":"референдум","uz":"referendum"},
      {"de":"das Mehrheitsprinzip","ru":"принцип большинства","uz":"ko'pchilik printsipi"},
      {"de":"das Verhältniswahlrecht","ru":"пропорциональное представительство","uz":"proporsional vakillik"},
      {"de":"die Meinungsfreiheit","ru":"свобода мнений","uz":"fikr erkinligi"},
      {"de":"die Versammlungsfreiheit","ru":"свобода собраний","uz":"yig'ilish erkinligi"},
      {"de":"die Religionsfreiheit","ru":"свобода вероисповедания","uz":"din erkinligi"},
      {"de":"die Menschenrechte","ru":"права человека","uz":"inson huquqlari"},
      {"de":"der Rechtsstaat","ru":"правовое государство","uz":"huquqiy davlat"},
      {"de":"die Gewaltenteilung","ru":"разделение властей","uz":"hokimiyat taqsimlanishi"},
      {"de":"die legislative Gewalt","ru":"законодательная власть","uz":"qonun chiqaruvchi hokimiyat"},
      {"de":"die exekutive Gewalt","ru":"исполнительная власть","uz":"ijro etuvchi hokimiyat"},
      {"de":"die judikative Gewalt","ru":"судебная власть","uz":"sud hokimiyati"},
      {"de":"die Lobbyarbeit","ru":"лоббирование","uz":"lobbizm"},
      {"de":"die NGO","ru":"НКО","uz":"NKT"},
      {"de":"die Zivilgesellschaft","ru":"гражданское общество","uz":"fuqarolik jamiyati"},
      {"de":"der Aktivismus","ru":"активизм","uz":"aktivizm"},
      {"de":"demonstrieren","ru":"демонстрировать","uz":"namoyish qilmoq"},
      {"de":"der Protest","ru":"протест","uz":"norozilik"},
      {"de":"die Petition","ru":"петиция","uz":"petitsiya"},
      {"de":"unterschreiben","ru":"подписывать","uz":"imzolash"},
      {"de":"die Sozialleistungen","ru":"социальные льготы","uz":"ijtimoiy imtiyozlar"},
      {"de":"die Steuern zahlen","ru":"платить налоги","uz":"soliq to'lamoq"},
      {"de":"das Gemeinwohl","ru":"общее благо","uz":"umumiy farovonlik"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'der Bundestag'?",
       "opts":["суд","бундестаг (парламент)","правительство","оппозиция"],"ans":1},
      {"type":"fill","q":"Die ___ garantiert die Rechte der Bürger. (конституция)",
       "opts":["Koalition","Verfassung","Opposition","Wahl"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'abstimmen'?",
       "opts":["голосовать","дискутировать","демонстрировать","петиция"],"ans":0},
      {"type":"fill","q":"Sie haben die ___ gewonnen. Mehr als 50% der Stimmen! (большинство)",
       "opts":["Koalition","Mehrheit","Opposition","Petition"],"ans":1},
      {"type":"choice","q":"Was ist 'die Meinungsfreiheit'?",
       "opts":["свобода собраний","свобода вероисповедания","свобода мнений","свобода прессы"],"ans":2},
      {"type":"fill","q":"Der ___ steht an der Spitze der deutschen Regierung. (канцлер)",
       "opts":["Bundespräsident","Abgeordnete","Bundeskanzler","Landtag"],"ans":2},
      {"type":"choice","q":"Was ist 'die Gewaltenteilung'?",
       "opts":["принцип большинства","разделение властей","пропорциональное представительство","коалиция"],"ans":1},
      {"type":"fill","q":"Sie ___ für mehr Klimaschutz. (демонстрируют)",
       "opts":["abstimmen","demonstrieren","unterschreiben","wählen"],"ans":1},
      {"type":"choice","q":"Was ist 'das Gemeinwohl'?",
       "opts":["лоббирование","протест","общее благо","гражданское общество"],"ans":2},
    ]
  },
  8: {  # Feste und Traditionen (weltweit)
    "vocab_extra":[
      {"de":"das Nowruz","ru":"Навруз","uz":"Navro'z"},
      {"de":"das Diwali","ru":"Дивали","uz":"Diwali"},
      {"de":"das Eid al-Fitr","ru":"Ид аль-Фитр","uz":"Ro'za hayiti"},
      {"de":"das Eid al-Adha","ru":"Ид аль-Адха","uz":"Qurbon hayiti"},
      {"de":"das Chinesische Neujahr","ru":"Китайский Новый год","uz":"Xitoy yangi yili"},
      {"de":"die Gepflogenheit","ru":"привычка / обычай","uz":"odat"},
      {"de":"der Ritus","ru":"ритуал","uz":"ritual"},
      {"de":"die Zeremonie","ru":"церемония","uz":"marosim"},
      {"de":"die Symbolik","ru":"символика","uz":"ramziylik"},
      {"de":"heilig / sakral","ru":"священный","uz":"muqaddas"},
      {"de":"profan","ru":"мирской / светский","uz":"dunyoviy"},
      {"de":"die Prozession","ru":"шествие","uz":"yurish"},
      {"de":"der Pilger","ru":"паломник","uz":"hoji / ziyoratchi"},
      {"de":"die Wallfahrt","ru":"паломничество","uz":"ziyorat"},
      {"de":"der Mythos","ru":"миф","uz":"mif"},
      {"de":"die Legende","ru":"легенда","uz":"afsona"},
      {"de":"der Volksglaube","ru":"народное верование","uz":"xalq e'tiqodi"},
      {"de":"die Volksmusik","ru":"народная музыка","uz":"xalq musiqasi"},
      {"de":"der Volkstanz","ru":"народный танец","uz":"xalq raqsi"},
      {"de":"die Tracht","ru":"народный костюм","uz":"milliy kiyim"},
      {"de":"das Dirndl","ru":"дирндль (баварский костюм)","uz":"dirndl (Bavariya kiyimi)"},
      {"de":"der Lederhosen","ru":"кожаные штаны (баварские)","uz":"teri shim (Bavariya)"},
      {"de":"die Gastfreundschaft","ru":"гостеприимство","uz":"mehmondo'stlik"},
      {"de":"Gäste empfangen","ru":"принимать гостей","uz":"mehmon qabul qilmoq"},
      {"de":"die Tafelrunde","ru":"застолье","uz":"dasturxon"},
      {"de":"der Toast","ru":"тост","uz":"tost"},
      {"de":"die Rede halten","ru":"произносить речь","uz":"nutq so'zlamoq"},
      {"de":"das Jubiläum feiern","ru":"отмечать юбилей","uz":"yubiley nishonlamoq"},
      {"de":"die Familientradition","ru":"семейная традиция","uz":"oila an'anasi"},
      {"de":"vererben","ru":"передавать по наследству","uz":"meros qoldirmoq"},
      {"de":"pflegen","ru":"поддерживать (традиции)","uz":"avaylash / qo'llab-quvvatlash"},
      {"de":"weitergeben","ru":"передавать","uz":"uzatmoq"},
      {"de":"der Ursprung","ru":"происхождение","uz":"kelib chiqish"},
      {"de":"entstehen","ru":"возникать","uz":"paydo bo'lmoq"},
      {"de":"der Wandel","ru":"изменение","uz":"o'zgarish"},
      {"de":"sich bewahren","ru":"сохраняться","uz":"saqlanmoq"},
    ],
    "exercises_extra":[
      {"type":"choice","q":"Was ist 'das Nowruz'?",
       "opts":["Рождество","Пасха","Навруз","Хэллоуин"],"ans":2},
      {"type":"fill","q":"Die ___ zeigen die Herkunft und Geschichte eines Volkes. (традиции)",
       "opts":["Riten","Symbole","Traditionen","Feste"],"ans":2},
      {"type":"choice","q":"Was ist 'die Tracht'?",
       "opts":["народный танец","народная музыка","народный костюм","народный обычай"],"ans":2},
      {"type":"fill","q":"Er ___ die Familientradition an seine Kinder weiter. (передаёт)",
       "opts":["pflegt","gibt","erbt","bewahrt"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'heilig'?",
       "opts":["мирской","светский","священный","традиционный"],"ans":2},
      {"type":"fill","q":"Die Zeremonie ist ein wichtiger ___. (ритуал)",
       "opts":["Mythos","Ritus","Volksglaube","Toast"],"ans":1},
      {"type":"choice","q":"Was ist 'die Gastfreundschaft'?",
       "opts":["паломничество","застолье","гостеприимство","тост"],"ans":2},
      {"type":"fill","q":"Der Brauch hat seinen ___ im Mittelalter. (происхождение)",
       "opts":["Wandel","Ursprung","Ritus","Mythos"],"ans":1},
      {"type":"choice","q":"Was bedeutet 'pflegen'?",
       "opts":["передавать","возникать","поддерживать","изменять"],"ans":2},
    ]
  },
}
